Repository woowacourse-teams/2024-review-me, pull requests merged in 2024-09, with the labels that each got.

#547 [FE] refactor: Input의 type에 올 수 있는 값을 html에서 제공하는 값으로 제한
  frontend/src/components/common/Input/index.tsx
Labels: 🍀 FE, 우선순위: 중, 🛠️ 리팩터링, 🍰 초간단

#557 [BE] fixture 에 static 키워드 적용
  backend/src/test/java/reviewme/fixture/OptionGroupFixture.java
  backend/src/test/java/reviewme/fixture/OptionItemFixture.java
  backend/src/test/java/reviewme/fixture/QuestionFixture.java
  backend/src/test/java/reviewme/fixture/ReviewGroupFixture.java
  backend/src/test/java/reviewme/fixture/SectionFixture.java
  backend/src/test/java/reviewme/fixture/TemplateFixture.java
Labels: ✨ BE, ♻️ 테스트, 🍰 초간단

#555 [FE] fix: 캐러셀 왼쪽/오른쪽 버튼 연속 클릭 시, 슬라이드 멈추는 현상 해결
  frontend/src/pages/HomePage/components/Carousel/index.tsx
Labels: 🍀 FE, 🐛 버그

#542 [FE] refactor: URLGeneratorForm의 상태와 책임 분산
  frontend/src/hooks/usePasswordValidation.ts
  frontend/src/pages/HomePage/components/Inputs/InputField.tsx
  frontend/src/pages/HomePage/components/Inputs/PasswordField.tsx
  frontend/src/pages/HomePage/components/Inputs/ProjectNameField.tsx
  frontend/src/pages/HomePage/components/Inputs/RevieweeNameField.tsx
  frontend/src/pages/HomePage/components/Inputs/index.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/types/index.ts
Labels: 🍀 FE, 우선순위: 중, 🛠️ 리팩터링, 😁 우하하

#564 [FE] fix: textarea에서 공백만 있는 입력인 경우 에러 메세지를 띄우고, 유효하지 않은 입력으로 간주
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useTextAnswer/index.ts
Labels: 🍀 FE, 우선순위: 중, 🐛 버그

#563 [FE] fix: 객관식 문항의 최소, 최대 선택 개수가 같은 경우 문구 추가
  frontend/src/pages/ReviewWritingPage/form/components/QnABox/index.tsx
Labels: 🍀 FE

#565 [FE] feat : 선택 질문에 대한 최소 조건 변경
  frontend/src/pages/ReviewWritingPage/form/components/QnABox/index.tsx
  frontend/src/pages/ReviewWritingPage/form/components/QnABox/style.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/multipleChoice/useUpdateMultipleChoiceAnswer/index.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/multipleChoice/useUpdateMultipleChoiceAnswer/test.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useTextAnswer/index.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useTextAnswer/test.tsx
Labels: 🍀 FE, 🚀 기능

#549 [BE] refactor: `@Transactional` import 패키지 수정
  backend/src/main/java/reviewme/DatabaseInitializer.java
  backend/src/test/java/reviewme/support/DatabaseCleaner.java
Labels: 🛠️ 리팩터링, 🍰 초간단

#566 [FE] refactor: 서술형 필수 질문에 최소/최대 문구 안내 추가
  frontend/src/pages/ReviewWritingPage/constants/index.ts
  frontend/src/pages/ReviewWritingPage/constants/textarea.ts
  frontend/src/pages/ReviewWritingPage/form/components/QnABox/index.tsx
  frontend/src/pages/ReviewWritingPage/form/components/TextAnswer/index.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useTextAnswer/index.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useTextAnswer/test.tsx
Labels: 우선순위: 하, 🛠️ 리팩터링

#567 [FE] refactor: 클릭 이벤트가 있는 요소 드래그 막기
  frontend/src/components/common/Breadcrumb/index.tsx
  frontend/src/components/common/Breadcrumb/styles.ts
  frontend/src/components/common/CheckboxItem/index.tsx
  frontend/src/components/common/UndraggableWrapper/index.tsx
  frontend/src/components/common/UndraggableWrapper/styles.ts
  frontend/src/components/layouts/Topbar/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링

#570 [FE] feat : 요청 데이터 특징에 따라 useQuery staleTime 지정
  frontend/src/hooks/review/useGetDetailedReview/index.ts
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/hooks/reviewGroup/useGetReviewGroupData/index.ts
Labels: 🍀 FE, 🚀 기능

#577 [FE] feat: 웹 페이지 탭 전환 시, 리액트 쿼리 api 요청 막기
  frontend/src/index.tsx
Labels: 🍀 FE, 🚀 기능

#578 [FE] chore: 서술형 답변에 최대 max의 2배 길이 문자열을 붙여 넣어도 문자열이 잘리지 않도록 수정
  frontend/src/pages/ReviewWritingPage/constants/textarea.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useTextAnswer/index.ts
Labels: 🍀 FE, 🐛 버그

#580 [FE] fix: 이전 버튼이 눌리지 않는 현상 수정
  frontend/src/pages/ReviewWritingPage/slider/components/CardSlider/index.tsx
  frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
Labels: 🍀 FE, 🐛 버그, 😱 긴급, 😁 우하하

#568 [BE] feat: 150자가 넘어가는 경우 `...` 말줄임표 추가
  backend/src/main/java/reviewme/review/service/ReviewPreviewGenerator.java
  backend/src/test/java/reviewme/review/service/ReviewPreviewGeneratorTest.java
Labels: ✨ BE, 🚀 기능, 🍰 초간단

#552 [BE] test: 객관식 검증, 리뷰 생성 테스트에 픽스처를 적용
  backend/src/test/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidatorTest.java
  backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#556 [BE] test: 리뷰 목록 조회, 리뷰 상세 조회 테스트에 픽스처를 적용
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링, ♻️ 테스트

#582 [BE] test: Fixture 가 적용되지 않은 테스트 반영
  backend/src/test/java/reviewme/question/repository/OptionItemRepositoryTest.java
  backend/src/test/java/reviewme/question/repository/QuestionRepositoryTest.java
  backend/src/test/java/reviewme/review/domain/ReviewTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
  backend/src/test/java/reviewme/template/domain/SectionTest.java
  backend/src/test/java/reviewme/template/repository/SectionRepositoryTest.java
  backend/src/test/java/reviewme/template/service/TemplateMapperTest.java
  backend/src/test/java/reviewme/template/service/TemplateServiceTest.java
Labels: ✨ BE, ♻️ 테스트

#595 [FE] fix : 캐러셀 frame drop 최소화
  frontend/src/components/common/Carousel/index.tsx
  frontend/src/components/common/Carousel/style.ts
  frontend/src/pages/HomePage/components/InfinityCarousel/index.tsx
  frontend/src/pages/HomePage/components/InfinityCarousel/styles.ts
  frontend/src/pages/HomePage/components/ReviewMeOverview/index.tsx
  frontend/src/pages/HomePage/components/index.ts
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingPage/form/components/ReviewWritingCard/index.tsx
  frontend/src/pages/ReviewWritingPage/progressBar/hooks/useStepList/test.tsx
  frontend/src/pages/ReviewWritingPage/slider/components/CardSlider/index.tsx
  frontend/src/pages/ReviewWritingPage/slider/hooks/index.ts
  frontend/src/pages/ReviewWritingPage/slider/hooks/useSlideHeight.ts
Labels: 🍀 FE

#596 [FE] refactor: svg 파일 최적화
  frontend/package.json
  frontend/src/assets/usageCarosel3.svg
  frontend/src/assets/usageCarousel1.svg
  frontend/src/assets/usageCarousel2.svg
  frontend/src/assets/usageCarousel3.svg
  frontend/src/pages/HomePage/components/ReviewMeOverview/index.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🍀 FE, 우선순위: 중, 🛠️ 리팩터링

#606 [FE] refactor: 페이지별로 JS 파일 분리
  frontend/src/components/error/ErrorSuspenseContainer/index.tsx
  frontend/src/index.tsx
  frontend/webpack.config.js
Labels: 🍀 FE, 🛠️ 리팩터링

#605 [FE] feat : 폰트 preload 적용
  frontend/public/index.html
  frontend/src/pages/ReviewWritingPage/progressBar/hooks/useStepList/test.tsx
  frontend/src/styles/globalStyles.ts
  frontend/webpack.config.js
Labels: 🍀 FE

#610 [FE] feat : js 번들 크기 압축
  frontend/src/pages/HomePage/components/Inputs/PasswordField.tsx
  frontend/src/pages/HomePage/components/Inputs/ProjectNameField.tsx
  frontend/src/pages/HomePage/components/Inputs/RevieweeNameField.tsx
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/HomePage/hooks/usePostDataForReviewRequestCode/index.ts
  frontend/src/pages/HomePage/hooks/usePostDataForReviewRequestCode/test.tsx
  frontend/src/pages/HomePage/utils/validateInput/index.ts
  frontend/src/pages/HomePage/utils/validateInput/test.ts
  frontend/tempTest.test.ts
  frontend/webpack.config.js
Labels: 🍀 FE

#601 [BE] chore: flyway 설정
  backend/build.gradle
  backend/src/main/resources/schema-doc.sql
Labels: ✨ BE, 🌏 인프라

#589 [BE] refactor: 필수 질문이 아닌 경우 최소 글자수 제한 제거
  backend/src/main/java/reviewme/review/domain/exception/InvalidTextAnswerLengthException.java
  backend/src/main/java/reviewme/review/service/module/TextAnswerValidator.java
  backend/src/test/java/reviewme/review/service/module/TextAnswerValidatorTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#616 [FE] feat: 반응형 유틸리티 함수 구현
  frontend/src/styles/theme.ts
  frontend/src/utils/media.ts
Labels: 🍀 FE, 🚀 기능

#614 [FE] fix : ErrorPage과 App의 레이아웃(=DOM 구조)다른 오류 수정
  frontend/src/App.tsx
  frontend/src/components/layouts/Main/index.tsx
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/components/layouts/PageLayout/index.tsx
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/components/layouts/Sidebar/styles.ts
  frontend/src/components/layouts/Topbar/components/SidebarOpenButton/index.tsx
  frontend/src/components/layouts/Topbar/components/SidebarOpenButton/styles.ts
  frontend/src/components/layouts/Topbar/index.tsx
  frontend/src/components/layouts/index.tsx
  frontend/src/pages/ErrorPage/index.tsx
  frontend/src/styles/theme.ts
Labels: 🍀 FE, 🐛 버그, 🍰 초간단

#612 [FE] fix : 리뷰 제출 실패 시, ErrorPage가 아닌 모달을 띄우기
  frontend/src/components/common/modals/AlertModal/styles.ts
  frontend/src/components/common/modals/ErrorAlertModal/index.tsx
  frontend/src/pages/ReviewWritingPage/constants/modal.ts
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useSubmitAnswers.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/useMutateReview/test.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/CardFormModalContainer/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitCheckModal/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitErrorModal/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitErrorModal/style.ts
Labels: 🍀 FE, 🐛 버그

#632 [FE] fix: media 유틸리티 함수 수정
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.ts
  frontend/src/utils/media.ts
Labels: 🍀 FE, 🐛 버그

#629 [FE] design: 리뷰 작성 페이지(프로그레스 바 제외) 반응형 구현
  frontend/src/components/common/Breadcrumb/styles.ts
  frontend/src/components/common/Checkbox/index.tsx
  frontend/src/components/common/CheckboxItem/styles.ts
  frontend/src/components/common/modals/ConfirmModal/styles.ts
  frontend/src/components/common/modals/ContentModal/styles.ts
  frontend/src/index.tsx
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/styles.ts
  frontend/src/pages/ReviewWritingPage/form/components/MultipleChoiceAnswer/index.tsx
  frontend/src/pages/ReviewWritingPage/form/components/MultipleChoiceAnswer/style.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/useCurrentCardIndex.ts
  frontend/src/pages/ReviewWritingPage/layout/components/ReviewWritingCardLayout/style.ts
  frontend/src/pages/ReviewWritingPage/modals/components/AnswerListRecheckModal/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/AnswerListRecheckModal/styles.ts
  frontend/src/pages/ReviewWritingPage/modals/components/NavigateBlockerModal/style.ts
  frontend/src/pages/ReviewWritingPage/modals/components/StrengthUnCheckModal/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/StrengthUnCheckModal/style.ts
  frontend/src/pages/ReviewWritingPage/modals/components/index.tsx
  frontend/src/pages/ReviewWritingPage/slider/components/CardSlider/style.ts
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.ts
Labels: 🍀 FE, 🎨 디자인

#627 [FE] design : 모바일 사이즈에서 스크롤 바, body padding-right 수정
  frontend/src/styles/globalStyles.ts
Labels: 🍀 FE, 🎨 디자인

#592 [BE] refactor: 예외별 로그 레벨을 재조정하고 로깅에서의 중복을 제거한다.
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/global/exception/DataInconsistencyException.java
  backend/src/main/java/reviewme/global/exception/UnexpectedRequestException.java
  backend/src/main/java/reviewme/question/domain/exception/QuestionNotFoundException.java
  backend/src/main/java/reviewme/review/domain/CheckboxAnswers.java
  backend/src/main/java/reviewme/review/domain/exception/CategoryOptionByReviewNotFoundException.java
  backend/src/main/java/reviewme/review/domain/exception/InvalidProjectNameLengthException.java
  backend/src/main/java/reviewme/review/domain/exception/InvalidReviewAccessByReviewGroupException.java
  backend/src/main/java/reviewme/review/domain/exception/InvalidRevieweeNameLengthException.java
  backend/src/main/java/reviewme/review/domain/exception/MissingCheckboxAnswerForQuestionException.java
  backend/src/main/java/reviewme/review/domain/exception/MissingTextAnswerForQuestionException.java
  backend/src/main/java/reviewme/review/domain/exception/QuestionNotAnsweredException.java
  backend/src/main/java/reviewme/review/domain/exception/ReviewGroupNotFoundByGroupAccessCodeException.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedNotProvidedOptionItemException.java
  backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedTextException.java
  backend/src/main/java/reviewme/review/service/exception/InvalidTextAnswerLengthException.java
  backend/src/main/java/reviewme/review/service/exception/MissingRequiredQuestionException.java
  backend/src/main/java/reviewme/review/service/exception/OptionGroupNotFoundByQuestionIdException.java
  backend/src/main/java/reviewme/review/service/exception/OptionItemNotFoundBySelectedOptionId.java
  backend/src/main/java/reviewme/review/service/exception/ReviewGroupNotFoundByCodesException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewGroupNotFoundByReviewRequestCodeException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewNotFoundException.java
  backend/src/main/java/reviewme/review/service/exception/SelectedOptionItemCountOutOfRangeException.java
  backend/src/main/java/reviewme/review/service/exception/SubmittedQuestionAndProvidedQuestionMismatchException.java
  backend/src/main/java/reviewme/review/service/exception/SubmittedQuestionNotFoundException.java
  backend/src/main/java/reviewme/review/service/exception/TextAnswerIncludedOptionItemException.java
  backend/src/main/java/reviewme/review/service/exception/UnnecessaryQuestionIncludedException.java
  backend/src/main/java/reviewme/review/service/module/AnswerMapper.java
  backend/src/main/java/reviewme/review/service/module/CheckBoxAnswerValidator.java
  backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
  backend/src/main/java/reviewme/review/service/module/ReviewMapper.java
  backend/src/main/java/reviewme/review/service/module/TextAnswerValidator.java
  backend/src/main/java/reviewme/reviewgroup/domain/exception/InvalidGroupAccessCodeFormatException.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/template/service/TemplateService.java
  backend/src/main/java/reviewme/template/service/exception/MissingOptionItemsInOptionGroupException.java
  backend/src/main/java/reviewme/template/service/exception/QuestionInSectionNotFoundException.java
  backend/src/main/java/reviewme/template/service/exception/SectionInTemplateNotFoundException.java
  backend/src/main/java/reviewme/template/service/exception/TemplateNotFoundByReviewGroupException.java
  backend/src/main/java/reviewme/template/service/module/TemplateMapper.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/TemplateApiTest.java
  backend/src/test/java/reviewme/review/domain/CheckboxAnswersTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/module/CheckBoxAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/module/ReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/module/TextAnswerValidatorTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupLookupServiceTest.java
  backend/src/test/java/reviewme/template/service/TemplateMapperTest.java
  backend/src/test/java/reviewme/template/service/TemplateServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#630 [FE] feature: 리뷰 연결, 목록, 상세 페이지의 반응형 레이아웃 구현
  frontend/src/components/ReviewCard/styles.ts
  frontend/src/components/common/ReviewDate/index.tsx
  frontend/src/components/common/ReviewDate/styles.ts
  frontend/src/components/common/modals/AlertModal/index.tsx
  frontend/src/components/common/modals/ContentModal/index.tsx
  frontend/src/components/common/modals/ContentModal/styles.ts
  frontend/src/components/layouts/Footer/style.ts
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/ReviewListPage/components/PageContents/styles.ts
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/styles.ts
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/styles.ts
  frontend/src/pages/ReviewZonePage/styles.ts
Labels: 🍀 FE, 우선순위: 상, 🛠️ 리팩터링, 🎨 디자인

#637 [FE] refactor: scrollToTop을 유틸함수로 분리
  frontend/src/components/common/TopButton/index.tsx
  frontend/src/hooks/useTopButton.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/useCurrentCardIndex.ts
  frontend/src/utils/debounce.ts
  frontend/src/utils/index.ts
  frontend/src/utils/isExistentElement.ts
  frontend/src/utils/scrollToTop.ts
Labels: 🍀 FE, 🛠️ 리팩터링, 🍰 초간단

#598 [BE] refactor: 패키지 `mapper`, `validator` 분리
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewRegisterService.java
  backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewDetailMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewListMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewPreviewGenerator.java
  backend/src/main/java/reviewme/review/service/validator/CheckBoxAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/ReviewValidator.java
  backend/src/main/java/reviewme/review/service/validator/TextAnswerValidator.java
  backend/src/main/java/reviewme/template/service/TemplateService.java
  backend/src/main/java/reviewme/template/service/mapper/TemplateMapper.java
  backend/src/test/java/reviewme/review/service/ReviewPreviewGeneratorTest.java
  backend/src/test/java/reviewme/review/service/mapper/AnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/validator/CheckBoxAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/ReviewValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/TextAnswerValidatorTest.java
  backend/src/test/java/reviewme/template/service/mapper/TemplateMapperTest.java
Labels: ✨ BE, 🛠️ 리팩터링, 🍰 초간단

#635 [FE] design : body에 단어 단위로 줄 바꿈 되는 속성 추가
  frontend/src/pages/HomePage/components/ReviewZoneURLModal/styles.ts
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/styles.ts
  frontend/src/pages/ReviewWritingPage/modals/components/AnswerListRecheckModal/styles.ts
  frontend/src/pages/ReviewWritingPage/modals/components/NavigateBlockerModal/style.ts
  frontend/src/pages/ReviewWritingPage/modals/components/StrengthUnCheckModal/style.ts
  frontend/src/styles/globalStyles.ts
Labels: 🍀 FE, 🎨 디자인, 🍰 초간단

#647 [FE] fix: 리뷰 제출 확인 모달 border, border-radius 복원
  frontend/src/pages/ReviewWritingPage/form/components/ReviewWritingCard/index.tsx
  frontend/src/pages/ReviewWritingPage/layout/components/ReviewWritingCardLayout/style.ts
  frontend/src/pages/ReviewWritingPage/slider/components/CardSlider/index.tsx
  frontend/src/pages/ReviewWritingPage/slider/components/CardSlider/style.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인

#645 [FE] feature: Breadcrumb 컴포넌트에 반응형 추가
  frontend/src/components/common/Breadcrumb/styles.ts
Labels: 🍀 FE, 우선순위: 중, 🚀 기능, 🍰 초간단

#617 [BE] refactor: DB 접근을 최소화 하도록 개선
  backend/src/main/java/reviewme/question/repository/OptionGroupRepository.java
  backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
  backend/src/main/java/reviewme/question/repository/QuestionRepository.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewDetailMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewListMapper.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/main/java/reviewme/template/repository/SectionRepository.java
  backend/src/test/java/reviewme/question/repository/OptionGroupRepositoryTest.java
  backend/src/test/java/reviewme/question/repository/OptionItemRepositoryTest.java
  backend/src/test/java/reviewme/question/repository/QuestionRepositoryTest.java
  backend/src/test/java/reviewme/review/repository/ReviewRepositoryTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#651 [FE] fix : 리뷰 제출 페이지에서 리뷰 대상(프로젝트,리뷰이)사라지는 오류 해결
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/styles.ts
  frontend/src/pages/ReviewWritingPage/layout/components/ReviewWritingCardLayout/style.ts
  frontend/src/pages/ReviewWritingPage/slider/components/CardSlider/style.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인

#657 [FE] style: styelint 적용되지 않은 코드에 이를 적용
  frontend/src/components/ReviewCard/styles.ts
  frontend/src/components/common/Breadcrumb/styles.ts
  frontend/src/components/common/Input/styles.ts
  frontend/src/components/common/modals/AlertModal/styles.ts
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/styles.ts
  frontend/src/pages/HomePage/components/InfinityCarousel/styles.ts
  frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
  frontend/src/pages/HomePage/components/ReviewZoneURLModal/styles.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/styles.ts
  frontend/src/pages/ReviewListPage/components/PageContents/styles.ts
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/styles.ts
  frontend/src/pages/ReviewZonePage/components/PasswordModal/styles.ts
  frontend/src/pages/ReviewZonePage/styles.ts
Labels: 🍀 FE, 🍰 초간단

#655 [FE] fix : 반응형 오류 및 디자인 수정, 리뷰 목록 페이지 Description border-radius 오류 수정
  frontend/src/components/common/modals/ContentModal/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/styles/globalStyles.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인, 🍰 초간단

#653 [FE] feat: 리뷰 목록 페이지에서, 받은 리뷰가 없을 때 보여주는 널 페이지에 반응형 적용 및 그에 따른 기존 스타일 일부 수정
  frontend/src/pages/ReviewListPage/components/PageContents/styles.ts
  frontend/src/pages/ReviewListPage/components/ReviewEmptySection/styles.ts
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/styles.ts
Labels: 🍀 FE, 우선순위: 중, 🐛 버그

#658 [FE] feat: 모바일 환경에서 홈 페이지 캐러셀 드래그 기능 구현
  frontend/src/assets/nextArrow.svg
  frontend/src/assets/prevArrow.svg
  frontend/src/pages/HomePage/components/InfinityCarousel/index.tsx
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링

#662 [FE] fix : ErrorAlertModal 가운데 정렬 오류 수정
  frontend/src/components/common/modals/ErrorAlertModal/styles.ts
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/styles.ts
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/styles.ts
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitCheckModal/style.ts
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitErrorModal/style.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인

#660 [FE] refactor: Footer 반응형 경계값을 small(태블릿 세로 모드)로 수정
  frontend/src/components/layouts/Footer/style.ts
Labels: 🍀 FE, 우선순위: 하, 🛠️ 리팩터링, 🍰 초간단

#680 [FE] feat: Brotli 압축 적용
  frontend/package.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🍀 FE, 🚀 기능

#648 [BE] chore: 로그에서의 오타 수정
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
Labels: ✨ BE, 🐛 버그, 🍰 초간단

#678 [FE] design: 홈페이지 AlertModal 내 체크박스 선택 시, 버튼 색상을 primary 색상으로 변경
  frontend/src/pages/HomePage/components/ReviewZoneURLModal/index.tsx
Labels: 🍀 FE, 🎨 디자인, 🍰 초간단

#673 [BE] infra: 어플리케이션 도커로 배포
  .github/workflows/backend-dev-cd.yml
  backend/Dockerfile
Labels: ✨ BE, 🌏 인프라

#688 [BE] fix: CD 스크립트 수정
  .github/workflows/backend-dev-cd.yml
  backend/Dockerfile
Labels: ✨ BE, 🌏 인프라, 🍰 초간단

#686 [BE] chore: 스웨거 관련 파일 제거
  backend/src/main/java/reviewme/config/SwaggerConfig.java
  backend/src/main/java/reviewme/config/properties/SwaggerProperties.java
  backend/src/main/resources/api-docs.yml
  backend/src/main/resources/application.yml
Labels: ✨ BE, 🍰 초간단

#694 [BE] infra: 여러 운영 서버에 병렬적으로 배포될 수 있도록 변경
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 우선순위: 상, 🌏 인프라

#696 [BE] chore: 운영 CD 스크립트를 도커 사용 스크립트로 변경
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 우선순위: 상, 🌏 인프라, 🍰 초간단

#687 [BE] infra: 운영 환경 DB에 Replication 적용
  backend/src/main/java/reviewme/config/DataSourceType.java
  backend/src/main/java/reviewme/config/ReplicationDatasourceConfig.java
  backend/src/main/java/reviewme/config/ReplicationRoutingDataSource.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application.yml
Labels: ✨ BE, 🌏 인프라

#666 [BE] feat: 세션을 활용해 리뷰 조회
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/review-detail.adoc
  backend/src/docs/asciidoc/review-list.adoc
  backend/src/docs/asciidoc/reviewgroup.adoc
  backend/src/main/java/reviewme/config/CorsConfig.java
  backend/src/main/java/reviewme/config/CorsProperties.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/exception/ReviewGroupUnauthorizedException.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/config/CorsConfigTest.java
  backend/src/test/java/reviewme/config/ExternalCorsConfigTest.java
  backend/src/test/java/reviewme/config/LocalCorsConfigTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
  backend/src/test/resources/application.yml
Labels: ✨ BE, 🚀 기능

#685 [FE] fix: threshold 오타 수정
  frontend/webpack.config.js
Labels: 🍀 FE, 🐛 버그

#695 [FE] refactor: 비밀번호 확인, 리뷰 목록 및 리뷰 상세 정보 요청 API 변경에 따른 리팩토링
  frontend/src/apis/endpoints.ts
  frontend/src/apis/group.ts
  frontend/src/apis/review.ts
  frontend/src/components/common/modals/LoginRedirectModal/index.tsx
  frontend/src/components/common/modals/index.tsx
  frontend/src/components/error/AuthAndServerErrorFallback/index.tsx
  frontend/src/components/error/AuthAndServerErrorSection/index.tsx
  frontend/src/components/error/ErrorFallback/index.tsx
  frontend/src/components/error/ErrorSection/index.tsx
  frontend/src/components/error/ErrorSuspenseContainer/index.tsx
  frontend/src/components/error/index.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/review/useGetDetailedReview/index.ts
  frontend/src/hooks/review/useGetDetailedReview/test.ts
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/hooks/review/useGetReviewList/test.ts
  frontend/src/hooks/reviewGroup/useCheckPasswordValidation/index.ts
  frontend/src/hooks/reviewGroup/useCheckPasswordValidation/test.ts
  frontend/src/hooks/useBreadcrumbPaths.ts
  frontend/src/hooks/useGroupAccessCode.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/group.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/index.tsx
  frontend/src/pages/ReviewWritingPage/progressBar/hooks/useStepList/test.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
  frontend/src/recoil/groupAccessCode/index.ts
  frontend/src/recoil/index.ts
  frontend/src/recoil/keys/index.ts
  frontend/src/types/reviewGroup.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 🛠️ 리팩터링, 💪 아자아자!!

#698 [FE] feat : 목 서버에서 세션 쿠키 사용하는 추가 및 확인하는 기능 추가
  frontend/src/hooks/review/useGetDetailedReview/index.ts
  frontend/src/hooks/review/useGetDetailedReview/test.ts
  frontend/src/hooks/review/useGetReviewList/test.ts
  frontend/src/mocks/handlers/group.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/group.ts
  frontend/src/mocks/mockData/reviewListMockData.ts
Labels: 🍀 FE, 🚀 기능

#699 [FE] refactor: 리뷰 목록 페이지에서 무한 스크롤 로직 수정 및 적용
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/assets/githubLogo.svg
  frontend/src/assets/lock.svg
  frontend/src/assets/unLock.svg
  frontend/src/components/ReviewCard/index.tsx
  frontend/src/components/common/DropDown/index.tsx
  frontend/src/components/common/DropDown/styles.ts
  frontend/src/components/common/ProjectImg/index.tsx
  frontend/src/components/common/ProjectImg/styles.ts
  frontend/src/components/common/SearchInput/index.tsx
  frontend/src/components/common/SearchInput/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewListMockData.ts
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/SearchSection/index.tsx
  frontend/src/pages/ReviewListPage/components/SearchSection/styles.ts
  frontend/src/pages/ReviewListPage/hooks/index.ts
  frontend/src/pages/ReviewListPage/hooks/useInfiniteScroll.ts
  frontend/src/pages/ReviewListPage/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링

#692 [FE] chore: 불필요한 이미지,컴포넌트 삭제
  frontend/src/assets/downArrow.svg
  frontend/src/assets/menu.svg
  frontend/src/assets/usageCarosel1.svg
  frontend/src/assets/usageCarosel2.svg
  frontend/src/assets/usageCarosel3.svg
  frontend/src/components/common/RevieweeComments/index.tsx
  frontend/src/components/common/RevieweeComments/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/common/modals/SideModal/index.tsx
  frontend/src/components/common/modals/SideModal/styles.ts
  frontend/src/components/common/modals/index.tsx
  frontend/src/mocks/mockData/reviewListMockData.ts
  frontend/src/pages/DetailedReviewPage/components/LockToggle/index.tsx
  frontend/src/pages/DetailedReviewPage/components/LockToggle/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/index.tsx
  frontend/src/pages/ErrorPage/index.tsx
Labels: 🍀 FE

#701 [FE] chore: BrotliPlugin을 prod 모드에서만 실행할 수 있도록 변경
  frontend/webpack.config.js
Labels: 🍀 FE, 우선순위: 하, 🍰 초간단

#704 [FE] fix: Brotli 압축 플러그인 교체
  frontend/package.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🍀 FE

#705 [FE] feat: Error Fallback에 반응형 도입
  frontend/src/components/error/ErrorSection/styles.ts
Labels: 🍀 FE, 우선순위: 중, 🚀 기능

#710 [BE] infra-fix: CD에서의 오타 수정
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 🐛 버그, 🌏 인프라, 😱 긴급

#683 [BE] feat: 내가 받은 리뷰 목록에 페이지네이션 적용
  backend/src/docs/asciidoc/review-list.adoc
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/PageSize.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewsResponse.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewListMapper.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/reviewme/review/service/PageSizeTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
Labels: ✨ BE, 🚀 기능

#709 [FE] design : 모바일 환경에서 리뷰 작성 페이지의 모달 width 오류 수정
  frontend/src/pages/ReviewWritingPage/modals/components/AnswerListRecheckModal/styles.ts
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitCheckModal/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitCheckModal/style.ts
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인

#708 [FE] 문자열 치환을 통해 앞말과 어울리는 조사를 계산해서 사용할 수 있도록 수정
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/index.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/question/useLoadAndPrepareReview.ts
  frontend/src/pages/ReviewZonePage/index.tsx
  frontend/src/utils/calculateParticle.ts
  frontend/src/utils/hasFinalConsonant.ts
  frontend/src/utils/index.ts
  frontend/src/utils/substituteString.ts
Labels: 🍀 FE, 🚀 기능

#714 [FE] fix: 무한 스크롤에서 lastReviewId 값이 null일 때와 아닐 때의 엔드포인트 링크 분리
  frontend/src/apis/endpoints.ts
Labels: 🍀 FE, 🐛 버그

#715 [FE] refactor: TopButton 반응형 도입, Layout에서 TopButton 제거
  frontend/src/components/common/TopButton/style.ts
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/components/layouts/PageLayout/index.tsx
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/ReviewListPage/index.tsx
  frontend/src/styles/theme.ts
Labels: 🍀 FE, 우선순위: 하, 🛠️ 리팩터링, 🎨 디자인

#720 [FE] fix: 리뷰 연결 페이지 url에 reviewRequestCode 추가
  frontend/src/hooks/useBreadcrumbPaths.ts
  frontend/src/index.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useSubmitAnswers.ts
Labels: 🍀 FE, 🐛 버그

#721 [FE] design: 모바일 환경에서 리뷰 작성 완료 페이지 버튼 및 폰트 사이즈 수정
  frontend/src/pages/ReviewWritingCompletePage/styles.ts
Labels: 🍀 FE, 🎨 디자인

#727 [FE] design : 리뷰 작성 확인 모달에서 리뷰 카드 컨테이너에 마진 추가
  frontend/src/pages/ReviewWritingPage/modals/components/AnswerListRecheckModal/styles.ts
Labels: 🍀 FE, 🎨 디자인

#729 [BE] fix: 선택하지 않은 체크박스는 응답하지 않도록 수정
  backend/src/main/java/reviewme/review/service/mapper/ReviewDetailMapper.java
Labels: ✨ BE, 🐛 버그, 😱 긴급

#742 [BE] fix: 리뷰 확인 코드 검증 시 서비스에서 검증하도록, 요청 객체에서의 검증은 NotEmpty로 변경
  backend/src/main/java/reviewme/reviewgroup/service/dto/CheckValidAccessRequest.java
Labels: ✨ BE, 🐛 버그

#741 [BE] infra: 도커 태그 분리
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 🌏 인프라

#744 [BE] fix: 리뷰 그룹 생성 요청 검증 `@NotEmpty`로 변경
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupCreationRequest.java
Labels: ✨ BE, 🐛 버그

#734 [FE] fix: 영어 이름이고, 조사 선택형이 아닌 경우 undefined가 출력되는 버그 수정
  frontend/src/utils/substituteString.ts
Labels: 🍀 FE, 🐛 버그

#737 [FE] refactor: 리뷰 목록 페이지에서 isLastPage가 true일 때, IntersectionObserver 해제
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewListMockData.ts
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/hooks/useInfiniteScroll.ts
  frontend/src/pages/ReviewWritingCompletePage/styles.ts
  frontend/src/pages/ReviewWritingPage/modals/components/AnswerListRecheckModal/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/AnswerListRecheckModal/styles.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 🐛 버그, 😱 긴급

#747 [BE] fix: 정렬 기준 추가
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewListMapper.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewListMapperTest.java
Labels: ✨ BE, 🐛 버그

#745 [BE] feat: 마지막 페이지 여부 반환 로직 구현
  backend/src/docs/asciidoc/review-detail.adoc
  backend/src/docs/asciidoc/review-list.adoc
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewsResponse.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
Labels: ✨ BE, 🚀 기능

#748 [BE] fix: exists 함수가 boolean을 리턴하도록 수정
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
Labels: ✨ BE, 🐛 버그

#749 [BE] fix: exists 쿼리가 boolean 리턴하도록 수정
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
Labels: ✨ BE, 🐛 버그
