Repository woowacourse-teams/2024-review-me, pull requests merged in 2024-07, with the labels that each got.

#2 docs: PR 템플릿, 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/1-all-issue.md
  .github/ISSUE_TEMPLATE/2-backend-issue.md
  .github/ISSUE_TEMPLATE/3-frontend-issue.md
  .github/pull-request-template.md
Labels: 📋 문서

#5 [FE] 프론트엔드 초기 세팅
  frontend/.gitignore
  frontend/.prettierrc
  frontend/.stylelintrc.json
  frontend/babel.config.json
  frontend/eslint.config.js
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🍀 FE

#15 [BE] feat: 리뷰 작성
  backend/src/main/java/reviewme/keyword/KeywordRepository.java
  backend/src/main/java/reviewme/member/MemberRepository.java
  backend/src/main/java/reviewme/member/ReviewerGroupRepository.java
  backend/src/main/java/reviewme/review/CreateReviewContentRequest.java
  backend/src/main/java/reviewme/review/CreateReviewRequest.java
  backend/src/main/java/reviewme/review/ReviewContentRepository.java
  backend/src/main/java/reviewme/review/ReviewController.java
  backend/src/main/java/reviewme/review/ReviewKeywordRepository.java
  backend/src/main/java/reviewme/review/ReviewRepository.java
  backend/src/main/java/reviewme/review/ReviewService.java
  backend/src/test/java/reviewme/review/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능

#19 [BE] feat: 테스트 메서드별 격리
  backend/src/test/java/reviewme/config/TestConfig.java
  backend/src/test/java/reviewme/review/ReviewServiceTest.java
  backend/src/test/java/reviewme/support/DatabaseCleaner.java
  backend/src/test/java/reviewme/support/DatabaseCleanerExtension.java
  backend/src/test/java/reviewme/support/ServiceTest.java
Labels: ✨ BE, ♻️ 테스트

#17 [BE] fix: 누락된 리뷰 작성 매핑 URL 추가
  backend/src/main/java/reviewme/review/ReviewController.java
Labels: ✨ BE, 🐛 버그

#22 [BE] feat: 리뷰 조회
  backend/src/main/java/reviewme/member/MemberResponse.java
  backend/src/main/java/reviewme/review/ContentResponse.java
  backend/src/main/java/reviewme/review/KeywordResponse.java
  backend/src/main/java/reviewme/review/ReviewContentRepository.java
  backend/src/main/java/reviewme/review/ReviewController.java
  backend/src/main/java/reviewme/review/ReviewKeywordRepository.java
  backend/src/main/java/reviewme/review/ReviewRepository.java
  backend/src/main/java/reviewme/review/ReviewResponse.java
  backend/src/main/java/reviewme/review/ReviewService.java
  backend/src/main/java/reviewme/review/ReviewerGroupResponse.java
  backend/src/test/java/reviewme/review/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능

#20 [BE] feat: 커스텀 예외 처리
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/global/exception/NotFoundException.java
  backend/src/main/java/reviewme/global/exception/ReviewMeException.java
  backend/src/main/java/reviewme/keyword/KeywordRepository.java
  backend/src/main/java/reviewme/keyword/exception/KeywordNotFoundException.java
  backend/src/main/java/reviewme/member/MemberRepository.java
  backend/src/main/java/reviewme/member/ReviewerGroupRepository.java
  backend/src/main/java/reviewme/member/exception/MemberNotFoundException.java
  backend/src/main/java/reviewme/member/exception/ReviewerGroupNotFoundException.java
Labels: ✨ BE

#24 [BE] feat: 리뷰어 그룹 정보 및 키워드 조회 API
  backend/src/main/java/reviewme/keyword/KeywordController.java
  backend/src/main/java/reviewme/keyword/KeywordResponse.java
  backend/src/main/java/reviewme/keyword/KeywordService.java
  backend/src/main/java/reviewme/keyword/KeywordsResponse.java
  backend/src/main/java/reviewme/member/ReviewerGroupController.java
  backend/src/main/java/reviewme/member/ReviewerGroupResponse.java
  backend/src/main/java/reviewme/member/ReviewerGroupService.java
  backend/src/main/java/reviewme/review/ReviewResponse.java
  backend/src/main/java/reviewme/review/ReviewService.java
  backend/src/main/java/reviewme/review/ReviewerGroupResponse.java
Labels: 🚀 기능

#26 [FE] 리뷰 작성화면과 상세 리뷰 보기 화면 결합
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/assets/lock.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/menu.svg
  frontend/src/assets/unLock.svg
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.ts
  frontend/src/components/Main/index.tsx
  frontend/src/components/Main/styles.ts
  frontend/src/components/Sidebar/index.tsx
  frontend/src/components/Sidebar/styles.ts
  frontend/src/components/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/DetailedReviewPage/components/LockButton/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewAnswer/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewAnswer/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewQuestion/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewQuestion/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewViewSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewViewSection/styles.ts
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/DetailedReviewPage/styles.ts
  frontend/src/pages/ReviewWriting/index.tsx
  frontend/src/pages/ReviewWriting/styles.ts
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/reset.ts
  frontend/src/types/index.ts
  frontend/src/types/review.ts
  frontend/tsconfig.json
  frontend/types.d..ts
  frontend/types.d.ts
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🍀 FE, 🚀 기능

#34 [BE] feat: 리뷰어 그룹 설명 작성, 마감 기한 및 검증 로직 추가
  backend/src/main/java/reviewme/global/exception/BadRequestException.java
  backend/src/main/java/reviewme/member/domain/ReviewerGroup.java
  backend/src/main/java/reviewme/member/domain/exception/DescriptionLengthExceedException.java
  backend/src/main/java/reviewme/member/domain/exception/InvalidGroupNameLengthException.java
  backend/src/test/java/reviewme/member/domain/ReviewerGroupTest.java
  backend/src/test/java/reviewme/review/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능

#41 [FE] design: theme ,전역 스타일을 설정
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.ts
  frontend/src/types/index.ts
  frontend/src/types/theme.ts
  frontend/types.d..ts
Labels: 🍀 FE, 🎨 디자인

#44 [FE] ci: 리액트 쿼리 및 msw 설치, eslint import rule 추가 및 적용
  frontend/.eslintrc.cjs
  frontend/eslint.config.js
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Header/index.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🍀 FE, 🐛 버그

#31 [BE] docs: Swagger를 활용한 API 문서 자동화
  backend/build.gradle
  backend/src/main/java/reviewme/config/SwaggerConfig.java
  backend/src/main/java/reviewme/config/properties/SwaggerProperties.java
  backend/src/main/java/reviewme/keyword/contoller/KeywordApi.java
  backend/src/main/java/reviewme/keyword/contoller/KeywordController.java
  backend/src/main/java/reviewme/keyword/dto/response/KeywordResponse.java
  backend/src/main/java/reviewme/keyword/dto/response/KeywordsResponse.java
  backend/src/main/java/reviewme/member/controller/ReviewerGroupApi.java
  backend/src/main/java/reviewme/member/controller/ReviewerGroupController.java
  backend/src/main/java/reviewme/member/dto/response/MemberResponse.java
  backend/src/main/java/reviewme/member/dto/response/ReviewerGroupResponse.java
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/dto/request/CreateReviewContentRequest.java
  backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
  backend/src/main/java/reviewme/review/dto/response/ReviewContentResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewResponse.java
  backend/src/main/resources/application-api-docs.yml
  backend/src/main/resources/application.yml
Labels: ✨ BE, 📋 문서

#43 [BE] feat: 리뷰 도메인 구체화, 정책 구현
  backend/build.gradle
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/global/exception/FieldErrorResponse.java
  backend/src/main/java/reviewme/member/domain/ReviewerGroup.java
  backend/src/main/java/reviewme/member/domain/exception/DescriptionLengthExceededException.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/domain/exception/DeadlineExpiredException.java
  backend/src/main/java/reviewme/review/dto/request/CreateReviewContentRequest.java
  backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/test/java/reviewme/member/domain/ReviewerGroupTest.java
  backend/src/test/java/reviewme/review/ReviewServiceTest.java
  backend/src/test/java/reviewme/support/DatabaseCleaner.java
Labels: ✨ BE, 🚀 기능

#40 [BE] feat: 키워드 도메인 구체화, 정책 구현
  backend/build.gradle
  backend/src/main/java/reviewme/keyword/domain/Keyword.java
  backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
  backend/src/main/java/reviewme/keyword/domain/exception/DuplicateKeywordException.java
  backend/src/main/java/reviewme/keyword/domain/exception/KeywordLimitExceedException.java
  backend/src/main/java/reviewme/review/repository/ReviewKeywordRepository.java
  backend/src/main/java/reviewme/review/service/ReviewKeywordService.java
  backend/src/test/java/reviewme/fixture/KeywordFixture.java
  backend/src/test/java/reviewme/fixture/ReviewerGroupFixture.java
  backend/src/test/java/reviewme/keyword/domain/SelectedKeywordsTest.java
  backend/src/test/java/reviewme/review/repository/ReviewKeywordRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewKeywordServiceTest.java
Labels: ✨ BE, 🚀 기능

#53 [FE] 리뷰 쓰기 페이지에 확정된 디자인을 반영하고, 리팩터링한다.
  frontend/.eslintrc.cjs
  frontend/src/assets/clock.svg
  frontend/src/assets/githubLogo.svg
  frontend/src/assets/logo.svg
  frontend/src/components/common/Button/index.tsx
  frontend/src/components/common/Button/styles.ts
  frontend/src/constants/review.ts
  frontend/src/index.tsx
  frontend/src/pages/ReviewWriting/components/KeywordButton/index.tsx
  frontend/src/pages/ReviewWriting/components/KeywordButton/styles.ts
  frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
  frontend/src/pages/ReviewWriting/components/ReviewItem/styles.ts
  frontend/src/pages/ReviewWriting/components/RevieweeComment/index.tsx
  frontend/src/pages/ReviewWriting/components/RevieweeComment/styles.ts
  frontend/src/pages/ReviewWriting/index.tsx
  frontend/src/pages/ReviewWriting/styles.ts
  frontend/src/styles/globalStyles.ts
  frontend/src/types/emotion.ts
  frontend/src/types/styles.ts
Labels: 🍀 FE, 우선순위: 중, 🛠️ 리팩터링, 🎨 디자인

#55 [FE] feat: sidebar 리팩토링 및 기능 추가 , topbar 추가, 반응형 페이지 레이아웃 적용
  frontend/src/App.tsx
  frontend/src/assets/close.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/userProfile.svg
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.ts
  frontend/src/components/Sidebar/index.tsx
  frontend/src/components/Sidebar/styles.ts
  frontend/src/components/common/SearchInput/index.tsx
  frontend/src/components/common/SearchInput/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/index.tsx
  frontend/src/components/layouts/Main/index.tsx
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/components/layouts/PageLayout/index.tsx
  frontend/src/components/layouts/PageLayout/styles.ts
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/components/layouts/Sidebar/styles.ts
  frontend/src/components/layouts/Topbar/components/Logo/index.tsx
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/components/layouts/Topbar/components/SidebarOpenButton/index.tsx
  frontend/src/components/layouts/Topbar/components/SidebarOpenButton/styles.ts
  frontend/src/components/layouts/Topbar/index.tsx
  frontend/src/components/layouts/Topbar/styles.ts
  frontend/src/components/layouts/index.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/page.ts
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.ts
  frontend/src/types/theme.ts
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링, 🎨 디자인

#60 [BE] fix: 컴파일 에러 해결
  backend/src/test/java/reviewme/review/ReviewServiceTest.java
  backend/src/test/java/reviewme/review/repository/ReviewKeywordRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewKeywordServiceTest.java
Labels: ✨ BE, 🐛 버그

#66 [FE] fix : stylelint 적용 오류 수정
  frontend/.stylelintrc.json
  frontend/package.json
  frontend/src/components/common/Button/styles.ts
  frontend/src/components/common/SearchInput/styles.ts
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/components/layouts/PageLayout/styles.ts
  frontend/src/components/layouts/Sidebar/styles.ts
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/components/layouts/Topbar/components/SidebarOpenButton/styles.ts
  frontend/src/components/layouts/Topbar/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewQuestion/styles.ts
  frontend/src/pages/DetailedReviewPage/styles.ts
  frontend/src/pages/ReviewWriting/components/KeywordButton/styles.ts
  frontend/src/pages/ReviewWriting/components/ReviewItem/styles.ts
  frontend/src/pages/ReviewWriting/components/RevieweeComment/styles.ts
  frontend/src/pages/ReviewWriting/styles.ts
  frontend/yarn.lock
Labels: 🍀 FE, 🐛 버그

#70 [BE] ci: CI 스크립트 작성
  backend/.github/workflows/backend-ci.yml
Labels: ✨ BE, 🌏 인프라

#68 [BE] test: 깃헙 리뷰어 그룹의 테스트 추가 및 fixture 미적용 부분 보완
  backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
  backend/src/test/java/reviewme/review/ReviewServiceTest.java
Labels: ✨ BE, ♻️ 테스트

#74 [BE] chore: workflow 디렉터리 이동
  .github/workflows/backend-ci.yml
Labels: ✨ BE, 🌏 인프라

#76 [BE] infra: CD 스크립트 작성
  .github/workflows/backend-cd.yml
Labels: ✨ BE, 🌏 인프라

#77 fix: cd gradle 디렉토리 이동
  .github/workflows/backend-cd.yml
Labels: ✨ BE, 🐛 버그, 🌏 인프라

#65 [BE] refactor: 단건 리뷰 조회 시 리뷰어 정보 삭제, 리뷰 작성 시점 추가
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/dto/response/ReviewResponse.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/test/java/reviewme/review/repository/ReviewKeywordRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewKeywordServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능, 🛠️ 리팩터링

#81 [Fe] 절대 경로 사용 시 발생하는 eslint 오류를 수정했습니다.
  frontend/.eslintrc.cjs
  frontend/package.json
  frontend/yarn.lock
Labels: 🍀 FE, 🐛 버그

#69 [BE] refactor: 발생하는 모든 예외의 형식 통일
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/review/exception/ReviewNotFoundException.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
Labels: ✨ BE, 🛠️ 리팩터링

#88 [BE] feat: CORS 설정 추가
  backend/src/main/java/reviewme/config/CorsConfig.java
Labels: ✨ BE, 🚀 기능

#87 [BE] refactor: 예외 핸들러 인자 변경
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
Labels: ✨ BE, 우선순위: 하, 🛠️ 리팩터링

#97 [BE] 도메인 연관관계 재설정
  backend/src/main/java/reviewme/keyword/contoller/KeywordApi.java
  backend/src/main/java/reviewme/keyword/contoller/KeywordController.java
  backend/src/main/java/reviewme/keyword/domain/Keyword.java
  backend/src/main/java/reviewme/keyword/domain/Keywords.java
  backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
  backend/src/main/java/reviewme/keyword/service/KeywordService.java
  backend/src/main/java/reviewme/member/domain/GithubId.java
  backend/src/main/java/reviewme/member/domain/GithubIdReviewerGroup.java
  backend/src/main/java/reviewme/member/domain/Member.java
  backend/src/main/java/reviewme/member/domain/ReviewerGroup.java
  backend/src/main/java/reviewme/member/domain/ReviewerGroupGithubIds.java
  backend/src/main/java/reviewme/member/domain/exception/DuplicateReviewerException.java
  backend/src/main/java/reviewme/member/domain/exception/EmptyReviewerException.java
  backend/src/main/java/reviewme/member/domain/exception/SelfReviewException.java
  backend/src/main/java/reviewme/member/repository/GithubReviewerGroupRepository.java
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/domain/Question.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/domain/ReviewContent.java
  backend/src/main/java/reviewme/review/domain/exception/IllegalReviewerException.java
  backend/src/main/java/reviewme/review/domain/exception/InvalidAnswerLengthException.java
  backend/src/main/java/reviewme/review/domain/exception/RevieweeMismatchException.java
  backend/src/main/java/reviewme/review/dto/response/ReviewDetailResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewDetailReviewContentResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewDetailReviewerGroupResponse.java
  backend/src/main/java/reviewme/review/exception/ReviewUnAuthorizedException.java
  backend/src/main/java/reviewme/review/repository/ReviewContentRepository.java
  backend/src/main/java/reviewme/review/repository/ReviewKeywordRepository.java
  backend/src/main/java/reviewme/review/service/ReviewKeywordService.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/test/java/reviewme/fixture/MemberFixture.java
  backend/src/test/java/reviewme/fixture/ReviewerGroupFixture.java
  backend/src/test/java/reviewme/keyword/domain/KeywordsTest.java
  backend/src/test/java/reviewme/member/domain/ReviewerGroupTest.java
  backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
  backend/src/test/java/reviewme/review/domain/ReviewContentTest.java
  backend/src/test/java/reviewme/review/domain/ReviewTest.java
  backend/src/test/java/reviewme/review/repository/ReviewKeywordRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewKeywordServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능, 🛠️ 리팩터링

#95 [FE] MSW를 mock server로 셋팅
  frontend/package.json
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/apis/endpoints.ts
  frontend/src/components/common/MultilineTextViewer/index.tsx
  frontend/src/components/common/ProjectImg/index.tsx
  frontend/src/components/common/ProjectImg/styles.ts
  frontend/src/components/common/ReviewComment/index.tsx
  frontend/src/components/common/ReviewComment/styles.ts
  frontend/src/components/common/ReviewDate/index.tsx
  frontend/src/components/common/ReviewDate/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/index.tsx
  frontend/src/components/layouts/PageLayout/styles.ts
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/mocks/server.ts
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/styles.ts
  frontend/src/pages/DetailedReviewPage/components/LockButton/index.tsx
  frontend/src/pages/DetailedReviewPage/components/LockToggle/index.tsx
  frontend/src/pages/DetailedReviewPage/components/LockToggle/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewAnswer/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewAnswer/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewQuestion/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewQuestion/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewSection/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewSectionHeader/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewSectionHeader/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewViewSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewViewSection/styles.ts
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/DetailedReviewPage/styles.ts
  frontend/src/pages/ReviewWriting/styles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.ts
  frontend/src/types/review.ts
  frontend/src/utils/date.ts
  frontend/src/utils/index.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🍀 FE, 우선순위: 상, 🚀 기능

#91 [FE] 상세 리뷰 페이지 : url router 연동, 변경된 디자인 반영 및 서버에서 api를 연동
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/index.tsx
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링

#101 [BE] test: 도메인 연관관계 재설정 후 테스트 작성
  backend/src/main/java/reviewme/member/domain/GithubId.java
  backend/src/main/java/reviewme/member/domain/GithubIdReviewerGroup.java
  backend/src/main/java/reviewme/member/domain/Member.java
  backend/src/main/java/reviewme/member/domain/ReviewerGroup.java
  backend/src/main/java/reviewme/member/domain/exception/InvalidDescriptionLengthException.java
  backend/src/test/java/reviewme/fixture/MemberFixture.java
  backend/src/test/java/reviewme/fixture/ReviewerGroupFixture.java
  backend/src/test/java/reviewme/member/domain/ReviewerGroupTest.java
  backend/src/test/java/reviewme/review/domain/ReviewTest.java
Labels: ✨ BE, ♻️ 테스트

#90 [FE] feat: 리뷰 목록 페이지 기능 구현
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/assets/lock.svg
  frontend/src/assets/unLock.svg
  frontend/src/components/ReviewPreviewCard/index.tsx
  frontend/src/components/ReviewPreviewCard/styles.ts
  frontend/src/components/common/Button/styles.ts
  frontend/src/components/common/DropDown/index.tsx
  frontend/src/components/common/DropDown/styles.ts
  frontend/src/components/common/SearchInput/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/components/layouts/Topbar/components/SidebarOpenButton/styles.ts
  frontend/src/components/layouts/Topbar/index.tsx
  frontend/src/components/layouts/Topbar/styles.ts
  frontend/src/constants/page.ts
  frontend/src/index.tsx
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/ReviewPreviewListPage/components/SearchSection/index.tsx
  frontend/src/pages/ReviewPreviewListPage/components/SearchSection/styles.ts
  frontend/src/pages/ReviewPreviewListPage/index.tsx
  frontend/src/pages/ReviewPreviewListPage/styles.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링, 🎨 디자인

#96 [FE] Github Actions로 CI 구축
  .github/workflows/frontend-ci.yml
  frontend/package.json
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/tempTest.test.ts
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🍀 FE, 🌏 인프라

#103 [BE] feat: 리뷰에 필요한 정보 조회 기능 추가
  backend/src/main/java/reviewme/keyword/dto/response/KeywordResponse.java
  backend/src/main/java/reviewme/keyword/service/KeywordService.java
  backend/src/main/java/reviewme/member/domain/ReviewerGroup.java
  backend/src/main/java/reviewme/member/domain/ReviewerGroupGithubIds.java
  backend/src/main/java/reviewme/member/dto/response/ReviewCreationReviewerGroupResponse.java
  backend/src/main/java/reviewme/member/service/ReviewerGroupService.java
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/dto/response/QuestionResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewCreationResponse.java
  backend/src/main/java/reviewme/review/service/QuestionService.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/test/java/reviewme/fixture/QuestionFixure.java
  backend/src/test/java/reviewme/fixture/ReviewerGroupFixture.java
  backend/src/test/java/reviewme/keyword/service/KeywordServiceTest.java
  backend/src/test/java/reviewme/member/domain/ReviewerGroupTest.java
  backend/src/test/java/reviewme/member/service/ReviewerGroupServiceTest.java
  backend/src/test/java/reviewme/review/service/QuestionServiceTest.java
Labels: ✨ BE, 🚀 기능

#111 [FE] 리뷰 작성 페이지에서 MSW를 사용하여 서버 mocking
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewWritingData.ts
  frontend/src/pages/ReviewWriting/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 🚀 기능

#110 [FE] 공통 컴포넌트인 모달을 만든다.
  frontend/src/App.tsx
  frontend/src/components/common/Button/index.tsx
  frontend/src/components/common/index.tsx
  frontend/src/components/common/modals/ConfirmModal/index.tsx
  frontend/src/components/common/modals/ConfirmModal/styles.ts
  frontend/src/components/common/modals/ModalBackground/index.tsx
  frontend/src/components/common/modals/ModalBackground/styles.ts
  frontend/src/components/common/modals/ModalPortal/index.tsx
  frontend/src/components/common/modals/ModalPortal/styles.ts
  frontend/src/components/common/modals/SideModal/index.tsx
  frontend/src/components/common/modals/SideModal/styles.ts
  frontend/src/components/common/modals/index.tsx
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/components/layouts/Sidebar/styles.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useSidebar.ts
  frontend/src/styles/theme.ts
Labels: 🍀 FE, 우선순위: 하, 🐛 버그, 🚀 기능

#114 [FE] msw관련 env 오류 해결
  frontend/src/apis/endpoints.ts
  frontend/src/index.tsx
Labels: 🍀 FE, 우선순위: 상, 🐛 버그

#109 [BE] feat: 내가 받은 리뷰 보기 기능 구현
  backend/src/main/java/reviewme/keyword/domain/Keywords.java
  backend/src/main/java/reviewme/member/domain/GithubIdReviewerGroup.java
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/domain/ReviewContent.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewKeywordsResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewReviewerGroupResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewsResponse.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 우선순위: 상, 🛠️ 리팩터링

#118 [FE] fix: 잘못 정의된 endpoint 수정
  frontend/src/apis/endpoints.ts
Labels: 🍀 FE, 우선순위: 상, 🐛 버그

#121 [FE] 머지로 인해 사라진 리뷰 상세 페이지 변경 사항 복구 및 데이터 타입 변경
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/index.tsx
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 🐛 버그

#130 [FE] msw 모킹을 위한 리뷰 데이터 하드코딩
  frontend/src/apis/review.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/pages/ReviewPreviewListPage/index.tsx
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링

#132 [FE] endPoint 오류와 리뷰 그룹 아이디 수정
  frontend/src/apis/endpoints.ts
  frontend/src/pages/ReviewWriting/index.tsx
Labels: 🍀 FE, 🐛 버그, 😱 긴급

#134 [BE] fix: 리뷰 미리 보기 생성 기능 수정
  backend/src/main/java/reviewme/member/service/ReviewerGroupService.java
  backend/src/main/java/reviewme/review/domain/ReviewContent.java
Labels: ✨ BE, 🐛 버그

#136 [FE] develop의 frontend/src/index.tsx에서 enableMocking를 제거한다.
  frontend/src/index.tsx
Labels: 🍀 FE, 🐛 버그

#147 [FE] Children 속성이 필수인 타입 제작
  frontend/src/components/common/Button/index.tsx
  frontend/src/components/common/Button/styles.ts
  frontend/src/components/common/modals/ConfirmModal/index.tsx
  frontend/src/types/essentialPropsWithChildren.ts
  frontend/src/types/index.ts
Labels: 🍀 FE, 우선순위: 중

#139 [FE] 사이드바 및 모달 사용성 개선
  frontend/src/App.tsx
  frontend/src/components/common/modals/ModalBackground/index.tsx
  frontend/src/components/common/modals/SideModal/index.tsx
  frontend/src/components/common/modals/SideModal/styles.ts
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useModalClose.ts
  frontend/src/hooks/useSidebar.ts
Labels: 🍀 FE, 🐛 버그

#150 [FE] 존재하지 않는 element에 대한 에러를 출력하는 유틸리티 함수 제작
  frontend/src/utils/index.ts
  frontend/src/utils/isExistentElement.ts
Labels: 🍀 FE, 우선순위: 중, 🚀 기능

#151 [FE] HTTP 요청 오류 시 status code별 오류 상황을 대응하는 함수 생성
  frontend/src/apis/apiErrorMessageCreator.ts
  frontend/src/apis/review.ts
  frontend/src/constants/apiErrorMessage.ts
  frontend/src/constants/index.ts
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링

#153 [FE] 페이지 상단 이동 버튼 구현
  frontend/src/assets/upperArrow.svg
  frontend/src/components/common/TopButton/index.tsx
  frontend/src/components/common/TopButton/style.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/layouts/PageLayout/index.tsx
  frontend/src/hooks/useTopButton.ts
Labels: 🍀 FE, 🚀 기능
