Repository woowacourse-teams/2024-review-me, pull requests merged in 2024-08, with the labels that each got.

#169 [All] infra: 디스코드 웹훅 사용해 PR 생성/코멘트 시 멘션
  .github/workflows/discord-pull-request-comment.yml
  .github/workflows/discord-pull-request.yml
Labels: 🌏 인프라

#163 [BE] feat: 리뷰 그룹 생성 API 구현
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/dto/ReviewGroupCreationRequest.java
  backend/src/main/java/reviewme/reviewgroup/dto/ReviewGroupCreationResponse.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/test/java/reviewme/reviewgroup/service/RandomCodeGeneratorTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
Labels: ✨ BE, 🚀 기능

#162 [BE] refactor: 리뷰 작성을 위한 정보 요청 기능 리팩터링
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/dto/request/CreateReviewContentRequest.java
  backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
  backend/src/main/java/reviewme/review/dto/response/QuestionSetupResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewDetailResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewDetailReviewerGroupResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewSetUpKeyword.java
  backend/src/main/java/reviewme/review/dto/response/ReviewSetupResponse.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 우선순위: 중, 🛠️ 리팩터링

#161 [FE] 리뷰 상세 페이지에 react-query 추가 및 리팩토링
  frontend/package.json
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/components/common/ReviewComment/index.tsx
  frontend/src/components/common/RevieweeComments/index.tsx
  frontend/src/components/common/RevieweeComments/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/error/ErrorFallback/index.tsx
  frontend/src/components/error/ErrorSection/index.tsx
  frontend/src/components/error/ErrorSection/styles.ts
  frontend/src/components/error/ErrorSuspenseContainer/index.tsx
  frontend/src/components/error/index.tsx
  frontend/src/components/index.tsx
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/index.tsx
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/ErrorPage/index.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/review.ts
  frontend/yarn.lock
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링

#179 [BE] feat: 리뷰 목록 조회
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewKeywordsResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewReviewerGroupResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewsResponse.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/ReviewPreviewGenerator.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/main/java/reviewme/review/service/exception/InvalidGroupAccessCodeException.java
  backend/src/main/java/reviewme/review/service/exception/InvalidReviewRequestCodeException.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/test/java/reviewme/review/service/ReviewPreviewGeneratorTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능

#167 [FE] fix: 브라우저 타이틀 오타 수정
  frontend/public/index.html
Labels: 🍀 FE, 😱 긴급

#182 [BE] feat: 리뷰 상세 조회 기능 구현
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/domain/exception/ReviewGroupNotFoundException.java
  backend/src/main/java/reviewme/review/domain/exception/ReviewIsNotInReviewGroupException.java
  backend/src/main/java/reviewme/review/dto/response/KeywordResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewDetailResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewSetupResponse.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/main/java/reviewme/review/service/exception/InvalidReviewRequestCodeException.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#180 [FE] recoil을 통한 groupAccessCode 전역 상태 관리
  frontend/package.json
  frontend/src/hooks/index.ts
  frontend/src/hooks/useGroupAccessCode.ts
  frontend/src/index.tsx
  frontend/src/recoil/groupAccessCode/index.ts
  frontend/src/recoil/index.ts
  frontend/src/recoil/keys/index.ts
  frontend/yarn.lock
Labels: 🍀 FE, 🚀 기능

#187 [BE] 초기 데이터 설정
  .github/workflows/backend-cd.yml
  backend/src/main/java/reviewme/DatabaseInitializer.java
Labels: ✨ BE, 우선순위: 상, 🚀 기능

#165 [FE] feat: Alert Modal과 Error Alert Modal 컴포넌트 구현 및 Button 컴포넌트 확장
  frontend/src/assets/alertTrianglePrimary.svg
  frontend/src/components/common/Button/index.tsx
  frontend/src/components/common/Button/styles.ts
  frontend/src/components/common/modals/AlertModal/index.tsx
  frontend/src/components/common/modals/AlertModal/styles.ts
  frontend/src/components/common/modals/ConfirmModal/index.tsx
  frontend/src/components/common/modals/ErrorAlertModal/index.tsx
  frontend/src/components/common/modals/ErrorAlertModal/styles.ts
  frontend/src/components/common/modals/ModalBackground/index.tsx
  frontend/src/components/common/modals/index.tsx
  frontend/src/components/error/ErrorSection/index.tsx
  frontend/src/hooks/useModalClose.ts
  frontend/src/pages/ReviewPreviewListPage/components/SearchSection/index.tsx
  frontend/src/pages/ReviewWriting/index.tsx
  frontend/src/types/styles.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능

#181 [FE] 랜딩 페이지 퍼블리싱 및 디바운싱 함수 추가
  frontend/src/components/common/Input/index.tsx
  frontend/src/components/common/Input/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/LandingPage/components/FormBody/index.tsx
  frontend/src/pages/LandingPage/components/FormLayout/index.tsx
  frontend/src/pages/LandingPage/components/ReviewAccessForm/index.tsx
  frontend/src/pages/LandingPage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/LandingPage/styles.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/debounce.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 🎨 디자인

#192 [FE] feat: 리뷰 목록 페이지에 변경된 API 연동 후, 리액트 쿼리 적용 및 무한 스크롤 구현
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/assets/lock.svg
  frontend/src/components/ReviewPreviewCard/index.tsx
  frontend/src/components/ReviewPreviewCard/styles.ts
  frontend/src/components/common/DropDown/styles.ts
  frontend/src/components/common/SearchInput/styles.ts
  frontend/src/components/error/ErrorSection/index.tsx
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/components/layouts/Sidebar/styles.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/useReviewPreviewList.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewPreviewList.ts
  frontend/src/pages/ReviewPreviewListPage/components/ReviewInfoSection/index.tsx
  frontend/src/pages/ReviewPreviewListPage/components/ReviewInfoSection/styles.ts
  frontend/src/pages/ReviewPreviewListPage/components/SearchSection/index.tsx
  frontend/src/pages/ReviewPreviewListPage/index.tsx
  frontend/src/pages/ReviewWriting/components/RevieweeComment/styles.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 🛠️ 리팩터링

#191 [FE] feat: 리뷰 작성 페이지와 서버 및 모달 연동
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/components/common/Textarea/index.tsx
  frontend/src/components/common/Textarea/styles.ts
  frontend/src/components/common/modals/AlertModal/styles.ts
  frontend/src/components/common/modals/ConfirmModal/index.tsx
  frontend/src/components/common/modals/ConfirmModal/styles.ts
  frontend/src/components/common/modals/ErrorAlertModal/styles.ts
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/ReviewWriting/index.tsx
  frontend/src/pages/ReviewWriting/styles.ts
  frontend/src/styles/reset.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 🛠️ 리팩터링

#193 [FE] 리뷰 목록 페이지, 리뷰 상세 페이지에서 로그인을 연동
  frontend/src/apis/review.ts
  frontend/src/assets/primaryHome.svg
  frontend/src/assets/primaryReload.svg
  frontend/src/assets/whiteHome.svg
  frontend/src/assets/whiteReload.svg
  frontend/src/components/common/modals/LoginRedirectModal/index.tsx
  frontend/src/components/common/modals/index.tsx
  frontend/src/components/error/ErrorFallback/index.tsx
  frontend/src/components/error/ErrorSection/index.tsx
  frontend/src/components/error/ErrorSection/styles.ts
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/index.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/mocks/mockData/reviewPreviewList.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/styles.ts
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/index.tsx
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/ErrorPage/index.tsx
  frontend/src/pages/ReviewPreviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewPreviewListPage/components/PageContents/styles.ts
  frontend/src/pages/ReviewPreviewListPage/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 🚀 기능

#196 [FE] feat: 랜딩 페이지 API 연동
  frontend/src/apis/group.ts
  frontend/src/apis/review.ts
  frontend/src/assets/copy.svg
  frontend/src/pages/LandingPage/components/FormLayout/index.tsx
  frontend/src/pages/LandingPage/components/ReviewAccessForm/index.tsx
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/index.tsx
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/styles.ts
  frontend/src/pages/LandingPage/components/URLGeneratorForm/index.tsx
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 😱 긴급

#200 [FE] feat: textarea에 최소 입력 글자 수를 만족하지 못한 경우 에러 메시지 표시 기능 구현
  frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
  frontend/src/pages/ReviewWriting/components/ReviewItem/styles.ts
Labels: 🍀 FE, 🚀 기능

#201 [FE] feat: 리뷰 작성 완료 페이지에 홈 버튼 추가
  frontend/src/pages/ReviewWritingCompletePage/index.tsx
  frontend/src/pages/ReviewWritingCompletePage/styles.ts
Labels: 🍀 FE, 🚀 기능

#203 [All] docs: 리뷰미 소개글 작성
  README.md
Labels: 📋 문서

#215 [FE] jest 사용 시 node환경 속 msw 호환성 문제와 환경 변수 오류 해결
  frontend/.eslintrc.cjs
  frontend/jest.config.js
  frontend/jest.polyfills.js
  frontend/jest.setup.js
  frontend/package.json
  frontend/yarn.lock
Labels: 🍀 FE, 🐛 버그

#216 [FE] 리뷰 상세페이지 query 훅 분리 및 HTTP 요청 테스트 진행
  frontend/src/apis/endpoints.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/review/useGetDetailedReview/index.ts
  frontend/src/hooks/review/useGetDetailedReview/test.ts
  frontend/src/hooks/useSearchParamAndQuery.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/queryTestSetup/QueryClientWrapper.tsx
Labels: 🍀 FE, ♻️ 테스트

#217 [FE] test: 리뷰 목록 페이지에 API 연동 테스트 추가 및 리팩토링
  frontend/src/apis/review.ts
  frontend/src/components/ReviewCard/index.tsx
  frontend/src/components/ReviewCard/styles.ts
  frontend/src/components/layouts/Sidebar/index.tsx
  frontend/src/constants/page.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useGetReviewList/index.ts
  frontend/src/hooks/useGetReviewList/test.tsx
  frontend/src/hooks/useReviewPreviewList.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewListMockData.ts
  frontend/src/mocks/mockData/reviewPreviewList.ts
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/styles.ts
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/styles.ts
  frontend/src/pages/ReviewListPage/components/SearchSection/index.tsx
  frontend/src/pages/ReviewListPage/components/SearchSection/styles.ts
  frontend/src/pages/ReviewListPage/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 🛠️ 리팩터링, ♻️ 테스트

#219 [FE] refactor: 리뷰 작성 페이지 리팩토링
  frontend/src/hooks/useAlertModal.ts
  frontend/src/hooks/useConfirmModal.ts
  frontend/src/hooks/useErrorModal.ts
  frontend/src/hooks/useReviewForm.ts
  frontend/src/hooks/useReviewRequestCode.ts
  frontend/src/pages/ReviewWriting/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링

#207 [BE] feat: 헤더 존재 여부 검증
  backend/src/main/java/reviewme/config/WebConfig.java
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/global/HeaderProperty.java
  backend/src/main/java/reviewme/global/HeaderPropertyArgumentResolver.java
  backend/src/main/java/reviewme/global/exception/MissingHeaderPropertyException.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/exception/InvalidGroupAccessCodeException.java
  backend/src/main/java/reviewme/review/service/exception/InvalidReviewRequestCodeException.java
  backend/src/test/java/reviewme/global/HeaderPropertyArgumentResolverTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능

#226 [FE] 구글 애널리틱스 적용
  frontend/public/index.html
Labels: 🍀 FE, 우선순위: 상, 🌏 인프라

#223 [FE] ci: sentry 초기 설정
  frontend/.gitignore
  frontend/package.json
  frontend/src/index.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🍀 FE, 우선순위: 상, 🌏 인프라

#218 [FE] refactor: LandingPage에 리액트 쿼리 적용 및 리팩토링
  frontend/src/apis/endpoints.ts
  frontend/src/apis/group.ts
  frontend/src/apis/review.ts
  frontend/src/components/common/Input/index.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/mocks/handlers/group.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/mockData/group.ts
  frontend/src/pages/LandingPage/components/FormBody/index.tsx
  frontend/src/pages/LandingPage/components/FormBody/styles.ts
  frontend/src/pages/LandingPage/components/FormLayout/index.tsx
  frontend/src/pages/LandingPage/components/FormLayout/styles.ts
  frontend/src/pages/LandingPage/components/ReviewAccessForm/index.tsx
  frontend/src/pages/LandingPage/components/ReviewAccessForm/styles.ts
  frontend/src/pages/LandingPage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/LandingPage/components/index.ts
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/LandingPage/queries/usePostDataForURL.ts
  frontend/src/pages/LandingPage/styles.ts
Labels: 우선순위: 하, 🚀 기능, 🛠️ 리팩터링

#236 fix: CD 스크립트 오타 수정
  .github/workflows/backend-cd.yml
Labels: ✨ BE, 🐛 버그, 🌏 인프라

#237 [FE] CD test 2
  frontend/src/index.tsx
Labels: 🍀 FE, 🌏 인프라

#238 fix: cd 스크립트 오타 수정
  .github/workflows/backend-cd.yml
Labels: ✨ BE, 🐛 버그, 🌏 인프라

#240 [FE] feat: 공통 컴포넌트인 체크박스와 체크박스 아이템 제작
  frontend/src/assets/checked.svg
  frontend/src/assets/unchecked.svg
  frontend/src/components/common/Checkbox/index.tsx
  frontend/src/components/common/Checkbox/styles.ts
  frontend/src/components/common/CheckboxItem/index.tsx
  frontend/src/components/common/CheckboxItem/styles.ts
Labels: 🍀 FE, 우선순위: 중, 🚀 기능

#246 [BE] fix: CD 스크립트 수정
  .github/workflows/backend-cd.yml
  backend/src/main/java/reviewme/DatabaseInitializer.java
Labels: ✨ BE, 🌏 인프라

#247 [FE] feat: 질문 작성 페이지 QuestionCard, ReviewWritingCard 공통 컴포넌트를 만들고, 슬라이더 방식의 기능 추가
  frontend/.gitignore
  frontend/public/index.html
  frontend/src/components/QuestionCard/index.tsx
  frontend/src/components/QuestionCard/styles.ts
  frontend/src/components/ReviewWritingCard/index.tsx
  frontend/src/components/ReviewWritingCard/styles.ts
  frontend/src/components/common/Input/styles.ts
  frontend/src/components/layouts/Topbar/components/Logo/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/LandingPage/components/FormLayout/styles.ts
  frontend/src/pages/LandingPage/components/ReviewAccessForm/styles.ts
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/styles.ts
  frontend/src/pages/LandingPage/styles.ts
  frontend/src/pages/ReviewWritingFormPage/index.tsx
  frontend/src/pages/ReviewWritingFormPage/styles.ts
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/styles.ts
Labels: 🍀 FE, 🚀 기능

#249 [FE] refactor: LandingPage 경로 변경
  frontend/src/App.tsx
  frontend/src/components/common/modals/LoginRedirectModal/index.tsx
  frontend/src/components/error/ErrorFallback/index.tsx
  frontend/src/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링

#254 [BE] Swagger API 문서 업데이트
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/dto/request/CreateReviewContentRequest.java
  backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewKeywordsResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewContentResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReviewDetailReviewContentResponse.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupApi.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/dto/ReviewGroupCreationRequest.java
  backend/src/main/java/reviewme/reviewgroup/dto/ReviewGroupCreationResponse.java
Labels: ✨ BE, 📋 문서, 🛠️ 리팩터링

#255 [BE] feat: 예외에 대한 로그 작성
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/keyword/domain/exception/DuplicateKeywordException.java
  backend/src/main/java/reviewme/keyword/domain/exception/KeywordLimitExceedException.java
  backend/src/main/java/reviewme/keyword/domain/exception/KeywordNotFoundException.java
  backend/src/main/java/reviewme/keyword/repository/KeywordRepository.java
  backend/src/main/java/reviewme/question/domain/exception/DuplicateQuestionException.java
  backend/src/main/java/reviewme/question/domain/exception/QuestionNotFoundException.java
  backend/src/main/java/reviewme/review/domain/ReviewContent.java
  backend/src/main/java/reviewme/review/domain/exception/InvalidAnswerLengthException.java
  backend/src/main/java/reviewme/review/domain/exception/InvalidProjectNameLengthException.java
  backend/src/main/java/reviewme/review/domain/exception/InvalidRevieweeNameLengthException.java
  backend/src/main/java/reviewme/review/domain/exception/ReviewGroupNotFoundByGroupAccessCodeException.java
  backend/src/main/java/reviewme/review/domain/exception/ReviewGroupNotFoundByRequestReviewCodeException.java
  backend/src/main/java/reviewme/review/domain/exception/ReviewGroupNotFoundException.java
  backend/src/main/java/reviewme/review/domain/exception/ReviewIsNotInReviewGroupException.java
  backend/src/main/java/reviewme/review/domain/exception/ReviewNotFoundException.java
  backend/src/main/java/reviewme/review/repository/QuestionRepository.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/ReviewCreationKeywordValidator.java
  backend/src/main/java/reviewme/review/service/ReviewCreationQuestionValidator.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/reviewme/review/service/ReviewCreationKeywordValidatorTest.java
  backend/src/test/java/reviewme/review/service/ReviewCreationQuestionValidatorTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🫠힘들다...

#252 [FE] refactor: Textarea를 사용하는 공통 장문형 답변 입력 컴포넌트 분리
  frontend/src/components/common/LongReviewItem/index.tsx
  frontend/src/components/common/LongReviewItem/styles.ts
  frontend/src/components/common/Textarea/index.tsx
  frontend/src/components/common/Textarea/styles.ts
  frontend/src/hooks/useLongReviewItem.ts
  frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
  frontend/src/pages/ReviewWriting/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링

#258 [FE] refactor: 공용 모달 훅 추가 및 LongReviewItem 리팩토링
  frontend/src/components/common/LongReviewItem/index.tsx
  frontend/src/hooks/useModals.ts
Labels: 🍀 FE, 🛠️ 리팩터링

#251 [FE] test: LandingPage에서 사용하는 API에 대한 테스트 작성
  frontend/src/pages/LandingPage/components/ReviewAccessForm/index.tsx
  frontend/src/pages/LandingPage/components/ReviewAccessForm/reviewAccessForm.test.tsx
  frontend/src/pages/LandingPage/queries/usePostDataForURL.test.tsx
  frontend/src/pages/LandingPage/queries/usePostDataForURL.ts
Labels: 🍀 FE, 우선순위: 중, ♻️ 테스트

#256 [FE] refactor: 리뷰 작성 페이지에 react query를 적용하고 API 연동 테스트 작성
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/review/useGetDataToWrite/index.ts
  frontend/src/hooks/review/useGetDataToWrite/test.tsx
  frontend/src/hooks/review/useMutateReview/index.ts
  frontend/src/hooks/review/useMutateReview/test.tsx
  frontend/src/hooks/useReviewForm.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewData.ts
  frontend/src/mocks/mockData/reviewWritingData.ts
  frontend/src/pages/ReviewWriting/components/ReviewWritingContents/index.tsx
  frontend/src/pages/ReviewWriting/components/ReviewWritingContents/styles.ts
  frontend/src/pages/ReviewWriting/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링, ♻️ 테스트

#265 [FE] fix: 질문 번호가 잘못 출력되는 오류 및 리뷰 작성 완료 시 잘못된 경로로 이동하는 오류 수정
  frontend/src/pages/ReviewWriting/components/ReviewWritingContents/index.tsx
  frontend/src/pages/ReviewWritingCompletePage/index.tsx
Labels: 🍀 FE, 🐛 버그, 😱 긴급

#262 [BE] feat: 질문 리뷰이 이름으로 치환
  backend/src/main/java/reviewme/DatabaseInitializer.java
  backend/src/main/java/reviewme/question/domain/Question.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능

#272 [FE] 데모데이 중 프론트엔드 CD 반영을 확인하는 코드를 추가
  frontend/src/App.tsx
Labels: 🍀 FE, ♻️ 테스트

#261 [FE] feat: 클립보드 복사 컴포넌트 구현
  frontend/src/components/common/Checkbox/styles.ts
  frontend/src/pages/LandingPage/components/CopyTextButton/index.tsx
  frontend/src/pages/LandingPage/components/CopyTextButton/styles.ts
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/index.tsx
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/styles.ts
  frontend/src/pages/LandingPage/components/index.ts
Labels: 🍀 FE, 우선순위: 하, 🚀 기능

#276 [FE] chore: front_deploy를 develop에 반영
  frontend/.gitignore
  frontend/public/index.html
  frontend/src/components/common/Checkbox/index.tsx
  frontend/src/components/common/Checkbox/styles.ts
  frontend/src/components/common/CheckboxItem/index.tsx
  frontend/src/components/common/CheckboxItem/styles.ts
  frontend/src/components/common/Input/styles.ts
  frontend/src/components/layouts/Topbar/components/Logo/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/LandingPage/components/FormLayout/styles.ts
  frontend/src/pages/LandingPage/components/ReviewAccessForm/styles.ts
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/styles.ts
  frontend/src/pages/LandingPage/styles.ts
  frontend/src/pages/ReviewWritingFormPage/components/QuestionCard/index.tsx
  frontend/src/pages/ReviewWritingFormPage/components/QuestionCard/styles.ts
  frontend/src/pages/ReviewWritingFormPage/components/ReviewWritingCard/index.tsx
  frontend/src/pages/ReviewWritingFormPage/components/ReviewWritingCard/styles.ts
  frontend/src/pages/ReviewWritingFormPage/components/index.tsx
  frontend/src/pages/ReviewWritingFormPage/index.tsx
  frontend/src/pages/ReviewWritingFormPage/question.ts
  frontend/src/pages/ReviewWritingFormPage/styles.ts
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/styles.ts
Labels: 🍀 FE, 🚀 기능, 🫠 힘들다...

#274 [FE] feat: 내용 확인 체크박스에 체크해야 모달을 닫을 수 있는 기능 추가 및 모달 스타일 조정
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/index.tsx
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/styles.ts
Labels: 🍀 FE, 우선순위: 중, 🚀 기능, 🎨 디자인

#284 [BE] feat: 초기 엔티티 구성
  backend/src/main/java/reviewme/question/domain/OptionGroup.java
  backend/src/main/java/reviewme/question/domain/OptionItem.java
  backend/src/main/java/reviewme/question/domain/Question2.java
  backend/src/main/java/reviewme/question/domain/QuestionType.java
  backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
  backend/src/main/java/reviewme/review/domain/Review2.java
  backend/src/main/java/reviewme/review/domain/TextAnswer.java
  backend/src/main/java/reviewme/template/domain/Section.java
  backend/src/main/java/reviewme/template/domain/Template.java
  backend/src/main/java/reviewme/template/domain/VisibleType.java
Labels: ✨ BE, 🚀 기능

#290 [All] fix (actions): PR 내용을 저장하지 않도록 수정
  .github/workflows/discord-pull-request.yml
Labels: 🐛 버그, 🌏 인프라

#293 [BE] feat: 리뷰 목록 재구현
  backend/src/main/java/reviewme/question/domain/OptionGroup.java
  backend/src/main/java/reviewme/question/domain/OptionItem.java
  backend/src/main/java/reviewme/question/domain/OptionType.java
  backend/src/main/java/reviewme/question/repository/OptionGroupRepository.java
  backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
  backend/src/main/java/reviewme/review/domain/Review2.java
  backend/src/main/java/reviewme/review/domain/TextAnswer.java
  backend/src/main/java/reviewme/review/domain/exception/CategoryOptionByReviewNotFoundException.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewCategoryResponse.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewResponse2.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewsResponse2.java
  backend/src/main/java/reviewme/review/repository/CheckboxAnswerRepository.java
  backend/src/main/java/reviewme/review/repository/Review2Repository.java
  backend/src/main/java/reviewme/review/service/ReviewPreviewGenerator.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/main/java/reviewme/template/domain/Section.java
  backend/src/main/java/reviewme/template/domain/Template.java
  backend/src/main/java/reviewme/template/repository/SectionRepository.java
  backend/src/main/java/reviewme/template/repository/TemplateRepository.java
  backend/src/test/java/reviewme/review/service/ReviewPreviewGeneratorTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🚀 기능

#281 [FE] chore: topbar에서 사용되지 않는 검색창 및 프로필 사진 숨김 처리
  frontend/src/components/layouts/Topbar/components/Logo/index.tsx
  frontend/src/components/layouts/Topbar/index.tsx
Labels: 🍀 FE, 우선순위: 중

#282 [FE] refactor: 리뷰 작성 페이지에 useModals 훅 적용
  frontend/src/hooks/useAlertModal.ts
  frontend/src/hooks/useConfirmModal.ts
  frontend/src/hooks/useErrorModal.ts
  frontend/src/hooks/useReviewForm.ts
  frontend/src/pages/ReviewWriting/components/ReviewWritingContents/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링

#288 [FE] refactor: 리뷰 목록 페이지에서 변경된 API 연동
  frontend/src/components/ReviewCard/index.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/hooks/review/useGetReviewList/test.tsx
  frontend/src/mocks/mockData/reviewListMockData.ts
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/styles.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 우선순위: 중, 🚀 기능

#302 [FE] feature: 제출할 리뷰를 한 번에 볼 수 있는 preview 모달 제작
  frontend/src/assets/x.svg
  frontend/src/components/AnswerListPreviewModal/answerList.ts
  frontend/src/components/AnswerListPreviewModal/components/QuestionCard/index.tsx
  frontend/src/components/AnswerListPreviewModal/components/QuestionCard/styles.ts
  frontend/src/components/AnswerListPreviewModal/components/ReviewWritingCard/index.tsx
  frontend/src/components/AnswerListPreviewModal/components/ReviewWritingCard/styles.ts
  frontend/src/components/AnswerListPreviewModal/index.tsx
  frontend/src/components/AnswerListPreviewModal/styles.ts
  frontend/src/components/common/Checkbox/index.tsx
  frontend/src/components/common/Checkbox/styles.ts
  frontend/src/components/common/modals/ContentModal/index.tsx
  frontend/src/components/common/modals/ContentModal/styles.ts
  frontend/src/pages/TempPage/index.tsx
Labels: 🍀 FE, 우선순위: 중, 🚀 기능, 🎨 디자인

#297 [FE] refactor: 리뷰 상세페이지에서 변경된 API를 연동
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/styles.ts
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewSectionHeader/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/styles.ts
  frontend/src/pages/ReviewListPage/components/SearchSection/index.tsx
  frontend/src/pages/ReviewListPage/components/SearchSection/styles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 우선순위: 중, 🚀 기능, 🎨 디자인

#296 [BE] feat: 변경된 도메인 구조가 적용된 리뷰 작성 API 구현
  backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
  backend/src/main/java/reviewme/question/repository/Question2Repository.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/dto/request/create/CreateReviewAnswerRequest.java
  backend/src/main/java/reviewme/review/dto/request/create/CreateReviewRequest.java
  backend/src/main/java/reviewme/review/repository/TextAnswerRepository.java
  backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
  backend/src/main/java/reviewme/review/service/CreateReviewService.java
  backend/src/main/java/reviewme/review/service/CreateTextAnswerRequestValidator.java
  backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedNotProvidedOptionItemException.java
  backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedTextException.java
  backend/src/main/java/reviewme/review/service/exception/MissingRequiredQuestionAnswerException.java
  backend/src/main/java/reviewme/review/service/exception/SelectedCheckBoxAnswerCountOutOfRange.java
  backend/src/main/java/reviewme/review/service/exception/SubmittedQuestionAndProvidedQuestionMismatchException.java
  backend/src/main/java/reviewme/review/service/exception/TextAnswerInculdedOptionException.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/template/domain/exception/OptionGroupNotFoundByQuestionIdException.java
  backend/src/main/java/reviewme/template/domain/exception/OptionItemNotFoundException.java
  backend/src/main/java/reviewme/template/domain/exception/SectionNotFoundException.java
  backend/src/main/java/reviewme/template/domain/exception/TemplateNotFoundException.java
  backend/src/main/java/reviewme/template/repository/SectionRepository.java
  backend/src/main/java/reviewme/template/repository/TemplateRepository.java
  backend/src/test/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidatorTest.java
  backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
  backend/src/test/java/reviewme/review/service/CreateTextAnswerRequestValidatorTest.java
Labels: ✨ BE, 🚀 기능, 아자아자!!💪

#311 [BE] feat: 초기 데이터 세팅
  backend/src/main/java/reviewme/DatabaseInitializer.java
  backend/src/main/java/reviewme/question/domain/Question2.java
  backend/src/main/java/reviewme/template/domain/Section.java
  backend/src/main/java/reviewme/template/service/TemplateMapper.java
Labels: ✨ BE, 🚀 기능

#316 [BE] feat: 리뷰 그룹 관련 v2 엔드포인트 추가
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupApi.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
Labels: ✨ BE, 우선순위: 상, 🚀 기능, 📋 문서

#310 [BE] refactor: 리뷰 상세보기에서 가이드라인 관련 필드 삭제
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/QuestionAnswerResponse.java
Labels: ✨ BE, 🛠️ 리팩터링

#317 [FE] 리뷰 작성 페이지에 변경된 리뷰 작성 페이지의 API 반영
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/components/AnswerListPreviewModal/answerList.ts
  frontend/src/components/AnswerListRecheckModal/components/QuestionCard/index.tsx
  frontend/src/components/AnswerListRecheckModal/components/QuestionCard/styles.ts
  frontend/src/components/AnswerListRecheckModal/components/ReviewWritingCard/index.tsx
  frontend/src/components/AnswerListRecheckModal/components/ReviewWritingCard/styles.ts
  frontend/src/components/AnswerListRecheckModal/index.tsx
  frontend/src/components/AnswerListRecheckModal/styles.ts
  frontend/src/components/index.tsx
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useGetDataToWrite/index.ts
  frontend/src/hooks/review/writingCardForm/index.ts
  frontend/src/hooks/review/writingCardForm/useGetDataToWrite/index.ts
  frontend/src/hooks/review/writingCardForm/useGetDataToWrite/test.ts
  frontend/src/hooks/review/writingCardForm/useMutateReview/index.ts
  frontend/src/hooks/review/writingCardForm/useMutateReview/test.tsx
  frontend/src/hooks/review/writingCardForm/useQuestionList.ts
  frontend/src/hooks/review/writingCardForm/useTextAnswer.ts
  frontend/src/hooks/useReviewRequestCode.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/index.ts
  frontend/src/mocks/mockData/reviewData.ts
  frontend/src/mocks/mockData/writingCardForm/reviewFormResultData.ts
  frontend/src/mocks/mockData/writingCardForm/reviewWritingCardFormData.ts
  frontend/src/pages/ReviewWritingCardFromPage/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/CardForm/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/CardSliderController/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/QnABox/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/ReviewWritingCard/index.tsx
  frontend/src/pages/TempPage/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 🚀 기능, 🫠 힘들다...

#313 [BE] docs: Swagger API 문서 업데이트
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/dto/request/create/CreateReviewAnswerRequest.java
  backend/src/main/java/reviewme/review/dto/request/create/CreateReviewRequest.java
  backend/src/main/java/reviewme/review/dto/response/ReceivedReviewResponse2.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/OptionGroupAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/OptionItemAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/QuestionAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/SectionAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/TemplateAnswerResponse.java
  backend/src/main/java/reviewme/template/controller/TemplateApi.java
  backend/src/main/java/reviewme/template/controller/TemplateController.java
  backend/src/main/java/reviewme/template/dto/response/OptionGroupResponse.java
  backend/src/main/java/reviewme/template/dto/response/OptionItemResponse.java
  backend/src/main/java/reviewme/template/dto/response/QuestionResponse.java
  backend/src/main/java/reviewme/template/dto/response/SectionResponse.java
  backend/src/main/java/reviewme/template/dto/response/TemplateResponse.java
Labels: ✨ BE, 📋 문서, 🫠 힘들다...

#318 [FE] feature: 전역 스타일에 커스텀 스크롤바 스타일 적용
  frontend/src/components/common/modals/ContentModal/styles.ts
  frontend/src/styles/globalStyles.ts
Labels: 🍀 FE, 우선순위: 하, 🚀 기능, 🎨 디자인

#308 [BE] refactor: 리뷰 작성 시 네이티브 쿼리를 사용
  backend/src/main/java/reviewme/question/repository/Question2Repository.java
  backend/src/main/java/reviewme/review/repository/QuestionRepository2.java
  backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
  backend/src/main/java/reviewme/review/service/CreateReviewService.java
  backend/src/main/java/reviewme/review/service/CreateTextAnswerRequestValidator.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/exception/SubmittedQuestionAndProvidedQuestionMismatchException.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupApi.java
  backend/src/main/java/reviewme/template/domain/Section.java
  backend/src/main/java/reviewme/template/service/TemplateMapper.java
  backend/src/test/java/reviewme/review/repository/QuestionRepository2Test.java
  backend/src/test/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidatorTest.java
  backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
  backend/src/test/java/reviewme/review/service/CreateTextAnswerRequestValidatorTest.java
  backend/src/test/java/reviewme/template/service/TemplateMapperTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#321 [FE] refactor: 리뷰 상세 페이지 url path 관련 코드 수정 및 리팩터링
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/hooks/review/useGetDetailedReview/index.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewSection/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/index.tsx
Labels: 🍀 FE, 😱 긴급, 🫠 힘들다...

#324 [FE] Fix: 리뷰 작성 페이지 API 관련 오류를 수정한다.
  frontend/src/hooks/review/writingCardForm/useMutateReview/index.ts
  frontend/src/hooks/review/writingCardForm/useMutateReview/test.tsx
  frontend/src/hooks/review/writingCardForm/useQuestionList.ts
  frontend/src/pages/ReviewWriting/components/KeywordButton/index.tsx
  frontend/src/pages/ReviewWriting/components/KeywordButton/styles.ts
  frontend/src/pages/ReviewWriting/components/ReviewWritingContents/index.tsx
  frontend/src/pages/ReviewWriting/components/ReviewWritingContents/styles.ts
  frontend/src/pages/ReviewWriting/components/RevieweeComment/index.tsx
  frontend/src/pages/ReviewWriting/components/RevieweeComment/styles.ts
  frontend/src/pages/ReviewWriting/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/CardForm/index.tsx
Labels: 🍀 FE, 🐛 버그, 🫠 힘들다...

#327 [BE] 리뷰 단건 조회 시, 리뷰이 이름으로 치환되지 않는 오류 수정
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
Labels: ✨ BE, 🐛 버그

#329 [FE] fix: URL 생성 모달에서 체크박스가 선택되지 않은 경우 닫기 버튼을 disabled로 수정
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/index.tsx
Labels: 🍀 FE, 🐛 버그

#333 [FE] fix : 리뷰 작성 페이지에서 유효하지 않은 답변 오류 수정
  frontend/src/hooks/review/writingCardForm/useMultipleChoice.ts
  frontend/src/hooks/review/writingCardForm/useTextAnswer.ts
Labels: 🍀 FE, 🐛 버그, 😱 긴급

#331 [FE] refactor: URLGeneratorForm에 useModals 훅 적용
  frontend/src/components/common/Checkbox/index.tsx
  frontend/src/pages/LandingPage/components/URLGeneratorForm/index.tsx
Labels: 🍀 FE, 우선순위: 하, 🛠️ 리팩터링, 아자아자!!💪

#339 [FE] fix : 필수가 아닌 객관식, 서술형에서 답변 작성이 들어갈 경우에도 유효성 검사를 진행
  frontend/src/hooks/review/writingCardForm/useMultipleChoice.ts
  frontend/src/hooks/review/writingCardForm/useReviewerAnswer.ts
  frontend/src/hooks/review/writingCardForm/useTextAnswer.ts
  frontend/src/pages/ReviewWritingCardFromPage/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/CardSliderController/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/QnABox/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/ReviewWritingCard/index.tsx
Labels: 🍀 FE, 🐛 버그

#342 [FE] fix : 필수가 아닌 답변을 작성하려 하지 않았을 경우에 대한 오류 수정
  frontend/src/hooks/review/writingCardForm/useReviewerAnswer.ts
Labels: 🍀 FE, 🐛 버그, 😱 긴급

#340 [FE] refactor: 리뷰 상세 페이지 QuestionData 인터페이스에서 hasGuideline, guideline 속성 제거
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 🛠️ 리팩터링

#345 [FE] refactor: 사용자 테스트에서 피드백 받은 사소한 버그 수정
  frontend/src/components/AnswerListRecheckModal/index.tsx
  frontend/src/components/common/LongReviewItem/index.tsx
  frontend/src/components/common/MultilineTextViewer/index.tsx
  frontend/src/components/common/MultilineTextViewer/styles.ts
  frontend/src/components/layouts/Topbar/components/Logo/index.tsx
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/components/layouts/Topbar/index.tsx
  frontend/src/hooks/useLongReviewItem.ts
  frontend/src/pages/ReviewWritingCardFromPage/QnABox/index.tsx
  frontend/src/styles/reset.ts
Labels: 🍀 FE, 🐛 버그, 🛠️ 리팩터링, 😱 긴급

#349 [FE] refactor: LandingPage에서 사용하는 Input 유효성 검사 함수 분리 및 테스트 작성
  frontend/src/pages/LandingPage/utils/validateInput.test.ts
  frontend/src/pages/LandingPage/utils/validateInput.ts
Labels: 🍀 FE, 우선순위: 하, 🛠️ 리팩터링, ♻️ 테스트

#347 [FE] refactor: sourcemap 관련 보안 설정 추가
  frontend/webpack.config.js
Labels: 🍀 FE, 🚀 기능, 🌏 인프라

#358 [BE] fix: 쿼리 문법 수정
  backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
Labels: ✨ BE, 우선순위: 상, 🐛 버그, 😱 긴급

#351 [FE] feature: 이름, 프로젝트명에 대한 유효성 검사 및 에러 메세지 안내 추가
  frontend/src/pages/LandingPage/components/FormBody/styles.ts
  frontend/src/pages/LandingPage/components/ReviewAccessForm/index.tsx
  frontend/src/pages/LandingPage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/LandingPage/components/URLGeneratorForm/styles.ts
Labels: 🍀 FE, 우선순위: 상, 🐛 버그, 🚀 기능

#365 [FE] fix: Pretendard 폰트가 정상적으로 적용되도록 나눔고딕 제거
  frontend/public/index.html
  frontend/src/styles/globalStyles.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인

#369 [FE] refactor,fix : 리뷰 작성 페이지 디자인 버그 수정 및 상태 관리 리팩토링
  frontend/src/components/common/LongReviewItem/styles.ts
  frontend/src/hooks/review/writingCardForm/index.ts
  frontend/src/hooks/review/writingCardForm/multiplceChoice/useAboveSelectionLimit.ts
  frontend/src/hooks/review/writingCardForm/multiplceChoice/useCancelAnsweredCategory.ts
  frontend/src/hooks/review/writingCardForm/multiplceChoice/useMultipleChoice.ts
  frontend/src/hooks/review/writingCardForm/multiplceChoice/useUpdateMultipleChoiceAnswer.ts
  frontend/src/hooks/review/writingCardForm/useCardSectionList.ts
  frontend/src/hooks/review/writingCardForm/useCheckNextStepAvailability.ts
  frontend/src/hooks/review/writingCardForm/useMultipleChoice.ts
  frontend/src/hooks/review/writingCardForm/useMutateReview/index.ts
  frontend/src/hooks/review/writingCardForm/useMutateReview/test.tsx
  frontend/src/hooks/review/writingCardForm/useQuestionList.ts
  frontend/src/hooks/review/writingCardForm/useResetFormRecoil.ts
  frontend/src/hooks/review/writingCardForm/useReviewerAnswer.ts
  frontend/src/hooks/review/writingCardForm/useTextAnswer.ts
  frontend/src/hooks/review/writingCardForm/useUpdateDefaultAnswers.ts
  frontend/src/hooks/review/writingCardForm/useUpdateReviewerAnswer.ts
  frontend/src/mocks/mockData/writingCardForm/reviewWritingCardFormData.ts
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/QnABox/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/CardSliderController/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/MultipleChoiceQuestion/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/MultipleChoiceQuestion/style.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/QnABox/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/QnABox/style.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/ReviewWritingCard/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/ReviewWritingCard/style.ts
  frontend/src/pages/ReviewWritingCardFromPage/index.tsx
  frontend/src/recoil/index.ts
  frontend/src/recoil/keys/index.ts
  frontend/src/recoil/reviewWritingForm/atom.ts
  frontend/src/recoil/reviewWritingForm/index.ts
  frontend/src/recoil/reviewWritingForm/selector.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 🐛 버그, 🛠️ 리팩터링, 🎨 디자인, 🫠 힘들다...

#352 [BE] infra: cd 스크립트 dev와 prod 분리
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 우선순위: 상, 📦 배포, 아자아자!!💪

#374 [FE] refactor: 리뷰 작성 페이지에 form 태그 도입 및 submit 버튼 변경
  frontend/src/components/common/modals/ConfirmModal/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/CardSliderController/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/ReviewWritingCard/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링

#388 [BE] infra: cd 스크립트 name 변경
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 📋 문서

#387 [BE] refactor: `ThreadLocalRandom`으로 변경
  backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
Labels: ✨ BE, 🛠️ 리팩터링

#386 [FE] fix: Pretendard 오류 수정
  frontend/src/styles/globalStyles.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인

#371 [FE] refactor: 랜딩 페이지 리팩토링 및 서비스 소개 section 제작
  frontend/src/assets/dashboard.svg
  frontend/src/assets/downArrow.svg
  frontend/src/assets/eye.svg
  frontend/src/assets/eyeOff.svg
  frontend/src/assets/overview1.svg
  frontend/src/assets/overview2.svg
  frontend/src/assets/overview3.svg
  frontend/src/assets/overviewTitle.svg
  frontend/src/components/common/EyeButton/index.tsx
  frontend/src/components/common/EyeButton/styles.ts
  frontend/src/components/common/Input/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useEyeButton.tsx
  frontend/src/index.tsx
  frontend/src/pages/HomePage/components/CopyTextButton/index.tsx
  frontend/src/pages/HomePage/components/CopyTextButton/styles.ts
  frontend/src/pages/HomePage/components/FormBody/index.tsx
  frontend/src/pages/HomePage/components/FormBody/styles.ts
  frontend/src/pages/HomePage/components/FormLayout/index.tsx
  frontend/src/pages/HomePage/components/FormLayout/styles.ts
  frontend/src/pages/HomePage/components/OverviewItem/index.tsx
  frontend/src/pages/HomePage/components/OverviewItem/styles.ts
  frontend/src/pages/HomePage/components/ReviewMeOverview/index.tsx
  frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
  frontend/src/pages/HomePage/components/ReviewURLModal/index.tsx
  frontend/src/pages/HomePage/components/ReviewURLModal/styles.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/HomePage/components/URLGeneratorForm/styles.ts
  frontend/src/pages/HomePage/components/index.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/HomePage/queries/usePostDataForURL.test.tsx
  frontend/src/pages/HomePage/queries/usePostDataForURL.ts
  frontend/src/pages/HomePage/styles.ts
  frontend/src/pages/HomePage/utils/validateInput.test.ts
  frontend/src/pages/HomePage/utils/validateInput.ts
  frontend/src/pages/LandingPage/components/ReviewAccessForm/index.tsx
  frontend/src/pages/LandingPage/components/ReviewAccessForm/reviewAccessForm.test.tsx
  frontend/src/pages/LandingPage/components/ReviewAccessForm/styles.ts
  frontend/src/pages/LandingPage/components/ReviewGroupDataModal/index.tsx
  frontend/src/pages/LandingPage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/LandingPage/components/URLGeneratorForm/styles.ts
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/LandingPage/styles.ts
  frontend/src/pages/LandingPage/utils/validateInput.test.ts
  frontend/src/pages/LandingPage/utils/validateInput.ts
  frontend/src/pages/index.tsx
Labels: 🍀 FE, 우선순위: 중, 🚀 기능, 🛠️ 리팩터링

#404 [BE] fix: CD 스크립트 - 스프링 포트 수정
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 😱 긴급

#398 [FE] feat: 리뷰 목록 페이지에서 받은 리뷰가 없을 경우, 그에 맞는 문구를 보여주는 ReviewEmptySection 컴포넌트 구현 및 스타일 수정
  frontend/src/assets/rightArrow.svg
  frontend/src/components/ReviewCard/index.tsx
  frontend/src/components/ReviewCard/styles.ts
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewEmptySection/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewEmptySection/styles.ts
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/styles.ts
Labels: 🍀 FE, 🚀 기능, 🎨 디자인

#402 [FE] design: 리뷰 상세, 작성 완료 페이지 디자인 수정
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/ReviewWritingCompletePage/index.tsx
  frontend/src/pages/ReviewWritingCompletePage/styles.ts
Labels: 🍀 FE, 🎨 디자인

#401 [FE] fix: Checkbox 컴포넌트의 잘못된 css 수정
  frontend/src/components/common/Checkbox/styles.ts
Labels: 🍀 FE, 우선순위: 상, 🐛 버그

#406 [FE] feat: 리뷰 작성 페이지 Progress Bar 구현
  frontend/src/assets/navigateNext.svg
  frontend/src/hooks/review/writingCardForm/multiplceChoice/useCancelAnsweredCategory.ts
  frontend/src/hooks/review/writingCardForm/multiplceChoice/useMultipleChoice.ts
  frontend/src/hooks/review/writingCardForm/useCurrentCardIndex.ts
  frontend/src/hooks/review/writingCardForm/useResetFormRecoil.ts
  frontend/src/mocks/mockData/writingCardForm/reviewWritingCardFormData.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/MultipleChoiceQuestion/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/ProgressBar/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/ProgressBar/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/ReviewWritingCard/index.tsx
  frontend/src/recoil/keys/index.ts
  frontend/src/recoil/reviewWritingForm/atom.ts
  frontend/src/styles/theme.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 🚀 기능, 🫠 힘들다...

#408 [FE] feat: 기존에 답변한 카테고리를 선택 해제하는 경우 confirm modal로 재확인하는 기능 구현
  frontend/src/components/common/modals/ConfirmModal/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/MultipleChoiceQuestion/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/MultipleChoiceQuestion/style.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/ProgressBar/index.tsx
Labels: 🍀 FE, 🚀 기능

#415 [FE] feat : 리뷰 그룹 정보(리뷰이,프로젝트 이름)을 서버에서 받는 로직 생성
  frontend/src/apis/endpoints.ts
  frontend/src/apis/group.ts
  frontend/src/constants/index.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routerParam.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/review/useGetDetailedReview/test.ts
  frontend/src/hooks/reviewGroup/index.ts
  frontend/src/hooks/reviewGroup/useGetReviewGroupData/index.ts
  frontend/src/hooks/reviewGroup/useGetReviewGroupData/test.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/group.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/group.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/ReviewGroupTestPage.tsx
  frontend/src/types/index.ts
  frontend/src/types/reviewGroup.ts
Labels: 🍀 FE, 🚀 기능

#405 [BE] refactor: 초기 데이터 설정시 중복 삽입 방지, 선택지 최대 개수 적용
  backend/src/main/java/reviewme/DatabaseInitializer.java
  backend/src/test/java/reviewme/question/repository/OptionItemRepositoryTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#391 [BE] refactor: 리뷰 목록 카테고리 조회 시 네이티브 쿼리를 사용하도록 변경
  backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링, 🍰 초간단

#419 [FE] feat: footer 생성 및 리뷰미 팀명과 icon8 저작권 표기
  frontend/src/App.tsx
  frontend/src/components/layouts/Footer/index.tsx
  frontend/src/components/layouts/Footer/style.ts
  frontend/src/components/layouts/PageLayout/styles.ts
  frontend/src/components/layouts/index.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.ts
Labels: 🍀 FE, 🚀 기능, 🎨 디자인, 🍰 초간단

#410 [BE] refactor: dto 에 Nullable, validation 어노테이션 적용
  backend/src/main/java/reviewme/review/service/dto/request/CreateReviewAnswerRequest.java
  backend/src/main/java/reviewme/review/service/dto/request/CreateReviewRequest.java
Labels: ✨ BE, 🍰 초간단

#396 [BE] feat: 리뷰 그룹 정보 조회 api 구현
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupResponse.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupLookupServiceTest.java
Labels: ✨ BE, 🚀 기능

#421 [FE] feat: 캐러셀 구현한 후, 홈 페이지에 적용
  frontend/src/components/common/EyeButton/styles.ts
  frontend/src/pages/HomePage/components/Carousel/index.tsx
  frontend/src/pages/HomePage/components/Carousel/styles.ts
  frontend/src/pages/HomePage/components/FormLayout/styles.ts
  frontend/src/pages/HomePage/components/ReviewDashboardURLModal/styles.ts
  frontend/src/pages/HomePage/components/ReviewMeOverview/index.tsx
  frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/styles.ts
  frontend/src/pages/HomePage/styles.ts
Labels: 🍀 FE, 🚀 기능, 🎨 디자인

#414 [BE] refactor: 리뷰 등록시 검증 보완
  backend/src/main/java/reviewme/review/domain/TextAnswer.java
  backend/src/main/java/reviewme/review/domain/exception/InvalidTextAnswerLengthException.java
  backend/src/main/java/reviewme/review/service/CreateReviewService.java
  backend/src/main/java/reviewme/review/service/CreateTextAnswerRequestValidator.java
  backend/src/main/java/reviewme/review/service/dto/request/CreateReviewAnswerRequest.java
  backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedTextException.java
  backend/src/test/java/reviewme/review/domain/TextAnswersTest.java
  backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
  backend/src/test/java/reviewme/review/service/CreateTextAnswerRequestValidatorTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#428 [FE] fix: 리뷰 연결 페이지 이름 수정 및 EyeButton이 가려지는 문제 해결
  frontend/src/assets/reviewZone.svg
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/pages/HomePage/components/ReviewZoneURLModal/index.tsx
  frontend/src/pages/HomePage/components/ReviewZoneURLModal/styles.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/HomePage/components/index.ts
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/styles.ts
  frontend/src/pages/ReviewZonePage/index.tsx
  frontend/src/pages/ReviewZonePage/styles.ts
  frontend/src/pages/index.tsx
Labels: 우선순위: 중, 🐛 버그, 🛠️ 리팩터링

#429 [FE] chore: 리뷰 목록, 상세 페이지에 유효하지 않은 접근 시 띄워주는 모달의 문구 및 버튼 content 수정
  frontend/src/components/common/modals/LoginRedirectModal/index.tsx
Labels: 🍀 FE, 우선순위: 하, 🍰 초간단

#412 [BE] feat: GroupAccessCode 와 ReviewRequestCode 를 받아 확인하는 API 구현
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/CheckValidAccessRequest.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/CheckValidAccessResponse.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
Labels: ✨ BE, 🚀 기능, 🍰 초간단

#407 [BE] feat: RestDocs 도입
  backend/build.gradle
  backend/src/docs/asciidoc/create-review.adoc
  backend/src/docs/asciidoc/get-review-form.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/review-detail.adoc
  backend/src/docs/asciidoc/review-list.adoc
  backend/src/docs/asciidoc/reviewgroup.adoc
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/dto/request/CreateReviewAnswerRequest.java
  backend/src/main/java/reviewme/review/service/dto/request/CreateReviewRequest.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/OptionGroupAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/OptionItemAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/QuestionAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/SectionAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/detail/TemplateAnswerResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewCategoryResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewsResponse.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupApi.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupCreationRequest.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupCreationResponse.java
  backend/src/main/java/reviewme/template/controller/TemplateApi.java
  backend/src/main/java/reviewme/template/controller/TemplateController.java
  backend/src/main/java/reviewme/template/service/dto/response/OptionGroupResponse.java
  backend/src/main/java/reviewme/template/service/dto/response/OptionItemResponse.java
  backend/src/main/java/reviewme/template/service/dto/response/QuestionResponse.java
  backend/src/main/java/reviewme/template/service/dto/response/SectionResponse.java
  backend/src/main/java/reviewme/template/service/dto/response/TemplateResponse.java
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/api/TemplateApiTest.java
  backend/src/test/java/reviewme/api/TemplateFixture.java
  backend/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  backend/src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
Labels: ✨ BE, 📋 문서, ♻️ 테스트

#436 [FE] feat : 리뷰 연결 페이지에서 비밀번호 조회 api 적용
  frontend/src/apis/endpoints.ts
  frontend/src/apis/group.ts
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/index.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/route.ts
  frontend/src/hooks/review/useGetDetailedReview/index.ts
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/hooks/review/writingCardForm/useGetDataToWrite/index.ts
  frontend/src/hooks/review/writingCardForm/useMutateReview/index.ts
  frontend/src/hooks/reviewGroup/useCheckPasswordValidation/index.ts
  frontend/src/hooks/useBreadcrumbPaths.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/group.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/PasswordTestPage.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/styles.ts
  frontend/src/pages/ReviewZonePage/index.tsx
  frontend/src/types/reviewGroup.ts
Labels: 🍀 FE, 🚀 기능

#441 [BE] refactor: GroupAccessCode를 발급하지 않고 사용자가 직접 입력하면서 변경되는 사항을 반영
  backend/src/main/java/reviewme/global/exception/UnexpectedRequestException.java
  backend/src/main/java/reviewme/review/controller/ReviewApi.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/main/java/reviewme/review/service/exception/ReviewGroupNotFoundByCodesException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewGroupNotFoundByReviewException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewNotFoundByIdAndCodesException.java
  backend/src/main/java/reviewme/reviewgroup/domain/GroupAccessCode.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/reviewgroup/domain/exception/InvalidGroupAccessCodeFormatException.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupCreationRequest.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupCreationResponse.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#440 [FE] fix: 리뷰 제출 전 확인 모달 스타일 조정
  frontend/src/components/AnswerListRecheckModal/components/QuestionCard/styles.ts
  frontend/src/components/AnswerListRecheckModal/index.tsx
  frontend/src/components/AnswerListRecheckModal/styles.ts
Labels: 🍀 FE, 우선순위: 중, 🐛 버그, 🛠️ 리팩터링

#434 [FE] fix: 비밀번호 검증 훅 분리 및 비밀번호 길이 유효성 검사 문구 추가
  frontend/src/components/common/Input/index.tsx
  frontend/src/hooks/usePasswordValidation.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
Labels: 🍀 FE, 우선순위: 중, 🐛 버그

#442 [FE] chore: 리뷰 목록 및 상세 페이지에서 reviewRequestCode를 recoil 상태로 관리
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/hooks/review/useGetDetailedReview/index.ts
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/index.tsx
  frontend/src/pages/ReviewZonePage/index.tsx
  frontend/src/recoil/index.ts
  frontend/src/recoil/keys/index.ts
  frontend/src/recoil/reviewRequestCode/index.ts
Labels: 🍀 FE, 우선순위: 상, 😱 긴급

#444 [FE]: 온점 삭제 및 ~다 체를 ~요 체로 변경
  frontend/src/components/common/LongReviewItem/index.tsx
  frontend/src/components/common/RevieweeComments/index.tsx
  frontend/src/components/layouts/Topbar/index.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/review.ts
  frontend/src/hooks/review/writingCardForm/useGetDataToWrite/index.ts
  frontend/src/hooks/useLongReviewItem.ts
  frontend/src/hooks/useReviewForm.ts
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/mocks/mockData/reviewWritingData.ts
  frontend/src/mocks/mockData/writingCardForm/reviewWritingCardFormData.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/index.tsx
  frontend/src/pages/HomePage/components/CopyTextButton/index.tsx
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/MultipleChoiceQuestion/index.tsx
  frontend/src/pages/ReviewZonePage/index.tsx
  frontend/src/utils/isExistentElement.ts
Labels: 🍀 FE, 우선순위: 하

#448 [FE] ci: concurrency의 cancel-in-progress 설정을 false로 수정
  .github/workflows/frontend-ci.yml
Labels: 🍀 FE, 우선순위: 상, 🐛 버그, 🍰 초간단

#457 [BE] refactor: 섹션에 섹션명 추가
  backend/src/main/java/reviewme/DatabaseInitializer.java
  backend/src/main/java/reviewme/template/domain/Section.java
  backend/src/main/java/reviewme/template/service/TemplateMapper.java
  backend/src/main/java/reviewme/template/service/dto/response/SectionResponse.java
  backend/src/test/java/reviewme/api/TemplateApiTest.java
  backend/src/test/java/reviewme/api/TemplateFixture.java
  backend/src/test/java/reviewme/review/repository/QuestionRepositoryTest.java
  backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/template/domain/SectionTest.java
  backend/src/test/java/reviewme/template/repository/SectionRepositoryTest.java
  backend/src/test/java/reviewme/template/service/TemplateMapperTest.java
Labels: ✨ BE, 우선순위: 상, 🛠️ 리팩터링

#458 [FE] refactor: 리뷰 작성 페이지 컴포넌트들의 gap 조정, footer 스타일 조정, 로고 가운데 정렬
  frontend/src/components/common/Breadcrumb/styles.ts
  frontend/src/components/layouts/Footer/style.ts
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/ProgressBar/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/ReviewWritingCard/style.ts
  frontend/src/styles/theme.ts
Labels: 🍀 FE, 우선순위: 중, 🐛 버그, 🛠️ 리팩터링, 🎨 디자인

#463 [FE] fix: HomePage 비밀번호 입력에서 onBlur 이벤트가 일어나지 않으면 유효하지 않은 비밀번호라도 통과되는 버그 수정
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
Labels: 🍀 FE, 우선순위: 상, 🐛 버그, 😱 긴급

#464 [FE] fix: breadcrumb에서 연결 페이지를 눌렀을 때 홈페이지로 이동되는 문제 해결
  frontend/src/hooks/useBreadcrumbPaths.ts
Labels: 🍀 FE, 🐛 버그, 🍰 초간단

#465 [FE] design: 캐러셀을 정가운데로 위치시킨 뒤, 자동 슬라이드 전환 시간을 6초로 설정한다. 그리고 전반적인 디자인을 수정한다.
  frontend/src/components/common/Breadcrumb/styles.ts
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/pages/HomePage/components/Carousel/index.tsx
  frontend/src/pages/HomePage/components/Carousel/styles.ts
  frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/styles.ts
  frontend/src/pages/ReviewZonePage/styles.ts
Labels: 🍀 FE, 🎨 디자인, 🍰 초간단

#466 [FE] feat : 리뷰 작성 내용 확인 에서 쓰지 않은 서술형에서 답변을 작성하지 않았다는 문구 띄어주기
  frontend/src/components/common/LongReviewItem/styles.ts
  frontend/src/components/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/AnswerListRecheckModal/components/QuestionCard/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/AnswerListRecheckModal/components/QuestionCard/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/AnswerListRecheckModal/components/ReviewCard/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/AnswerListRecheckModal/components/ReviewCard/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/AnswerListRecheckModal/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/AnswerListRecheckModal/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/index.tsx
Labels: 🍀 FE, 🐛 버그, 🎨 디자인, 🍰 초간단

#468 [FE] fix: 아루가 제안한 버그 수정
  frontend/src/pages/ReviewZonePage/index.tsx
  frontend/src/pages/ReviewZonePage/styles.ts
Labels: 🍀 FE, 🐛 버그, 🍰 초간단

#470 [FE] refactor: 비밀번호 조회 input에서 placeholder 삭제
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링

#472 [BE] 답변을 길게 작성하는 경우 발생하는 서버 에러 해결
  backend/src/main/java/reviewme/review/domain/TextAnswer.java
  backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
Labels: ✨ BE, 🐛 버그, 😱 긴급

#474 [FE] design: confirm modal의 버튼 관련 디자인 수정
  frontend/src/components/common/modals/ConfirmModal/index.tsx
  frontend/src/components/common/modals/ConfirmModal/styles.ts
Labels: 🍀 FE, 🎨 디자인, 🍰 초간단

#476 [FE] design : 홈페이지에서 footer가 스크롤 없이 한 화면에 보이도록 수정
  frontend/src/App.tsx
  frontend/src/components/common/Breadcrumb/styles.ts
  frontend/src/components/layouts/Footer/style.ts
  frontend/src/components/layouts/Main/index.tsx
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/components/layouts/Topbar/styles.ts
  frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
  frontend/src/pages/HomePage/styles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인

#485 [FE] rafactor: isSuccess 상태에 따라 리뷰 목록 페이지 전체 레이아웃 렌더링 및 리뷰 목록 간격 수정
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/styles.ts
Labels: 🍀 FE, 🛠️ 리팩터링, 🎨 디자인

#478 [FE] fix: 객관식 내용과 주관식 질문 간의 gap 띄우기
  frontend/src/pages/ReviewWritingCardFromPage/components/AnswerListRecheckModal/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/AnswerListRecheckModal/styles.ts
Labels: 🍀 FE, 우선순위: 중, 🐛 버그, 🎨 디자인

#481 [FE] refactor: 프로그레스 바 관련 코드 리팩토링
  frontend/src/hooks/review/writingCardForm/useCurrentCardIndex.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/ProgressBar/styles.ts
  frontend/src/recoil/reviewWritingForm/atom.ts
Labels: 🍀 FE, 🛠️ 리팩터링

#483 [FE] design: 링크 생성 모달, 연결 페이지 버튼 내 텍스트, 리뷰 확인 모달 띄어쓰기 관련 문제를 해결
  frontend/src/pages/HomePage/components/ReviewZoneURLModal/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
  frontend/src/pages/ReviewZonePage/styles.ts
Labels: 🍀 FE, 🎨 디자인

#487 [FE] refactor: react-query에 retry 설정 추가
  frontend/src/index.tsx
Labels: 🍀 FE, 🛠️ 리팩터링

#484 [FE] feat: 캐러셀 하단에 슬라이드 위치 표시용 도트를 추가 및 피그마 컴포넌트를 사용하여 기존 슬라이드 이미지 교체
  frontend/src/assets/usageCarosel1.svg
  frontend/src/assets/usageCarosel2.svg
  frontend/src/assets/usageCarosel3.svg
  frontend/src/pages/HomePage/components/Carousel/index.tsx
  frontend/src/pages/HomePage/components/Carousel/styles.ts
  frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
Labels: 🍀 FE, 🚀 기능, 🎨 디자인

#489 [BE] feat: 그룹 접근 코드 해싱 적용
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/global/exception/UnauthorizedException.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewPreviewGenerator.java
  backend/src/main/java/reviewme/review/service/ReviewService.java
  backend/src/main/java/reviewme/review/service/exception/ReviewGroupNotFoundByReviewException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewGroupUnauthorizedException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewNotFoundByIdAndCodesException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewNotFoundByIdAndGroupException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewNotFoundException.java
  backend/src/main/java/reviewme/reviewgroup/domain/GroupAccessCode.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/util/Encoder.java
  backend/src/main/java/reviewme/util/EncoderAlgorithmInitializationException.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewPreviewGeneratorTest.java
  backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/domain/GroupAccessCodeTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
Labels: ✨ BE, 🚀 기능

#492 [FE] design: 홈페이지 디자인 오류 수정
  frontend/src/pages/HomePage/components/FormLayout/styles.ts
  frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인, 😱 긴급, 🫠 힘들다..., 🍰 초간단

#494 [FE] chore: 리뷰미 저작권 표시 및 Icons8 저작권 표기를 공식 문서대로 변경
  frontend/src/components/layouts/Footer/index.tsx
Labels: 🍀 FE, 🍰 초간단

#497 [FE] feat :리뷰 작성 중 리뷰 작성 페이지를 떠날 때, 확인 모달을 띄우는 기능 추가
  frontend/package.json
  frontend/src/hooks/review/writingCardForm/index.ts
  frontend/src/hooks/review/writingCardForm/multipleChoice/useAboveSelectionLimit.ts
  frontend/src/hooks/review/writingCardForm/multipleChoice/useCancelAnsweredCategory.ts
  frontend/src/hooks/review/writingCardForm/multipleChoice/useMultipleChoice.ts
  frontend/src/hooks/review/writingCardForm/multipleChoice/useUpdateMultipleChoiceAnswer.ts
  frontend/src/hooks/review/writingCardForm/useNavigateBlocker.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/CardForm/styles.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/CardSliderController/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/NavigateBlockerModal/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/NavigateBlockerModal/style.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/ReviewWritingCard/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/SubmitCheckModal/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/SubmitCheckModal/style.ts
  frontend/src/pages/ReviewWritingCardFromPage/components/index.tsx
  frontend/yarn.lock
Labels: 🍀 FE, 🚀 기능

#498 [FE] design: 파비콘 추가 및 적용
  frontend/src/favicons/favicon.ico
  frontend/webpack.config.js
Labels: 🍀 FE, 🎨 디자인

#451 [BE] fix: QA에서 발생한 오류를 수정한다.
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/reviewme/DatabaseInitializer.java
  backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/exception/SelectedOptionItemCountOutOfRangeException.java
  backend/src/main/java/reviewme/review/service/exception/SubmittedQuestionAndProvidedQuestionMismatchException.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/template/domain/exception/OptionGroupNotFoundByQuestionIdException.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupLookupServiceTest.java
  backend/src/test/java/reviewme/template/service/TemplateMapperTest.java
Labels: ✨ BE, 🐛 버그, 🛠️ 리팩터링

#508 [FE] fix: 캐러셀에서 마지막 슬라이드가 넘어갈 때 자연스럽게 첫 슬라이드로 넘어가도록 수정
  frontend/src/pages/HomePage/components/Carousel/index.tsx
  frontend/src/pages/HomePage/components/ReviewMeOverview/index.tsx
Labels: 🍀 FE, 🐛 버그, 🛠️ 리팩터링

#512 [FE] feat : dev, production 서버 api 주소 설정
  frontend/src/apis/endpoints.ts
Labels: 🍀 FE

#514 [BE] hotfix: 운영 서버에 초기 데이터를 세팅한다.
  backend/src/main/java/reviewme/DatabaseInitializer.java
Labels: ✨ BE, 🐛 버그, 😱 긴급

#519 [BE] fix: SELECT q.*을 q.id로 수정 (ID를 가져오도록)
  backend/src/main/java/reviewme/question/repository/QuestionRepository.java
Labels: ✨ BE, 🐛 버그, 😱 긴급

#523 [FE] design: 파비콘 파일 교체
  frontend/src/favicons/favicon.ico
Labels: 🍀 FE, 🎨 디자인, 💪 아자아자!!, 🍰 초간단

#530 [FE] fix: 홈 페이지 캐러셀 초기 슬라이드 위치를 조정하고 ConfirmModal에 props로 title을 받아서 디자인을 수정한다.
  frontend/src/components/common/modals/ContentModal/index.tsx
  frontend/src/components/common/modals/ContentModal/styles.ts
  frontend/src/pages/HomePage/components/Carousel/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/styles.ts
Labels: 🍀 FE, 🛠️ 리팩터링, 🎨 디자인

#531 [BE] docs: SwaggerConfig 가 운영 환경에서 등록되지 않도록 변경
  backend/src/main/java/reviewme/config/SwaggerConfig.java
Labels: ✨ BE, 📋 문서, 🍰 초간단

#536 [FE] fix: textarea의 입력이 1000자를 초과했을 때 실시간으로 에러 메세지를 띄우도록 수정
  frontend/src/hooks/useLongReviewItem.ts
Labels: 🍀 FE, 우선순위: 중, 🐛 버그

#533 [FE] 비밀번호 조회 모달의 배경 화면 클릭 시 모달 닫히는 기능 제거
  frontend/src/components/common/modals/ContentModal/index.tsx
  frontend/src/components/common/modals/ModalBackground/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
Labels: 🍀 FE, 🐛 버그

#534 [All] 리뷰미 v1.0.1 배포
  backend/src/main/java/reviewme/config/SwaggerConfig.java
  frontend/src/components/common/modals/ContentModal/index.tsx
  frontend/src/components/common/modals/ContentModal/styles.ts
  frontend/src/components/common/modals/ModalBackground/index.tsx
  frontend/src/favicons/favicon.ico
  frontend/src/hooks/useLongReviewItem.ts
  frontend/src/pages/HomePage/components/Carousel/index.tsx
  frontend/src/pages/ReviewWritingCardFromPage/components/SubmitCheckModal/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/index.tsx
  frontend/src/pages/ReviewZonePage/components/PasswordModal/styles.ts
Labels: 📦 배포

#538 [BE] test: fixture 추가
  backend/src/test/java/reviewme/fixture/OptionGroupFixture.java
  backend/src/test/java/reviewme/fixture/OptionItemFixture.java
  backend/src/test/java/reviewme/fixture/QuestionFixture.java
  backend/src/test/java/reviewme/fixture/ReviewGroupFixture.java
  backend/src/test/java/reviewme/fixture/SectionFixture.java
  backend/src/test/java/reviewme/fixture/TemplateFixture.java
Labels: ✨ BE, ♻️ 테스트, 💪 아자아자!!
