Repository woowacourse-teams/2024-review-me, pull requests merged in 2024-11, with the labels that each got.

#940 [All] fix: `[Release]` PR 머릿말 디스코드 알림 처리
  .github/workflows/discord-pull-request.yml
Labels: 🐛 버그, 🌏 인프라, 🍰 초간단

#957 [BE] refactor: Config 패키지 분리, 스타일 적용
  backend/src/main/java/reviewme/config/WebConfig.java
  backend/src/main/java/reviewme/config/cors/CorsConfig.java
  backend/src/main/java/reviewme/config/cors/CorsProperties.java
  backend/src/main/java/reviewme/config/datasource/DataSourceType.java
  backend/src/main/java/reviewme/config/datasource/ReplicationDatasourceConfig.java
  backend/src/main/java/reviewme/config/datasource/ReplicationRoutingDataSource.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitInterceptor.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitProperties.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitRedisConfig.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitWebConfig.java
  backend/src/main/java/reviewme/config/requestlimit/TooManyRequestException.java
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/global/exception/FieldErrorResponse.java
  backend/src/main/java/reviewme/review/service/ReviewRegisterService.java
  backend/src/test/java/reviewme/config/cors/CorsConfigTest.java
  backend/src/test/java/reviewme/config/cors/ExternalCorsConfigTest.java
  backend/src/test/java/reviewme/config/cors/LocalCorsConfigTest.java
  backend/src/test/java/reviewme/config/requestlimit/RequestLimitInterceptorTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#959 [All] chore: CODEOWNERS 추가
  .github/CODEOWNERS
Labels: 🍰 초간단

#961 [BE] feat: 하이라이트 벌크 삽입 추가
  backend/src/main/java/reviewme/highlight/repository/HighlightJdbcRepository.java
  backend/src/main/java/reviewme/highlight/repository/HighlightJdbcRepositoryImpl.java
  backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
  backend/src/test/java/reviewme/highlight/repository/HighlightRepositoryTest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
Labels: ✨ BE, 🚀 기능

#962 [BE] refactor: 하이라이트 매핑 로직 간소화
  backend/src/main/java/reviewme/highlight/domain/HighlightedLines.java
  backend/src/main/java/reviewme/highlight/service/HighlightService.java
  backend/src/main/java/reviewme/highlight/service/dto/HighlightRequest.java
  backend/src/main/java/reviewme/highlight/service/dto/HighlightsRequest.java
  backend/src/main/java/reviewme/highlight/service/mapper/HighlightFragment.java
  backend/src/main/java/reviewme/highlight/service/mapper/HighlightMapper.java
  backend/src/test/java/reviewme/highlight/domain/HighlightedLinesTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#966 [BE] refactor/fix: 하이라이트 검증 객체 책임 이동, 하이라이트 삭제 로직 수정
  backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
  backend/src/main/java/reviewme/highlight/service/HighlightService.java
  backend/src/main/java/reviewme/highlight/service/exception/SubmittedAnswerAndProvidedAnswerMismatchException.java
  backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
  backend/src/main/java/reviewme/review/service/exception/QuestionNotContainingAnswersException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewGroupNotContainingAnswersException.java
  backend/src/main/java/reviewme/review/service/validator/AnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/CheckboxTypedAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/ReviewValidator.java
  backend/src/main/java/reviewme/review/service/validator/TextTypedAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/TypedAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/TypedAnswerValidatorFactory.java
  backend/src/test/java/reviewme/highlight/repository/HighlightRepositoryTest.java
  backend/src/test/java/reviewme/highlight/service/validator/HighlightValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/AnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/CheckboxTypedAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/TextTypedAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/TypedTypedAnswerValidatorFactoryTest.java
Labels: ✨ BE, 🐛 버그, 🛠️ 리팩터링, 😱 긴급

#969 [All] fix: Release PR 코드리뷰 시 디스코드 알림
  .github/workflows/discord-pull-request-comment.yml
Labels: 🐛 버그

#976 [FE] fix : 리뷰 모아보기 쿼리 캐시로 인한 변경된 형광펜 데이터 반영 오류 수정
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/index.ts
  frontend/src/constants/storageKey.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
  frontend/src/pages/ReviewCollectionPage/hooks/useGetGroupedReviews.ts
  frontend/src/pages/ReviewCollectionPage/index.tsx
Labels: 🍀 FE, 🐛 버그

#972 [BE] refactor: 2차 정렬 기준 추가
  backend/src/main/java/reviewme/review/repository/AnswerRepository.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
Labels: ✨ BE, 🍰 초간단

#792 [BE] feat: Spring Cache 적용
  backend/build.gradle
  backend/src/main/java/reviewme/config/CacheManagerConfig.java
  backend/src/main/java/reviewme/template/service/mapper/TemplateMapper.java
  backend/src/test/resources/application.yml
Labels: ✨ BE, 🚀 기능

#958 [BE] refactor: question 타입과 답변 내용 일치 검증 및 매핑 로직 개선
  backend/src/main/java/reviewme/review/service/dto/request/ReviewAnswerRequest.java
  backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
  backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
  backend/src/test/java/reviewme/review/service/mapper/AnswerMapperFactoryTest.java
  backend/src/test/java/reviewme/review/service/mapper/CheckboxAnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/TextAnswerMapperTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#983 [BE] refactor: 요청 제한 관련 코드 제거
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitInterceptor.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitProperties.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitRedisConfig.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitWebConfig.java
  backend/src/main/java/reviewme/config/requestlimit/TooManyRequestException.java
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/resources/application.yml
  backend/src/test/java/reviewme/config/requestlimit/RequestLimitInterceptorTest.java
  backend/src/test/resources/application.yml
Labels: ✨ BE, 🍰 초간단

#984 [BE] cd: develop 오라클 인스턴스에서 실행하도록 수정
  .github/workflows/backend-dev-cd.yml
Labels: ✨ BE, 🌏 인프라, 🍰 초간단
