Repository woowacourse-teams/2024-review-me, pull requests merged in 2024-12, with the labels that each got.

#986 [BE] refactor: port config 파일 경로 이동
  backend/src/main/resources/ports.yml
Labels: ✨ BE, 🛠️ 리팩터링, 🍰 초간단

#1008 [Release] 리뷰미 2.0.6 배포
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
  backend/build.gradle
  backend/src/main/java/reviewme/config/CacheManagerConfig.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitInterceptor.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitProperties.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitRedisConfig.java
  backend/src/main/java/reviewme/config/requestlimit/RequestLimitWebConfig.java
  backend/src/main/java/reviewme/config/requestlimit/TooManyRequestException.java
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/review/repository/AnswerRepository.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/dto/request/ReviewAnswerRequest.java
  backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
  backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
  backend/src/main/java/reviewme/template/service/mapper/TemplateMapper.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/ports.yml
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/config/requestlimit/RequestLimitInterceptorTest.java
  backend/src/test/java/reviewme/review/service/mapper/AnswerMapperFactoryTest.java
  backend/src/test/java/reviewme/review/service/mapper/CheckboxAnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/TextAnswerMapperTest.java
  backend/src/test/resources/application.yml
Labels: ✨ BE, 📦 배포

#1004 [BE] chore: release cd를 돌릴 수 있는 브랜치 한정
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 🍰 초간단

#1007 [BE] refactor: 테스트 환경에서 캐싱을 사용하도록 하여 환경 통일
  backend/src/test/java/reviewme/config/TestConfig.java
  backend/src/test/java/reviewme/support/CacheCleaner.java
  backend/src/test/java/reviewme/support/CacheCleanerExtension.java
  backend/src/test/java/reviewme/support/ServiceTest.java
  backend/src/test/resources/application.yml
Labels: ✨ BE, ♻️ 테스트

#999 [BE] refactor: review group 관련 예외를 발생하는 위치의 패키지로 이동
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/reviewgroup/domain/exception/InvalidProjectNameLengthException.java
  backend/src/main/java/reviewme/reviewgroup/domain/exception/InvalidRevieweeNameLengthException.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/reviewgroup/service/exception/ReviewGroupNotFoundByReviewRequestCodeException.java
  backend/src/main/java/reviewme/reviewgroup/service/exception/ReviewGroupUnauthorizedException.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/TemplateApiTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewMapperTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupLookupServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링, 🍰 초간단

#1003 [BE] fix: 잘못된 캐시 키 정정
  backend/src/main/java/reviewme/template/service/mapper/TemplateMapper.java
Labels: ✨ BE, 😱 긴급

#1010 [BE] chore: H2를 테스트에서만 사용하도록 설정
  backend/build.gradle
Labels: ✨ BE, 🌏 인프라, 🍰 초간단

#1011 [BE] refactor: `TemplateMapper`에서 `ReviewGroup` 의존성 제거
  backend/src/main/java/reviewme/template/service/TemplateService.java
  backend/src/main/java/reviewme/template/service/mapper/TemplateMapper.java
  backend/src/test/java/reviewme/template/service/mapper/TemplateMapperTest.java
Labels: ✨ BE, 🛠️ 리팩터링, 🍰 초간단

#1012 [BE] refactor: DTO에서 Enum 사용하도록 수정
  backend/src/main/java/reviewme/template/domain/OptionType.java
  backend/src/main/java/reviewme/template/domain/QuestionType.java
  backend/src/main/java/reviewme/template/service/dto/response/QuestionResponse.java
  backend/src/main/java/reviewme/template/service/dto/response/SectionResponse.java
  backend/src/main/java/reviewme/template/service/mapper/TemplateMapper.java
  backend/src/test/java/reviewme/api/TemplateFixture.java
Labels: ✨ BE, 🛠️ 리팩터링, 🍰 초간단
