Repository woowacourse-teams/2024-review-me, pull requests merged in 2024-10, with the labels that each got.

#758 [FE] design: CardForm의 시작 위치를 고정
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/styles.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인, 🍰 초간단

#761 [Release] 리뷰미 v1.1.1 배포
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewListMockData.ts
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/hooks/useInfiniteScroll.ts
  frontend/src/pages/ReviewWritingPage/form/components/CardForm/styles.ts
Labels: ✨ BE, 🍀 FE, 📦 배포

#779 [BE] fix: Flyway Auto Increment 설정 수정
  backend/src/main/resources/db/migration/V2__answer_abstraction.sql
Labels: ✨ BE

#784 [BE] refactor: Answer 추상화 2단계: 기존 레거시 코드 제거
  backend/src/main/java/reviewme/review/domain/Answer.java
  backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
  backend/src/main/java/reviewme/review/domain/CheckboxAnswerSelectedOption.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/domain/TextAnswer.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswer.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswerRepository.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswerSelectedOption.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewReview.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewReviewRepository.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewTextAnswer.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewTextAnswerRepository.java
  backend/src/main/java/reviewme/review/repository/CheckboxAnswerRepository.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/repository/TextAnswerRepository.java
  backend/src/main/java/reviewme/review/service/ReviewRegisterService.java
  backend/src/main/java/reviewme/review/service/abstraction/mapper/NewAnswerMapper.java
  backend/src/main/java/reviewme/review/service/abstraction/mapper/NewReviewMapper.java
  backend/src/main/java/reviewme/review/service/abstraction/validator/NewAnswerValidator.java
  backend/src/main/java/reviewme/review/service/abstraction/validator/NewReviewValidator.java
  backend/src/main/java/reviewme/review/service/abstraction/validator/NewTextAnswerValidator.java
  backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/AnswerMapperFactory.java
  backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewDetailMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewListMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
  backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/UnsupportedQuestionTypeException.java
  backend/src/main/java/reviewme/review/service/validator/AnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/AnswerValidatorFactory.java
  backend/src/main/java/reviewme/review/service/validator/CheckBoxAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/CheckboxAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/ReviewValidator.java
  backend/src/main/java/reviewme/review/service/validator/TextAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/UnsupportedAnswerTypeException.java
  backend/src/test/java/reviewme/review/domain/ReviewTest.java
  backend/src/test/java/reviewme/review/domain/abstraction/CheckboxAnswerTest.java
  backend/src/test/java/reviewme/review/domain/abstraction/ReviewTest.java
  backend/src/test/java/reviewme/review/domain/abstraction/TextAnswerTest.java
  backend/src/test/java/reviewme/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewRegisterServiceTest.java
  backend/src/test/java/reviewme/review/service/abstraction/mapper/NewReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/abstraction/validator/NewReviewValidatorTest.java
  backend/src/test/java/reviewme/review/service/abstraction/validator/NewTextAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/mapper/AnswerMapperFactoryTest.java
  backend/src/test/java/reviewme/review/service/mapper/AnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/CheckboxAnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewListMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/TextAnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/validator/AnswerValidatorFactoryTest.java
  backend/src/test/java/reviewme/review/service/validator/CheckBoxAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/CheckboxAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/ReviewValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/TextAnswerValidatorTest.java
Labels: ✨ BE, 🌏 인프라, 😁 우하하

#786 [Release] 리뷰미 v1.1.3 배포
  backend/src/main/java/reviewme/review/domain/Answer.java
  backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
  backend/src/main/java/reviewme/review/domain/CheckboxAnswerSelectedOption.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/domain/TextAnswer.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswer.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswerRepository.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswerSelectedOption.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewReview.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewReviewRepository.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewTextAnswer.java
  backend/src/main/java/reviewme/review/domain/abstraction/NewTextAnswerRepository.java
  backend/src/main/java/reviewme/review/repository/CheckboxAnswerRepository.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/repository/TextAnswerRepository.java
  backend/src/main/java/reviewme/review/service/ReviewRegisterService.java
  backend/src/main/java/reviewme/review/service/abstraction/mapper/NewAnswerMapper.java
  backend/src/main/java/reviewme/review/service/abstraction/mapper/NewReviewMapper.java
  backend/src/main/java/reviewme/review/service/abstraction/validator/NewAnswerValidator.java
  backend/src/main/java/reviewme/review/service/abstraction/validator/NewReviewValidator.java
  backend/src/main/java/reviewme/review/service/abstraction/validator/NewTextAnswerValidator.java
  backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/AnswerMapperFactory.java
  backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewDetailMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewListMapper.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
  backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
  backend/src/main/java/reviewme/review/service/mapper/UnsupportedQuestionTypeException.java
  backend/src/main/java/reviewme/review/service/validator/AnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/AnswerValidatorFactory.java
  backend/src/main/java/reviewme/review/service/validator/CheckBoxAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/CheckboxAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/ReviewValidator.java
  backend/src/main/java/reviewme/review/service/validator/TextAnswerValidator.java
  backend/src/main/java/reviewme/review/service/validator/UnsupportedAnswerTypeException.java
  backend/src/test/java/reviewme/review/domain/ReviewTest.java
  backend/src/test/java/reviewme/review/domain/abstraction/CheckboxAnswerTest.java
  backend/src/test/java/reviewme/review/domain/abstraction/ReviewTest.java
  backend/src/test/java/reviewme/review/domain/abstraction/TextAnswerTest.java
  backend/src/test/java/reviewme/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewRegisterServiceTest.java
  backend/src/test/java/reviewme/review/service/abstraction/mapper/NewReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/abstraction/validator/NewReviewValidatorTest.java
  backend/src/test/java/reviewme/review/service/abstraction/validator/NewTextAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/mapper/AnswerMapperFactoryTest.java
  backend/src/test/java/reviewme/review/service/mapper/AnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/CheckboxAnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewListMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/TextAnswerMapperTest.java
  backend/src/test/java/reviewme/review/service/validator/AnswerValidatorFactoryTest.java
  backend/src/test/java/reviewme/review/service/validator/CheckBoxAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/CheckboxAnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/ReviewValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/TextAnswerValidatorTest.java
Labels: 📦 배포

#785 [BE] docs: 리뷰 모아보기 RestDocs 작성
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/review-gather.adoc
  backend/src/docs/asciidoc/review-summary.adoc
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/GatheredReviewLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewSummaryService.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/AnswerContentResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/ReviewsGatheredByQuestionResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/ReviewsGatheredBySectionResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/SimpleQuestionResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/VoteResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewsSummaryResponse.java
  backend/src/main/java/reviewme/template/controller/SectionController.java
  backend/src/main/java/reviewme/template/service/SectionService.java
  backend/src/main/java/reviewme/template/service/dto/response/SectionNameResponse.java
  backend/src/main/java/reviewme/template/service/dto/response/SectionNamesResponse.java
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/TemplateApiTest.java
  backend/src/test/java/reviewme/api/TemplateFixture.java
  backend/src/test/java/reviewme/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
Labels: ✨ BE

#776 [FE] feat: 리뷰 목록/리뷰 모아보기의 공통 UI 및 스위치 컴포넌트, 새 URL 및 디자인 적용
  frontend/src/components/ReviewCard/index.tsx
  frontend/src/components/ReviewCard/styles.ts
  frontend/src/components/common/OptionSwitch/index.tsx
  frontend/src/components/common/OptionSwitch/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/layouts/PageLayout/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/components/ReviewInfoSection/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/components/ReviewInfoSection/styles.ts
  frontend/src/components/layouts/ReviewDisplayLayout/hooks/useReviewDisplayLayoutOptions.ts
  frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/styles.ts
  frontend/src/constants/route.ts
  frontend/src/hooks/useBreadcrumbPaths.ts
  frontend/src/index.tsx
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/pages/ReviewCollectionPage/styles.ts
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/styles.ts
  frontend/src/pages/ReviewListPage/components/ReviewInfoSection/index.tsx
  frontend/src/pages/index.tsx
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 🛠️ 리팩터링, 🎨 디자인, 💪 아자아자!!

#790 [FE] feat: 리뷰 모아보기 페이지의 공통 컴포넌트 구현 및 퍼블리싱
  frontend/src/assets/downArrow.svg
  frontend/src/components/common/Accordion/index.tsx
  frontend/src/components/common/Accordion/styles.ts
  frontend/src/components/common/Dropdown/index.tsx
  frontend/src/components/common/Dropdown/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useAccordion.ts
  frontend/src/hooks/useDropdown.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/pages/ReviewCollectionPage/styles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/review.ts
Labels: 🍀 FE, 🚀 기능, 🎨 디자인

#803 [FE] feat: 리뷰 모아보기에서 질문별 통계 차트 구현
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/pages/ReviewCollectionPage/components/DoughnutChart/index.tsx
  frontend/src/pages/ReviewCollectionPage/components/DoughnutChart/styles.ts
  frontend/src/pages/ReviewCollectionPage/components/DoughnutChartDetails/index.tsx
  frontend/src/pages/ReviewCollectionPage/components/DoughnutChartDetails/styles.ts
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/pages/ReviewCollectionPage/utils/generateGradientColors.ts
Labels: 🍀 FE, 🚀 기능

#783 [FE] feat: 하이라이팅 기능 구현
  frontend/src/apis/collection.ts
  frontend/src/apis/endpoints.ts
  frontend/src/assets/eraser.svg
  frontend/src/assets/highlighter.svg
  frontend/src/assets/trash.svg
  frontend/src/components/highlight/EditSwitchButton/index.tsx
  frontend/src/components/highlight/EditSwitchButton/style.ts
  frontend/src/components/highlight/EditorLineBlock/index.tsx
  frontend/src/components/highlight/HighlightButton/index.tsx
  frontend/src/components/highlight/HighlightButton/style.ts
  frontend/src/components/highlight/HighlightEditor/index.tsx
  frontend/src/components/highlight/HighlightEditor/style.ts
  frontend/src/components/highlight/HighlightRemoverWrapper/index.tsx
  frontend/src/components/highlight/HighlightToggleButtonContainer/index.tsx
  frontend/src/components/highlight/Syntax/index.tsx
  frontend/src/components/highlight/Syntax/style.ts
  frontend/src/constants/highlight.ts
  frontend/src/constants/index.ts
  frontend/src/constants/screenReader.ts
  frontend/src/hooks/highlight/index.tsx
  frontend/src/hooks/highlight/useCheckHighlight.tsx
  frontend/src/hooks/highlight/useHighlight.tsx
  frontend/src/hooks/highlight/useHighlightRemoverPosition.tsx
  frontend/src/hooks/highlight/useHighlightToggleButtonPosition.tsx
  frontend/src/hooks/index.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/collection.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/EditorTestPage/index.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/types/highlight.ts
  frontend/src/types/index.ts
  frontend/src/utils/highlight/highlighList.ts
  frontend/src/utils/highlight/index.ts
  frontend/src/utils/highlight/selection.ts
  frontend/src/utils/index.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 🫠 힘들다...

#816 [FE] feat: 받은 리뷰 정보를 가져오는 API 연동
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/components/ReviewCard/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/components/ReviewInfoSection/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/hooks/index.ts
  frontend/src/components/layouts/ReviewDisplayLayout/hooks/useReviewDisplayLayoutOptions/index.ts
  frontend/src/components/layouts/ReviewDisplayLayout/hooks/useReviewInfoData/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/index.ts
  frontend/src/mocks/mockData/reviewInfoData.ts
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능

#817 [FE] 리뷰 모아보기 페이지 API 로직 연동
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/components/common/Dropdown/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/useDropdown.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/pages/ReviewCollectionPage/hooks/useGetGroupedReviews.ts
  frontend/src/pages/ReviewCollectionPage/hooks/useGetSectionList.ts
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/types/review.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능

#821 [FE] fix: 섹션별 답변 모아보기의 중복 출력 문제 해결 및 리스트 형식으로 출력
  frontend/src/components/highlight/EditorLineBlock/index.tsx
  frontend/src/components/highlight/EditorLineBlock/style.ts
  frontend/src/components/highlight/HighlightEditor/index.tsx
  frontend/src/components/highlight/HighlightEditor/style.ts
  frontend/src/pages/ReviewCollectionPage/index.tsx
Labels: 🍀 FE, 🐛 버그

#823 [FE] feat: 형광펜 모드 on/off 표시 메세지 추가
  frontend/src/assets/grayHighlighter.svg
  frontend/src/assets/primaryHighlighter.svg
  frontend/src/components/highlight/EditSwitchButton/style.ts
  frontend/src/components/highlight/HighlightEditor/index.tsx
  frontend/src/components/highlight/HighlightEditor/style.ts
Labels: 🍀 FE, 🍰 초간단

#801 [BE] feat: 섹션 이름 조회 API 구현
  backend/src/main/java/reviewme/template/service/SectionService.java
  backend/src/test/java/reviewme/template/service/SectionServiceTest.java
Labels: ✨ BE, 🚀 기능

#796 [BE] feat: 받은 리뷰 요약 조회 API 구현
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/review/service/ReviewSummaryService.java
  backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
Labels: ✨ BE, 🚀 기능

#813 [BE] feat: 하이라이트 추가 및 수정 API 구현
  backend/src/main/java/reviewme/highlight/controller/HighlightController.java
  backend/src/main/java/reviewme/highlight/domain/Highlight.java
  backend/src/main/java/reviewme/highlight/domain/HighlightPosition.java
  backend/src/main/java/reviewme/highlight/domain/exception/HighlightStartIndexExceedEndIndexException.java
  backend/src/main/java/reviewme/highlight/domain/exception/NegativeHighlightIndexException.java
  backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
  backend/src/main/java/reviewme/highlight/service/HighlightService.java
  backend/src/main/java/reviewme/highlight/service/exception/HighlightDuplicatedException.java
  backend/src/main/java/reviewme/highlight/service/exception/InvalidHighlightLineIndexException.java
  backend/src/main/java/reviewme/highlight/service/exception/SubmittedAnswerAndProvidedAnswerMismatchException.java
  backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
  backend/src/main/java/reviewme/review/repository/AnswerRepository.java
  backend/src/main/java/reviewme/review/service/exception/AnswerNotFoundByIdException.java
  backend/src/main/java/reviewme/review/service/exception/SubmittedQuestionAndProvidedQuestionMismatchException.java
  backend/src/main/resources/db/migration/V3__create_highlight_table.sql
  backend/src/test/java/reviewme/highlight/domain/HighlightPositionTest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
  backend/src/test/java/reviewme/highlight/service/validator/HighlightValidatorTest.java
  backend/src/test/java/reviewme/review/repository/AnswerRepositoryTest.java
Labels: ✨ BE, 🚀 기능

#806 [BE] feat: 리뷰 모아보기 API 구현
  backend/src/main/java/reviewme/question/repository/QuestionRepository.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/repository/AnswerRepository.java
  backend/src/main/java/reviewme/review/service/GatheredReviewLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/AnswerContentResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/HighlightResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/RangeResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/ReviewsGatheredByQuestionResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/SimpleQuestionResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/TextResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/VoteResponse.java
  backend/src/main/java/reviewme/review/service/exception/GatheredAnswersTypeNonUniformException.java
  backend/src/main/java/reviewme/review/service/exception/SectionNotFoundInTemplateException.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewGatherMapper.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/template/repository/SectionRepository.java
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/question/repository/QuestionRepositoryTest.java
  backend/src/test/java/reviewme/review/repository/AnswerRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewGatheredLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewGatherMapperTest.java
  backend/src/test/java/reviewme/template/repository/SectionRepositoryTest.java
Labels: ✨ BE, 🚀 기능, 💪 아자아자!!

#829 [BE] fix: Highlight 엔티티의 데이터 타입을 db 테이블와 일치시킨다.
  backend/src/main/java/reviewme/highlight/domain/Highlight.java
  backend/src/main/java/reviewme/highlight/domain/HighlightPosition.java
  backend/src/main/java/reviewme/highlight/service/dto/HighlightIndexRangeRequest.java
  backend/src/main/java/reviewme/highlight/service/dto/HighlightedLineRequest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
  backend/src/test/java/reviewme/highlight/service/validator/HighlightValidatorTest.java
Labels: ✨ BE, 🐛 버그

#808 [BE] refactor: NativeQuery를 JPQL로 변환
  backend/src/main/java/reviewme/question/repository/OptionGroupRepository.java
  backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
  backend/src/main/java/reviewme/question/repository/QuestionRepository.java
  backend/src/main/java/reviewme/review/repository/AnswerRepository.java
  backend/src/main/java/reviewme/review/repository/ReviewRepository.java
  backend/src/main/java/reviewme/template/repository/SectionRepository.java
Labels: ✨ BE, 🛠️ 리팩터링

#845 [BE] fix: Dto 하위 필드에 `@Valid` 추가
  backend/src/main/java/reviewme/review/service/dto/request/ReviewRegisterRequest.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
Labels: ✨ BE, 🐛 버그, 🍰 초간단

#844 [BE] feat: UTF-8 설정 추가
  backend/src/main/resources/application.yml
Labels: ✨ BE, 🍰 초간단

#812 [BE] refactor: 리뷰 그룹에 템플릿 정보를 하드코딩 하지 않도록 변경
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/template/service/exception/TemplateNotFoundException.java
  backend/src/test/java/reviewme/fixture/ReviewGroupFixture.java
  backend/src/test/java/reviewme/reviewgroup/ReviewGroupTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupLookupServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링, 🍰 초간단

#843 [BE] refactor: 세션을 가져오는 역할을 `ReviewGroupSessionResolver`에 위임
  backend/src/main/java/reviewme/config/WebConfig.java
  backend/src/main/java/reviewme/global/HeaderProperty.java
  backend/src/main/java/reviewme/global/HeaderPropertyArgumentResolver.java
  backend/src/main/java/reviewme/global/exception/MissingHeaderPropertyException.java
  backend/src/main/java/reviewme/highlight/controller/HighlightController.java
  backend/src/main/java/reviewme/highlight/service/HighlightService.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewSummaryService.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupSession.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupSessionNotFoundException.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupSessionResolver.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/template/controller/SectionController.java
  backend/src/main/java/reviewme/template/service/SectionService.java
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/TemplateApiTest.java
  backend/src/test/java/reviewme/config/CorsConfigTest.java
  backend/src/test/java/reviewme/config/ExternalCorsConfigTest.java
  backend/src/test/java/reviewme/config/LocalCorsConfigTest.java
  backend/src/test/java/reviewme/global/HeaderPropertyArgumentResolverTest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewGatheredLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/controller/ReviewGroupSessionResolverTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
  backend/src/test/java/reviewme/template/service/SectionServiceTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#859 [BE] refactor: 도메인을 활용한 하이라이트 추가 및 수정 로직 리팩토링
  backend/src/main/java/reviewme/highlight/controller/HighlightController.java
  backend/src/main/java/reviewme/highlight/domain/Highlight.java
  backend/src/main/java/reviewme/highlight/domain/HighlightRange.java
  backend/src/main/java/reviewme/highlight/domain/HighlightedLine.java
  backend/src/main/java/reviewme/highlight/domain/HighlightedLines.java
  backend/src/main/java/reviewme/highlight/domain/exception/HighlightIndexExceedLineLengthException.java
  backend/src/main/java/reviewme/highlight/domain/exception/HighlightStartIndexExceedEndIndexException.java
  backend/src/main/java/reviewme/highlight/domain/exception/InvalidHighlightIndexRangeException.java
  backend/src/main/java/reviewme/highlight/domain/exception/InvalidHighlightLineIndexException.java
  backend/src/main/java/reviewme/highlight/domain/exception/NegativeHighlightIndexException.java
  backend/src/main/java/reviewme/highlight/domain/exception/NegativeHighlightLineIndexException.java
  backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
  backend/src/main/java/reviewme/highlight/service/HighlightService.java
  backend/src/main/java/reviewme/highlight/service/dto/HighlightsRequest.java
  backend/src/main/java/reviewme/highlight/service/exception/HighlightDuplicatedException.java
  backend/src/main/java/reviewme/highlight/service/mapper/HighlightMapper.java
  backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
  backend/src/main/java/reviewme/review/domain/TextAnswers.java
  backend/src/main/java/reviewme/review/repository/AnswerRepository.java
  backend/src/test/java/reviewme/highlight/domain/HighlightPositionTest.java
  backend/src/test/java/reviewme/highlight/domain/HighlightedLineTest.java
  backend/src/test/java/reviewme/highlight/domain/HighlightedLinesTest.java
  backend/src/test/java/reviewme/highlight/entity/HighlightRangeTest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
  backend/src/test/java/reviewme/highlight/service/mapper/HighlightMapperTest.java
  backend/src/test/java/reviewme/highlight/service/validator/HighlightValidatorTest.java
  backend/src/test/java/reviewme/review/domain/TextAnswersTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#834 [BE] fix: 질문을 position 순서대로 내려주도록 로직 수정
  backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
  backend/src/test/java/reviewme/review/service/ReviewGatheredLookupServiceTest.java
Labels: ✨ BE, 우선순위: 상, 🐛 버그

#837 [FE] fix: 차트에서 0% 비율 제외 및 객관식 질문을 투표수 기준으로 내림차순 정렬
  frontend/src/components/ReviewCard/index.tsx
  frontend/src/components/ReviewCard/styles.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/mocks/mockData/reviewListMockData.ts
  frontend/src/pages/ReviewCollectionPage/components/DoughnutChart/index.tsx
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/pages/ReviewCollectionPage/utils/generateGradientColors.ts
Labels: 🍀 FE, 🐛 버그, 🛠️ 리팩터링

#853 [FE] feat: 커스텀한 ErrorBoudary 생성 및 react-error-boundary 삭제
  frontend/package.json
  frontend/src/components/error/AuthAndServerErrorFallback/index.tsx
  frontend/src/components/error/ErrorBoundary.tsx
  frontend/src/components/error/ErrorFallback/index.tsx
  frontend/src/components/error/ErrorSuspenseContainer/index.tsx
  frontend/src/components/error/index.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/pages/ReviewWritingPage/modals/components/CardFormModalContainer/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitErrorModal/index.tsx
  frontend/yarn.lock
Labels: 🍀 FE, 🚀 기능

#856 [FE] design: 리뷰 작성 페이지 모달 글자 가운데 정렬
  frontend/src/pages/ReviewWritingPage/modals/components/NavigateBlockerModal/style.ts
  frontend/src/pages/ReviewWritingPage/modals/components/StrengthUnCheckModal/style.ts
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitCheckModal/style.ts
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitErrorModal/style.ts
Labels: 🍀 FE, 🎨 디자인

#854 [FE] test : 형광펜 API 테스트 추가 및 쿠키 관련 목 핸들러 리팩토링 및 토스트 모달 준비 작업 진행
  frontend/src/apis/collection.ts
  frontend/src/apis/highlight.ts
  frontend/src/components/error/ErrorBoundary/index.tsx
  frontend/src/components/highlight/components/EditSwitchButton/index.tsx
  frontend/src/components/highlight/components/EditSwitchButton/style.ts
  frontend/src/components/highlight/components/EditorLineBlock/index.tsx
  frontend/src/components/highlight/components/EditorLineBlock/style.ts
  frontend/src/components/highlight/components/HighlightButton/index.tsx
  frontend/src/components/highlight/components/HighlightButton/style.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/index.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useCheckHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightRemoverPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightToggleButtonPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/index.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/test.ts
  frontend/src/components/highlight/components/HighlightEditor/index.tsx
  frontend/src/components/highlight/components/HighlightEditor/style.ts
  frontend/src/components/highlight/components/HighlightEditorContainer/index.tsx
  frontend/src/components/highlight/components/HighlightRemoverWrapper/index.tsx
  frontend/src/components/highlight/components/HighlightToggleButtonContainer/index.tsx
  frontend/src/components/highlight/components/Syntax/index.tsx
  frontend/src/components/highlight/components/Syntax/style.ts
  frontend/src/components/highlight/components/index.tsx
  frontend/src/components/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/review/useGetDetailedReview/test.ts
  frontend/src/hooks/review/useGetReviewList/test.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/collection.ts
  frontend/src/mocks/handlers/cookies.ts
  frontend/src/mocks/handlers/highlight.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/pages/EditorTestPage/index.tsx
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/utils/index.ts
  frontend/src/utils/testUtils/index.ts
  frontend/src/utils/testUtils/testWithAuthCookie.ts
Labels: 🍀 FE, 🚀 기능, ♻️ 테스트

#839 [FE] fix: 리뷰 목록 페이지에서 preview가 짧을 때 스타일이 깨지던 현상 수정 및 명시적인 ellipsis 설정
  frontend/src/components/ReviewCard/index.tsx
  frontend/src/components/ReviewCard/styles.ts
Labels: 🍀 FE, 우선순위: 상, 🐛 버그, 🚀 기능, 🎨 디자인

#840 [FE] fix : 형광펜 위치,모바일 동작 오류 수정
  frontend/src/components/highlight/components/DragHighlightButtonContainer/index.tsx
  frontend/src/components/highlight/components/HighlightButton/index.tsx
  frontend/src/components/highlight/components/HighlightButton/style.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/index.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useCheckHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useDragHighlightButtonPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useEditableState.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightEventListener.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightRemoverPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightToggleButtonPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useLongPress.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useLongPressHighlightButtonPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/index.tsx
  frontend/src/components/highlight/components/HighlightRemoverWrapper/index.tsx
  frontend/src/components/highlight/components/LongPressHighlightButtonWrapper/index.tsx
  frontend/src/components/highlight/components/Syntax/style.ts
  frontend/src/constants/highlight.ts
  frontend/src/constants/index.ts
  frontend/src/constants/sessionStorageKey.ts
  frontend/src/mocks/handlers/highlight.ts
  frontend/src/utils/highlight/highlighList.ts
  frontend/src/utils/highlight/selection.ts
  frontend/src/utils/index.ts
  frontend/src/utils/touchDevice.ts
Labels: 🍀 FE, 🐛 버그, 🚀 기능

#876 [BE] feat: 하이라이트 정보 함께 조회
  backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
  backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
  backend/src/main/java/reviewme/review/service/dto/response/gathered/RangeResponse.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewGatherMapper.java
  backend/src/test/java/reviewme/highlight/repository/HighlightRepositoryTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewGatherMapperTest.java
Labels: ✨ BE, 🚀 기능, 🫠 힘들다...

#886 [BE] chore: 무중단 배포 개발 서버에 적용하는 cd 작성
  .github/workflows/zero-downtime-deploy-test-cd.yml
  backend/src/main/resources/ports.yml
Labels: ✨ BE, 🌏 인프라

#858 [FE] fix: 모아보기 페이지 버그 수정
  frontend/src/components/common/Accordion/index.tsx
  frontend/src/components/common/Accordion/styles.ts
  frontend/src/components/common/ReviewEmptySection/index.tsx
  frontend/src/components/common/ReviewEmptySection/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/components/highlight/components/EditorLineBlock/index.tsx
  frontend/src/components/highlight/components/EditorLineBlock/style.ts
  frontend/src/components/highlight/components/HighlightEditor/index.tsx
  frontend/src/components/highlight/components/HighlightEditor/style.ts
  frontend/src/components/layouts/ReviewDisplayLayout/ReviewInfoDataProvider.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/components/ReviewInfoSection/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/styles.ts
  frontend/src/constants/review.ts
  frontend/src/hooks/useAccordion.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/styles.ts
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewEmptySection/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewListPageContents/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewListPageContents/styles.ts
  frontend/src/pages/ReviewListPage/index.tsx
Labels: 🍀 FE, 🐛 버그

#874 [FE] feat: 형광펜 메뉴 및 툴팁 구현
  frontend/src/assets/grayHighlighter.svg
  frontend/src/assets/helper.svg
  frontend/src/assets/primaryHighlighter.svg
  frontend/src/components/common/UndraggableWrapper/styles.ts
  frontend/src/components/highlight/components/DragHighlightButtonContainer/index.tsx
  frontend/src/components/highlight/components/EditSwitchButton/style.ts
  frontend/src/components/highlight/components/EditorLineBlock/index.tsx
  frontend/src/components/highlight/components/EditorLineBlock/style.ts
  frontend/src/components/highlight/components/HighlightButton/index.tsx
  frontend/src/components/highlight/components/HighlightButton/style.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/index.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useCheckHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useDragHighlightPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useEditableState.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightEventListener.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightMenuPosition/index.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useLongPressHighlightButtonPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useLongPressHighlightPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/index.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/test.ts
  frontend/src/components/highlight/components/HighlightEditor/index.tsx
  frontend/src/components/highlight/components/HighlightEditor/style.ts
  frontend/src/components/highlight/components/HighlightMenu/index.tsx
  frontend/src/components/highlight/components/HighlightMenu/style.ts
  frontend/src/components/highlight/components/LongPressHighlightButtonWrapper/index.tsx
  frontend/src/components/highlight/components/Syntax/style.ts
  frontend/src/components/highlight/components/Tooltip/index.tsx
  frontend/src/components/highlight/components/Tooltip/style.ts
  frontend/src/constants/highlight.ts
  frontend/src/constants/index.ts
  frontend/src/constants/screenReader.ts
  frontend/src/constants/sessionStorageKey.ts
  frontend/src/mocks/handlers/highlight.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/styles/globalStyles.ts
  frontend/src/types/highlight.ts
  frontend/src/utils/highlight/highlighList.ts
  frontend/src/utils/highlight/selection.ts
Labels: 🍀 FE, 🐛 버그, 🚀 기능

#866 [FE] fix: 리뷰 작성 완료 페이지에 url로 직접 접근하는 행위 방지
  frontend/src/components/common/Breadcrumb/index.tsx
  frontend/src/components/error/ErrorSection/index.tsx
  frontend/src/hooks/useBreadcrumbPaths.ts
  frontend/src/pages/ReviewWritingCompletePage/index.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/answers/useSubmitAnswers.ts
  frontend/src/pages/ReviewZonePage/index.tsx
Labels: 🍀 FE, 🐛 버그

#889 [FE] feat: Checkbox, CheckboxItem 컴포넌트 접근성 개선
  frontend/src/components/common/Checkbox/index.tsx
  frontend/src/components/common/CheckboxItem/index.tsx
  frontend/src/components/common/CheckboxItem/styles.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능

#897 [FE] fix: api 중복 요청 방지
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/index.ts
  frontend/src/pages/HomePage/hooks/usePostDataForReviewRequestCode/index.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/useMutateReview/index.ts
Labels: 🍀 FE, 🐛 버그

#891 [FE] 리뷰 작성 페이지에서 동적으로 에러가 생기는 경우, 해당 에러를 읽어주는 기능
  frontend/src/pages/ReviewWritingPage/form/components/MultipleChoiceAnswer/index.tsx
  frontend/src/pages/ReviewWritingPage/form/components/TextAnswer/index.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/index.ts
  frontend/src/pages/ReviewWritingPage/form/hooks/useFocusMessage.ts
  frontend/src/styles/globalStyles.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능

#881 [FE] feat: 현재 리뷰 작성 카드에만 tab 이동하는 기능 구현 및 로고,BreadCrumb 포커스 이동 구현
  frontend/src/assets/logo.svg
  frontend/src/components/common/Breadcrumb/index.tsx
  frontend/src/components/layouts/Topbar/components/Logo/index.tsx
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/pages/ReviewWritingPage/slider/components/CardSlider/index.tsx
  frontend/src/pages/ReviewWritingPage/slider/hooks/ally/useTabNavigationOnValidity.ts
  frontend/src/pages/ReviewWritingPage/slider/hooks/index.ts
  frontend/src/styles/reset.ts
Labels: 🍀 FE, 🚀 기능, 💪 아자아자!!

#898 [FE] feat: Amplitude를 통한 사용자 데이터 수집 기능 구현
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/highlight/components/HighlightEditor/hooks/useEditableState.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/layouts/ReviewDisplayLayout/hooks/useReviewDisplayLayoutOptions/index.ts
  frontend/src/constants/amplitudeEventName.ts
  frontend/src/constants/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useTrackVisitedPageInAmplitude.ts
  frontend/src/index.tsx
  frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/SubmitCheckModal/index.tsx
  frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
  frontend/src/router.tsx
  frontend/src/types/amplitude.ts
  frontend/src/types/index.ts
  frontend/src/utils/analytics/amplitude.ts
  frontend/src/utils/analytics/index.ts
  frontend/src/utils/analytics/sentry.ts
  frontend/src/utils/index.ts
  frontend/src/utils/mockWorkerStarter.ts
  frontend/src/utils/queryRetrier.ts
  frontend/yarn.lock
Labels: 🍀 FE, 🚀 기능

#902 [FE] fix: 리뷰 모아보기, 리뷰 목록 스위치 오류 해결
  frontend/src/components/layouts/ReviewDisplayLayout/hooks/useReviewDisplayLayoutOptions/index.ts
Labels: 🍀 FE, 🐛 버그

#905 [FE] fix: Toast가 나타난 후 클릭 및 드래그 불가 이슈 해결
  frontend/src/components/common/Portal/index.tsx
  frontend/src/components/common/Portal/styles.ts
  frontend/src/components/common/Toast/styles.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/pages/ReviewCollectionPage/components/DoughnutChart/styles.ts
  frontend/src/pages/ReviewCollectionPage/components/DoughnutChartDetails/styles.ts
Labels: 🍀 FE, 🐛 버그, 😱 긴급

#907 [FE] fix : 형광펜 endIndex 오류 및 api 오류 시 isEditable 오류 수정
  frontend/src/apis/highlight.ts
  frontend/src/components/highlight/components/EditorLineBlock/style.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useEditableState.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/index.ts
  frontend/src/components/highlight/components/HighlightEditorContainer/index.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/storageKey.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/types/highlight.ts
Labels: 🍀 FE, 🐛 버그

#883 [FE] feat: 작성 페이지의 버튼 활성화 상태 및 현재 섹션 정보를 스크린 리더가 인식하도록 개선
  frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
  frontend/src/pages/ReviewWritingPage/progressBar/components/ProgressBar/index.tsx
  frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
Labels: 🍀 FE, 🚀 기능

#906 [FE] feat: 리뷰 작성 페이지 모달 접근성 개선
  frontend/src/components/common/FocusTrap/index.tsx
  frontend/src/components/common/FocusTrap/styles.ts
  frontend/src/components/common/modals/AlertModal/index.tsx
  frontend/src/components/common/modals/ConfirmModal/index.tsx
  frontend/src/components/common/modals/ContentModal/index.tsx
  frontend/src/pages/ReviewWritingPage/modals/components/AnswerListRecheckModal/index.tsx
Labels: 🍀 FE, 🚀 기능

#914 [FE] fix: textarea가 없는 리뷰 작성 카드에서 tab키로 다른 리뷰 섹션에 접근할 수 있는 문제 수정
  frontend/src/components/common/CheckboxItem/index.tsx
  frontend/src/pages/ReviewWritingPage/slider/hooks/ally/useTabNavigationOnValidity.ts
Labels: 🍀 FE, 우선순위: 상, 🐛 버그, 😱 긴급

#915 [FE] feat: 메타 데이터 설정 및 OptionSwitch 디자인 수정
  frontend/public/index.html
  frontend/src/assets/metaImage.svg
  frontend/src/components/common/OptionSwitch/styles.ts
  frontend/src/components/layouts/ReviewDisplayLayout/styles.ts
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/styles.ts
Labels: 🍀 FE, 🚀 기능, 🎨 디자인

#920 [Release] 리뷰미 v2.0.1
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
  .github/workflows/zero-downtime-deploy-test-cd.yml
Labels: ✨ BE, 🌏 인프라

#922 [FE] fix: ios에서 형광펜 안되는 오류 수정 및 형광펜 색상 변경
  frontend/src/components/highlight/components/HighlightEditor/hooks/useDragHighlightPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightEventListener.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightRemoverPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightToggleButtonPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/style.ts
  frontend/src/components/highlight/components/HighlightMenu/index.tsx
  frontend/src/components/highlight/components/HighlightToggleButtonContainer/index.tsx
  frontend/src/components/highlight/components/Syntax/style.ts
  frontend/src/components/layouts/Topbar/components/Logo/index.tsx
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/device.ts
  frontend/src/utils/highlight/selection.ts
  frontend/src/utils/index.ts
Labels: 🍀 FE, 🐛 버그, 🎨 디자인, 😱 긴급

#917 [FE] feat: URL 모달이 떠있는 동안 뒤로가기, 새로고침 방지
  frontend/src/pages/HomePage/components/ReviewZoneURLModal/index.tsx
Labels: 🍀 FE, 우선순위: 상, 🐛 버그

#926 [FE] refactor: merge 과정에서 없어진 차트 내림차순 정렬 코드 복원 및 링크 공유 시, 양옆 여백 이슈 해결을 위한 메타 데이터 수정
  frontend/src/assets/metaImage.svg
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
Labels: 🍀 FE, 🍰 초간단

#929 [Release] 리뷰미 v2.0.2 배포
  frontend/src/assets/metaImage.svg
  frontend/src/components/highlight/components/HighlightEditor/hooks/useDragHighlightPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightEventListener.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightRemoverPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlightToggleButtonPosition.ts
  frontend/src/components/highlight/components/HighlightEditor/style.ts
  frontend/src/components/highlight/components/HighlightMenu/index.tsx
  frontend/src/components/highlight/components/HighlightToggleButtonContainer/index.tsx
  frontend/src/components/highlight/components/Syntax/style.ts
  frontend/src/components/layouts/Topbar/components/Logo/index.tsx
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/pages/HomePage/components/ReviewZoneURLModal/index.tsx
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/device.ts
  frontend/src/utils/highlight/selection.ts
  frontend/src/utils/index.ts
Labels: ✨ BE, 🍀 FE, 📦 배포

#932 [FE] fix : 질문 섹션 변경 시, 변경된 형광펜 상태 적용되지 않는 오류 수정 및 리뷰 모아보기 목 핸들러,목 데이터 변경
  frontend/src/apis/endpoints.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditorContainer/index.tsx
  frontend/src/constants/storageKey.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/pages/ReviewCollectionPage/index.tsx
Labels: 🍀 FE, 🐛 버그, 😱 긴급

#936 [FE] fix: 모든 아코디언을 기본적으로 닫힌 상태로 두기
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
Labels: 🍀 FE, 🍰 초간단

#937 [BE] fix: 존재하지 않는 질문 ID로 가져오는 경우 예외 처리
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
Labels: ✨ BE, 🐛 버그

#939 [FE] design: 아코디언 header의 모든 영역을 클릭 가능하도록 수정
  frontend/src/components/common/Accordion/styles.ts
Labels: 🍀 FE, 🎨 디자인

#942 [Release] 리뷰미 v2.0.3 배포
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
  frontend/src/apis/endpoints.ts
  frontend/src/components/common/Accordion/styles.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditorContainer/index.tsx
  frontend/src/constants/storageKey.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewCollection.ts
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
  frontend/src/pages/ReviewCollectionPage/index.tsx
Labels: ✨ BE, 🍀 FE, 📦 배포

#927 [All] README 업데이트
  README.md
Labels: 😁 우하하

#947 [BE] cd-fix: 배포 시 새로운 이미지를 pull하도록 수정
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 🐛 버그, 🌏 인프라

#948 [BE] chore: 도커 태그 지정 방식 변경
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
Labels: ✨ BE, 🌏 인프라, 😱 긴급

#951 [BE] 예외의 잘못된 로그레벨 수정 및 사용하지 않는 예외 제거
  backend/src/main/java/reviewme/highlight/domain/exception/HighlightStartIndexExceedEndIndexException.java
  backend/src/main/java/reviewme/review/domain/exception/MissingTextAnswerForQuestionException.java
  backend/src/main/java/reviewme/review/service/exception/AnswerNotFoundByIdException.java
  backend/src/main/java/reviewme/review/service/exception/InvalidTextAnswerLengthException.java
  backend/src/main/java/reviewme/review/service/exception/SubmittedQuestionAndProvidedQuestionMismatchException.java
Labels: ✨ BE, 🛠️ 리팩터링

#952 [BE] docs: 리드미에 인프라 구조 추가
  README.md
Labels: 📋 문서
