Repository woowacourse-teams/2024-review-me, pull requests merged in 2025-02, with the labels that each got.

#1060 [BE] 깃허브 인증 구현과 세션 권한 체계 설계
  backend/src/main/java/reviewme/ReviewMeApplication.java
  backend/src/main/java/reviewme/auth/controller/AuthController.java
  backend/src/main/java/reviewme/auth/domain/GitHubMember.java
  backend/src/main/java/reviewme/auth/infrastructure/GitHubOAuthClient.java
  backend/src/main/java/reviewme/auth/infrastructure/dto/request/GitHubAccessTokenRequest.java
  backend/src/main/java/reviewme/auth/infrastructure/dto/response/GitHubAccessTokenResponse.java
  backend/src/main/java/reviewme/auth/infrastructure/dto/response/GitHubUserInfoResponse.java
  backend/src/main/java/reviewme/auth/infrastructure/exception/GitHubOAuthFailedException.java
  backend/src/main/java/reviewme/auth/service/AuthService.java
  backend/src/main/java/reviewme/auth/service/GitHubMemberService.java
  backend/src/main/java/reviewme/config/client/ClientConfig.java
  backend/src/main/java/reviewme/config/client/GitHubOAuthProperties.java
  backend/src/main/java/reviewme/config/client/GitHubUserProperties.java
  backend/src/main/java/reviewme/global/session/SessionManager.java
  backend/src/main/java/reviewme/member/domain/Member.java
  backend/src/main/java/reviewme/member/repository/MemberRepository.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V5__create_member_table.sql
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/api/AuthApiTest.java
  backend/src/test/java/reviewme/auth/service/AuthServiceTest.java
  backend/src/test/java/reviewme/auth/service/GitHubMemberServiceTest.java
  backend/src/test/java/reviewme/global/session/SessionManagerTest.java
  backend/src/test/resources/application.yml
Labels: ✨ BE, 🚀 기능

#1081 [BE] refactor: 비회원 인증을 Auth에서 하도록 변경
  backend/src/main/java/reviewme/auth/controller/AuthController.java
  backend/src/main/java/reviewme/auth/service/AuthService.java
  backend/src/main/java/reviewme/auth/service/exception/ReviewGroupUnauthorizedException.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/test/java/reviewme/api/AuthApiTest.java
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/auth/service/AuthServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
Labels: ✨ BE, 우선순위: 상

#1083 [BE] test: api테스트 오류 수정
  backend/src/test/java/reviewme/api/AuthApiTest.java
Labels: ✨ BE, 우선순위: 상, ♻️ 테스트, 🍰 초간단

#1072 [FE] feat : 회원용 리뷰 그룹 생성 API 연결 및 관련 목서버 셋팅 수정
  frontend/src/apis/group.ts
  frontend/src/components/reviewURL/URLGeneratorForm/components/URLGeneratorButton/index.tsx
  frontend/src/components/reviewURL/URLGeneratorForm/hooks/usePostDataForReviewRequestCode/index.ts
  frontend/src/components/reviewURL/URLGeneratorForm/hooks/usePostDataForReviewRequestCode/test.tsx
  frontend/src/hooks/reviewGroup/useGetReviewGroupData/test.ts
  frontend/src/mocks/handlers/group.ts
  frontend/src/mocks/mockData/group.ts
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkDashboard/index.tsx
  frontend/src/types/reviewGroup.ts
  frontend/src/utils/mockingUtils.ts
Labels: 🍀 FE, 🚀 기능, 🛠️ 리팩터링, ♻️ 테스트

#1075 [BE] refactor: 회원 추가로 인한 스키마 변경
  backend/build.gradle
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/service/ReviewRegisterService.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/domain/GroupAccessCode.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/reviewgroup/service/exception/GroupAccessCodeNullException.java
  backend/src/main/resources/db/migration/V6__member_id_add.sql
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/fixture/ReviewFixture.java
  backend/src/test/java/reviewme/fixture/ReviewGroupFixture.java
  backend/src/test/java/reviewme/highlight/domain/HighlightedLinesTest.java
  backend/src/test/java/reviewme/highlight/repository/HighlightRepositoryTest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
  backend/src/test/java/reviewme/highlight/service/mapper/HighlightMapperTest.java
  backend/src/test/java/reviewme/review/domain/ReviewTest.java
  backend/src/test/java/reviewme/review/domain/abstraction/ReviewTest.java
  backend/src/test/java/reviewme/review/repository/AnswerRepositoryTest.java
  backend/src/test/java/reviewme/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewGatheredLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewRegisterServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewGatherMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewListMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/validator/AnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/ReviewValidatorTest.java
  backend/src/test/java/reviewme/reviewgroup/ReviewGroupTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupLookupServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
Labels: ✨ BE, 우선순위: 중, 🛠️ 리팩터링

#1078 [BE] refactor: 기존 api가 리뷰 그룹 정보를 포함하도록 수정
  backend/src/main/java/reviewme/highlight/controller/HighlightController.java
  backend/src/main/java/reviewme/highlight/service/HighlightService.java
  backend/src/main/java/reviewme/highlight/service/dto/HighlightsRequest.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewSummaryService.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/domain/exception/ReviewGroupNotFoundException.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupSummaryResponse.java
  backend/src/main/java/reviewme/template/controller/SectionController.java
  backend/src/main/java/reviewme/template/service/DefaultTemplateService.java
  backend/src/main/java/reviewme/template/service/TemplateService.java
  backend/src/main/java/reviewme/template/service/exception/DefaultTemplateNotFoundException.java
  backend/src/test/java/reviewme/api/HighlightApiTest.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/api/TemplateApiTest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
  backend/src/test/java/reviewme/highlight/service/mapper/HighlightMapperTest.java
  backend/src/test/java/reviewme/review/service/ReviewGatheredLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupLookupServiceTest.java
  backend/src/test/java/reviewme/template/service/DefaultTemplateServiceTest.java
  backend/src/test/java/reviewme/template/service/TemplateServiceTest.java
Labels: ✨ BE, 📋 문서

#1091 [BE] docs: 리뷰 요청, 확인 코드 일치 여부 문서 위치 변경
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/reviewgroup.adoc
Labels: 🍰 초간단

#1106 [BE] fix: 스키마 마이그레이션 스크립트 수정
  backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
  backend/src/main/java/reviewme/review/domain/CheckboxAnswerSelectedOption.java
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/review/domain/TextAnswer.java
  backend/src/main/resources/db/migration/V7__review_table_change.sql
Labels: ✨ BE, 우선순위: 상

#1094 [BE] feat: 컨트롤러에서 리졸버를 통해 세션 저장 정보를 사용
  backend/src/main/java/reviewme/auth/controller/AuthController.java
  backend/src/main/java/reviewme/config/WebConfig.java
  backend/src/main/java/reviewme/highlight/controller/HighlightController.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewRegisterService.java
  backend/src/main/java/reviewme/review/service/exception/ReviewNotFoundByIdAndGroupException.java
  backend/src/main/java/reviewme/review/service/exception/ReviewNotFoundException.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupSessionNotFoundException.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupSessionResolver.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
  backend/src/main/java/reviewme/security/resolver/GuestReviewGroupSession.java
  backend/src/main/java/reviewme/security/resolver/GuestReviewGroupSessionResolver.java
  backend/src/main/java/reviewme/security/resolver/LoginMemberSession.java
  backend/src/main/java/reviewme/security/resolver/LoginMemberSessionResolver.java
  backend/src/main/java/reviewme/security/resolver/dto/GuestReviewGroup.java
  backend/src/main/java/reviewme/security/resolver/dto/LoginMember.java
  backend/src/main/java/reviewme/security/resolver/exception/GuestReviewGroupSessionNotExistsException.java
  backend/src/main/java/reviewme/security/resolver/exception/LoginMemberSessionNotExistsException.java
  backend/src/main/java/reviewme/security/session/SessionManager.java
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/api/AuthApiTest.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/global/session/SessionManagerTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/controller/ReviewGroupSessionResolverTest.java
  backend/src/test/java/reviewme/security/resolver/GuestReviewGroupSessionResolverTest.java
  backend/src/test/java/reviewme/security/resolver/LoginMemberSessionResolverTest.java
Labels: ✨ BE, 🚀 기능

#1095 [FE] fix: 오픈 그래프 이미지 형식을 SVG에서 PNG로 변경
  frontend/public/index.html
  frontend/public/ogImage.png
Labels: 🍀 FE, 🍰 초간단

#1098 [BE] feat: 회원이 등록한 리뷰 그룹들을 조회하는 기능 구현
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupPageElementResponse.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupPageResponse.java
  backend/src/main/java/reviewme/util/PageSize.java
  backend/src/main/resources/db/migration/V8__review_group_created_at_add.sql
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/fixture/ReviewGroupFixture.java
  backend/src/test/java/reviewme/highlight/repository/HighlightRepositoryTest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
  backend/src/test/java/reviewme/highlight/service/mapper/HighlightMapperTest.java
  backend/src/test/java/reviewme/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewGatheredLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewRegisterServiceTest.java
  backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewListMapperTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewMapperTest.java
  backend/src/test/java/reviewme/review/service/validator/AnswerValidatorTest.java
  backend/src/test/java/reviewme/review/service/validator/ReviewValidatorTest.java
  backend/src/test/java/reviewme/reviewgroup/repository/ReviewGroupRepositoryTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupLookupServiceTest.java
  backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupServiceTest.java
  backend/src/test/java/reviewme/template/service/TemplateServiceTest.java
  backend/src/test/java/reviewme/util/PageSizeTest.java
Labels: ✨ BE, 우선순위: 상, 🚀 기능

#1111 [BE] docs: 내가 받은 리뷰 api 문서에 ReviewRequestCode 제거
  backend/src/test/java/reviewme/api/ReviewApiTest.java
Labels: ✨ BE, 📋 문서, 🍰 초간단

#1120 [FE] feat: 변경되는 API요청 URL 적용
  frontend/src/apis/endpoints.ts
  frontend/src/apis/group.ts
  frontend/src/apis/highlight.ts
  frontend/src/apis/review.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/index.ts
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/test.ts
  frontend/src/components/highlight/components/HighlightEditor/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/ReviewInfoDataProvider.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/hooks/useReviewInfoData/index.tsx
  frontend/src/components/reviewURL/URLGeneratorForm/hooks/usePostDataForReviewRequestCode/test.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/hooks/review/useGetReviewList/test.ts
  frontend/src/hooks/useReviewRequestCodeParam.ts
  frontend/src/mocks/handlers/group.ts
  frontend/src/mocks/handlers/highlight.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/reviewWriting/reviewFormResultData.ts
  frontend/src/mocks/mockData/reviewWriting/reviewQuestionData.ts
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
  frontend/src/pages/ReviewCollectionPage/hooks/useGetGroupedReviews.ts
  frontend/src/pages/ReviewListPage/components/ReviewListPageContents/index.tsx
  frontend/src/pages/ReviewWritingPage/form/hooks/question/useGetDataToWrite/test.ts
  frontend/src/pages/ReviewZonePage/index.tsx
Labels: 🍀 FE, 우선순위: 상, 🚀 기능

#1089 [BE] feat: 리소스 접근 권한 검증 aop 구현
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/global/exception/ForbiddenException.java
  backend/src/main/java/reviewme/highlight/controller/HighlightController.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/exception/ReviewNotFoundException.java
  backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
  backend/src/main/java/reviewme/security/aspect/RequireReviewAccess.java
  backend/src/main/java/reviewme/security/aspect/RequireReviewGroupAccess.java
  backend/src/main/java/reviewme/security/aspect/ResourceAuthorizationUtils.java
  backend/src/main/java/reviewme/security/aspect/ReviewAuthorizationAspect.java
  backend/src/main/java/reviewme/security/aspect/ReviewGroupAuthorizationAspect.java
  backend/src/main/java/reviewme/security/aspect/exception/ForbiddenReviewAccessException.java
  backend/src/main/java/reviewme/security/aspect/exception/ForbiddenReviewGroupAccessException.java
  backend/src/main/java/reviewme/security/aspect/exception/SpELEvaluationFailedException.java
  backend/src/test/java/reviewme/fixture/MemberFixture.java
  backend/src/test/java/reviewme/security/aspect/AopTestClass.java
  backend/src/test/java/reviewme/security/aspect/ResourceAuthorizationUtilsTest.java
  backend/src/test/java/reviewme/security/aspect/ReviewAuthorizationAspectTest.java
  backend/src/test/java/reviewme/security/aspect/ReviewGroupAuthorizationAspectTest.java
Labels: ✨ BE

#1115 [BE] feat: 사용자 프로필 조회 api 구현
  backend/src/main/java/reviewme/member/controller/MemberController.java
  backend/src/main/java/reviewme/member/service/MemberService.java
  backend/src/main/java/reviewme/member/service/dto/ProfileResponse.java
  backend/src/test/java/reviewme/api/MemberApiTest.java
  backend/src/test/java/reviewme/member/service/MemberServiceTest.java
Labels: ✨ BE, 🚀 기능

#1113 [BE] refactor: 깃허브 인증 http method 변경, 응답 시 사용자 프로필 정보를 반환하도록 수정
  backend/src/main/java/reviewme/auth/controller/AuthController.java
  backend/src/main/java/reviewme/auth/service/AuthService.java
  backend/src/main/java/reviewme/auth/service/dto/GitHubOAuthRequest.java
  backend/src/test/java/reviewme/api/AuthApiTest.java
  backend/src/test/java/reviewme/auth/service/AuthServiceTest.java
Labels: ✨ BE

#1114 [BE] refactor: 하이라이트 api에서 요청 본문이 아닌 uri에 리뷰 정보를 포함하도록 변경
  backend/src/main/java/reviewme/highlight/controller/HighlightController.java
  backend/src/main/java/reviewme/highlight/service/HighlightService.java
  backend/src/main/java/reviewme/highlight/service/dto/HighlightsRequest.java
  backend/src/test/java/reviewme/api/HighlightApiTest.java
  backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
  backend/src/test/java/reviewme/highlight/service/mapper/HighlightMapperTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#1121 [BE] feat: 로그아웃 api 구현
  backend/src/main/java/reviewme/auth/controller/AuthController.java
  backend/src/test/java/reviewme/api/AuthApiTest.java
Labels: ✨ BE, 🚀 기능, 🍰 초간단

#1127 [BE] refactor: 중복이 허용되지 않는 컬럼에 UNIQUE 제약 조건 추가
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/resources/db/migration/V10__uique_constraint_add.sql
  backend/src/test/java/reviewme/fixture/ReviewGroupFixture.java
Labels: ✨ BE, 🍰 초간단

#1100 [BE] refactor: 회원 서비스 운영에 필요한 기본적인 회원 속성 추가
  backend/src/main/java/reviewme/member/domain/Member.java
  backend/src/main/java/reviewme/member/domain/MemberStatus.java
  backend/src/main/resources/db/migration/V10__member_email_unique.sql
  backend/src/test/java/reviewme/member/repository/MemberRepositoryTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#1090 [FE] feat: 리뷰 그룹 목록 조회 API 연동 및 MSW 핸들러 수정
  frontend/src/apis/endpoints.ts
  frontend/src/apis/review.ts
  frontend/src/components/common/EmptyContent/index.tsx
  frontend/src/components/common/EmptyContent/styles.ts
  frontend/src/components/common/NavigationTab/NavItem/index.tsx
  frontend/src/components/common/NavigationTab/NavItem/styles.ts
  frontend/src/components/common/NavigationTab/index.tsx
  frontend/src/components/common/NavigationTab/styles.ts
  frontend/src/components/layouts/Footer/style.ts
  frontend/src/components/layouts/Main/index.tsx
  frontend/src/components/layouts/Main/styles.ts
  frontend/src/components/layouts/PageLayout/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/components/ReviewInfoSection/styles.ts
  frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
  frontend/src/components/layouts/ReviewDisplayLayout/styles.ts
  frontend/src/components/layouts/Topbar/index.tsx
  frontend/src/components/layouts/Topbar/styles.ts
  frontend/src/components/reviewURL/URLGeneratorForm/index.tsx
  frontend/src/components/reviewURL/URLGeneratorForm/style.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/review.ts
  frontend/src/hooks/review/index.ts
  frontend/src/hooks/review/useGetReviewLinks/index.ts
  frontend/src/hooks/review/useGetReviewLinks/test.ts
  frontend/src/hooks/reviewGroup/useGetReviewGroupData/test.ts
  frontend/src/hooks/useNavigationTabs.ts
  frontend/src/mocks/handlers/group.ts
  frontend/src/mocks/handlers/review.ts
  frontend/src/mocks/mockData/group.ts
  frontend/src/mocks/mockData/index.ts
  frontend/src/mocks/mockData/reviewLinks.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/styles.ts
  frontend/src/pages/DetailedReviewPage/components/MultipleChoiceAnswerList/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/DetailedReviewPage/styles.ts
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkDashboard/index.tsx
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkDashboard/styles.ts
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkItem/index.tsx
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkItem/styles.ts
  frontend/src/pages/ReviewLinkPage/components/RevieweeName/index.tsx
  frontend/src/pages/ReviewLinkPage/components/RevieweeName/styles.ts
  frontend/src/pages/ReviewLinkPage/components/layouts/ReviewLinkLayout/index.tsx
  frontend/src/pages/ReviewLinkPage/components/layouts/ReviewLinkLayout/styles.ts
  frontend/src/pages/ReviewLinkPage/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewListPageContents/index.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/review.ts
  frontend/src/types/reviewGroup.ts
Labels: 🍀 FE, 🚀 기능

#1123 [BE] refactor: groupId를 받는 api를 reviewRequestCode를 받도록 변경
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/security/aspect/RequireReviewGroupAccess.java
  backend/src/main/java/reviewme/security/aspect/ReviewGroupAuthorizationAspect.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/security/aspect/AopTestClass.java
  backend/src/test/java/reviewme/security/aspect/ReviewGroupAuthorizationAspectTest.java
Labels: ✨ BE, 🛠️ 리팩터링

#1135 [BE] flyway: 반영되지 않은 스크립트 삭제
  backend/src/main/resources/db/migration/V10__add_member_base_column.sql
  backend/src/main/resources/db/migration/V10__uique_constraint_add.sql
Labels: ✨ BE, 🍰 초간단

#1139 [BE] chore: member createdAt default 값에 단위 추가
  backend/src/main/resources/db/migration/V10__add_member_base_column.sql
Labels: ✨ BE, 🍰 초간단

#1132 [BE] flyway: 중복된 ReviewRequestCode 처리
  backend/src/main/resources/db/migration/V11__uique_constraint_add.sql
Labels: ✨ BE

#1141 [BE] chore: flyway 중복 review_request_code 제거 sql 수정
  backend/src/main/resources/db/migration/V11__uique_constraint_add.sql
Labels: ✨ BE, 🫠 힘들다...

#1137 [BE] docs: dto 필드명 개선
  backend/src/main/java/reviewme/review/service/dto/response/list/AuthoredReviewElementResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewPageElementResponse.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
Labels: ✨ BE, 📋 문서, 🍰 초간단

#1130 [FE] ci: yml 파일에 추가된 환경 변수 반영
  .github/workflows/frontend-ci.yml
  frontend/.gitignore
Labels: 🍀 FE

#1153 [FE] chore: 리뷰 링크의 생성일 안내 문구를 생성일로 변경
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkItem/index.tsx
Labels: 🍀 FE, 우선순위: 상, 🍰 초간단

#1155 [FE] fix: 리뷰 링크별 받은 리뷰 목록이 제대로 뜨지 않는 문제 수정
  frontend/src/components/highlight/components/HighlightEditor/hooks/useMutateHighlight/index.ts
  frontend/src/components/layouts/ReviewDisplayLayout/hooks/useReviewInfoData/index.tsx
  frontend/src/hooks/review/useGetReviewLinks/index.ts
  frontend/src/hooks/review/useGetReviewLinks/test.ts
  frontend/src/hooks/review/useGetReviewList/index.ts
  frontend/src/hooks/reviewGroup/useCheckPasswordValidation/index.ts
  frontend/src/pages/ReviewCollectionPage/hooks/useGetGroupedReviews.ts
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkDashboard/index.tsx
  frontend/src/pages/WrittenReviewPage/hooks/useGetWrittenReviewList/index.ts
  frontend/src/pages/WrittenReviewPage/index.tsx
  frontend/src/utils/formatKeyword.ts
Labels: 🍀 FE, 🐛 버그

#1157 [FE] refactor: 작성한 리뷰, 생성한 링크 목록 쿼리를 로그아웃 시 무효화하도록 수정
  frontend/src/hooks/oAuth/useOAuthLogout.ts
  frontend/src/hooks/review/useGetReviewLinks/index.ts
  frontend/src/hooks/review/useGetReviewLinks/test.ts
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkDashboard/index.tsx
  frontend/src/pages/WrittenReviewPage/hooks/useGetWrittenReviewList/index.ts
  frontend/src/pages/WrittenReviewPage/index.tsx
Labels: 🍀 FE, 🐛 버그

#1147 [BE] fix: 새로운 세션을 만들지 않게 수정
  backend/src/main/java/reviewme/auth/controller/AuthController.java
  backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
  backend/src/main/java/reviewme/member/controller/MemberController.java
  backend/src/main/java/reviewme/security/aspect/ResourceAuthorizationUtils.java
  backend/src/main/java/reviewme/security/aspect/ReviewAuthorizationAspect.java
  backend/src/main/java/reviewme/security/aspect/ReviewGroupAuthorizationAspect.java
  backend/src/main/java/reviewme/security/resolver/GuestReviewGroupSessionResolver.java
  backend/src/main/java/reviewme/security/resolver/LoginMemberSessionResolver.java
  backend/src/main/java/reviewme/security/session/SessionManager.java
  backend/src/test/java/reviewme/global/session/SessionManagerTest.java
  backend/src/test/java/reviewme/security/aspect/ResourceAuthorizationUtilsTest.java
  backend/src/test/java/reviewme/security/aspect/ReviewAuthorizationAspectTest.java
  backend/src/test/java/reviewme/security/aspect/ReviewGroupAuthorizationAspectTest.java
  backend/src/test/java/reviewme/security/resolver/GuestReviewGroupSessionResolverTest.java
  backend/src/test/java/reviewme/security/resolver/LoginMemberSessionResolverTest.java
Labels: ✨ BE, 우선순위: 상, 🐛 버그

#1160 [FE] fix : 비밀번호 확인 코드 API 엔드포인트 수정, 로그아웃 시 쿼리 캐싱 문제 해결
  frontend/src/apis/endpoints.ts
  frontend/src/hooks/oAuth/useOAuthLogout.ts
Labels: 우선순위: 상, 🐛 버그, 😱 긴급

#1164 [FE] fix: 답변 모아보기에서, 받은 서술형 답변이 없을 때 EmptyContent 렌더링
  frontend/src/pages/ReviewCollectionPage/components/ReviewCollectionPageContents/index.tsx
Labels: 우선순위: 중, 🐛 버그

#1165 [FE] fix: 작성한 리뷰 확인 페이지 401 응답 메세지 오류 수정
  frontend/src/components/error/ErrorSection/index.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/pages/WrittenReviewPage/components/PageContent/index.tsx
  frontend/src/pages/WrittenReviewPage/index.tsx
Labels: 우선순위: 상, 🐛 버그, 🫠 힘들다..., 💪 아자아자!!

#1167 [BE] refactor: 회원이 리뷰 그룹을 인증하면, 해당 리뷰 그룹에 접근할 수 있도록 수정
  backend/src/main/java/reviewme/review/domain/Review.java
  backend/src/main/java/reviewme/reviewgroup/domain/ReviewGroup.java
  backend/src/main/java/reviewme/security/aspect/ReviewAuthorizationAspect.java
  backend/src/main/java/reviewme/security/aspect/ReviewGroupAuthorizationAspect.java
  backend/src/test/java/reviewme/security/aspect/ReviewAuthorizationAspectTest.java
  backend/src/test/java/reviewme/security/aspect/ReviewGroupAuthorizationAspectTest.java
Labels: ✨ BE, 우선순위: 상

#1173 [FE] fix: 로그아웃 시, 변경된 사용자 프로필 캐시 적용안되는 오류 수정
  frontend/src/components/error/ErrorSection/index.tsx
  frontend/src/components/error/ErrorSection/styles.ts
  frontend/src/components/profile/ProfileInfo/index.tsx
  frontend/src/hooks/oAuth/useOAuthLogout.ts
Labels: 🍀 FE, 우선순위: 상, 🐛 버그

#1177 [FE] fix: 작성한 리뷰 페이지에서의 상세 리뷰 maxWidth 수정
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/pages/WrittenReviewPage/components/DetailedWrittenReview/styles.ts
  frontend/src/styles/theme.ts
Labels: 🍀 FE, 우선순위: 상, 🐛 버그, 🎨 디자인

#1179 [FE] fix: 링크 페이지, 작성한 리뷰 확인 페이지 외에 다른 페이지에서 NavigationTab 비활성화
  frontend/src/components/common/NavigationTab/index.tsx
  frontend/src/hooks/useNavigationTabs.ts
Labels: 🍀 FE, 🍰 초간단
