Repository woowacourse-teams/2024-review-me, pull requests merged in 2025-01, with the labels that each got.

#1034 [FE] chore: 타입, 인터페이스의 이름을 PascalCase로 강제하는 eslint 규칙 추가
  frontend/.eslintrc.cjs
Labels: 🍀 FE, 우선순위: 중, 🍰 초간단

#1027 [FE] feat : ErrorSuspense에 fallback 수정
  frontend/src/components/error/ErrorSuspenseContainer/index.tsx
  frontend/src/pages/DetailedReviewPage/index.tsx
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/pages/ReviewListPage/index.tsx
Labels: 🍀 FE, 🚀 기능

#1024 [FE] feat : 받은, 작성한 리뷰 없을 때 보여주는 돋보기 컴포넌트 생성
  frontend/src/assets/emptyContentIcon.svg
  frontend/src/components/common/EmptyContent/index.tsx
  frontend/src/components/common/EmptyContent/styles.ts
  frontend/src/components/common/index.tsx
  frontend/src/styles/theme.ts
Labels: 🍀 FE, 🍰 초간단

#1035 [FE] feat: 사용자 프로필 정보 및 프로필 탭 구현
  frontend/src/assets/github.svg
  frontend/src/assets/logout.svg
  frontend/src/assets/menu.svg
  frontend/src/assets/openedBook.svg
  frontend/src/assets/user.svg
  frontend/src/components/common/UndraggableWrapper/styles.ts
  frontend/src/components/layouts/Topbar/styles.ts
  frontend/src/components/profile/ProfileInfo/index.tsx
  frontend/src/components/profile/ProfileInfo/styles.ts
  frontend/src/components/profile/ProfileTab/components/ActionItem/index.tsx
  frontend/src/components/profile/ProfileTab/components/ActionItem/styles.ts
  frontend/src/components/profile/ProfileTab/components/Divider/index.tsx
  frontend/src/components/profile/ProfileTab/components/Divider/styles.ts
  frontend/src/components/profile/ProfileTab/components/ReadonlyItem/index.tsx
  frontend/src/components/profile/ProfileTab/components/ReadonlyItem/styles.ts
  frontend/src/components/profile/ProfileTab/hooks/useProfile.tsx
  frontend/src/components/profile/ProfileTab/hooks/useProfileTabElements.tsx
  frontend/src/components/profile/ProfileTab/index.tsx
  frontend/src/components/profile/ProfileTab/styles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/profile.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능

#1039 [FE] refactor: ReviewCard에서 강점 키워드를 표시하는 ReviewKeyword 컴포넌트 분리 및 불필요한 예시 제거
  frontend/src/components/common/OptionSwitch/styles.ts
  frontend/src/components/common/ReviewCard/index.tsx
  frontend/src/components/common/ReviewCard/styles.ts
  frontend/src/components/common/ReviewDate/index.tsx
  frontend/src/components/common/ReviewDate/styles.ts
  frontend/src/components/common/ReviewKeyword/index.tsx
  frontend/src/components/common/ReviewKeyword/styles.ts
  frontend/src/mocks/mockData/detailedReviewMockData.ts
  frontend/src/mocks/mockData/reviewListMockData.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/styles.ts
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/KeywordSection/styles.ts
  frontend/src/pages/DetailedReviewPage/components/MultipleChoiceAnswer/index.tsx
  frontend/src/pages/DetailedReviewPage/components/MultipleChoiceAnswerList/index.tsx
  frontend/src/pages/DetailedReviewPage/components/MultipleChoiceAnswerList/styles.ts
  frontend/src/pages/DetailedReviewPage/components/QuestionAnswerSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/QuestionAnswerSection/styles.ts
  frontend/src/pages/DetailedReviewPage/components/QuestionTitle/index.tsx
  frontend/src/pages/DetailedReviewPage/components/QuestionTitle/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
  frontend/src/pages/DetailedReviewPage/components/ReviewSection/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewSectionHeader/index.tsx
  frontend/src/pages/DetailedReviewPage/components/ReviewSectionHeader/styles.ts
  frontend/src/pages/DetailedReviewPage/components/index.tsx
  frontend/src/pages/ReviewListPage/components/ReviewListPageContents/index.tsx
  frontend/src/utils/formatKeyword.ts
Labels: 🍀 FE, 🛠️ 리팩터링, 🎨 디자인

#1040 [FE] feat: 뒤로 가기 버튼 구현
  frontend/src/assets/backButton.svg
  frontend/src/components/common/BackButton/index.tsx
  frontend/src/components/common/BackButton/styles.ts
  frontend/src/pages/DetailedReviewPage/components/DetailedReviewPageContents/index.tsx
  frontend/src/pages/ReviewCollectionPage/index.tsx
  frontend/src/pages/ReviewListPage/index.tsx
Labels: 🍀 FE, 🚀 기능

#1022 [FE] feat: 소셜 연동 로그인 버튼 및 로그인 요청 모달
  frontend/src/assets/githubWhiteLogo.svg
  frontend/src/components/common/modals/index.tsx
  frontend/src/components/index.tsx
  frontend/src/components/login/GithubLoginButton/index.tsx
  frontend/src/components/login/LoginButton/index.tsx
  frontend/src/components/login/LoginButton/styles.ts
  frontend/src/components/login/LoginRequestModal/index.tsx
  frontend/src/components/login/LoginRequestModal/styles.ts
  frontend/src/components/login/index.ts
  frontend/src/pages/ReviewZonePage/index.tsx
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 🎨 디자인

#1032 [FE] feat: 리뷰 링크 관리 페이지와 라우터 설정 추가
  frontend/src/components/layouts/Footer/style.ts
  frontend/src/components/layouts/Topbar/components/Logo/styles.ts
  frontend/src/constants/amplitudeEventName.ts
  frontend/src/constants/route.ts
  frontend/src/pages/HomePage/components/URLGeneratorForm/styles.ts
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkDashboard/index.tsx
  frontend/src/pages/ReviewLinkPage/components/ReviewLinkDashboard/styles.ts
  frontend/src/pages/ReviewLinkPage/components/layouts/ReviewLinkLayout/index.tsx
  frontend/src/pages/ReviewLinkPage/components/layouts/ReviewLinkLayout/styles.ts
  frontend/src/pages/ReviewLinkPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/router.tsx
Labels: 🍀 FE, 🚀 기능, 🎨 디자인

#1014 [BE] docs: GitHub 연동, 자신이 만든 리뷰 그룹 목록 조회 API 문서 작성
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/reviewgroup.adoc
  backend/src/main/java/reviewme/auth/controller/AuthController.java
  backend/src/main/java/reviewme/auth/service/AuthService.java
  backend/src/main/java/reviewme/auth/service/dto/GithubCodeRequest.java
  backend/src/main/java/reviewme/member/controller/MemberController.java
  backend/src/main/java/reviewme/member/service/MemberService.java
  backend/src/main/java/reviewme/member/service/dto/ProfileResponse.java
  backend/src/main/java/reviewme/review/controller/ReviewController.java
  backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewPageElementResponse.java
  backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewPageResponse.java
  backend/src/main/java/reviewme/review/service/mapper/ReviewListMapper.java
  backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
  backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupPageElementResponse.java
  backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupPageResponse.java
  backend/src/test/java/reviewme/api/ApiTest.java
  backend/src/test/java/reviewme/api/AuthApiTest.java
  backend/src/test/java/reviewme/api/MemberApiTest.java
  backend/src/test/java/reviewme/api/ReviewApiTest.java
  backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
  backend/src/test/java/reviewme/review/service/ReviewListLookupServiceTest.java
  backend/src/test/java/reviewme/review/service/mapper/ReviewListMapperTest.java
Labels: ✨ BE, 📋 문서

#1053 [BE] hotfix: 캐싱 제거
  backend/src/main/java/reviewme/template/service/mapper/TemplateMapper.java
Labels: ✨ BE, 🐛 버그, 🍰 초간단

#1052 [FE] ci : 환경변수 추가, 프리플라이트 추가
  .github/workflows/frontend-ci.yml
Labels: 🍀 FE

#1038 [FE] 작성한 리뷰를 확인할 수 있는 반응형 레이아웃
  frontend/src/assets/slideArrows.svg
  frontend/src/components/ReviewListItem/index.tsx
  frontend/src/components/ReviewListItem/styles.ts
  frontend/src/constants/amplitudeEventName.ts
  frontend/src/constants/route.ts
  frontend/src/hooks/useSearchParamAndQuery.ts
  frontend/src/pages/WrittenReviewPage/components/DetailedWrittenReview/index.tsx
  frontend/src/pages/WrittenReviewPage/components/DetailedWrittenReview/styles.ts
  frontend/src/pages/WrittenReviewPage/components/NoSelectedReviewGuide/index.tsx
  frontend/src/pages/WrittenReviewPage/components/NoSelectedReviewGuide/styles.ts
  frontend/src/pages/WrittenReviewPage/components/WrittenReviewList/index.tsx
  frontend/src/pages/WrittenReviewPage/components/WrittenReviewList/styles.ts
  frontend/src/pages/WrittenReviewPage/components/index.tsx
  frontend/src/pages/WrittenReviewPage/components/layouts/PageContentLayout/index.tsx
  frontend/src/pages/WrittenReviewPage/components/layouts/PageContentLayout/styles.ts
  frontend/src/pages/WrittenReviewPage/components/layouts/index.tsx
  frontend/src/pages/WrittenReviewPage/hooks/index.ts
  frontend/src/pages/WrittenReviewPage/hooks/useDeviceBreakpoints/index.ts
  frontend/src/pages/WrittenReviewPage/index.tsx
  frontend/src/pages/WrittenReviewPage/styles.ts
  frontend/src/pages/index.tsx
  frontend/src/router.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.ts
  frontend/src/types/media.ts
  frontend/src/utils/media.ts
Labels: 🍀 FE, 우선순위: 상, 🚀 기능, 🎨 디자인, 💭 고민거리

#1055 [FE] feat : 이미지 스켈레톤 적용
  frontend/src/components/index.tsx
  frontend/src/components/skeleton/ImgWithSkeleton/index.tsx
  frontend/src/components/skeleton/ImgWithSkeleton/style.ts
  frontend/src/components/skeleton/index.tsx
  frontend/src/pages/HomePage/components/InfinityCarousel/index.tsx
  frontend/src/pages/HomePage/components/InfinityCarousel/styles.ts
  frontend/src/pages/HomePage/hooks/useSlideImgSize.tsx
  frontend/src/pages/ReviewZonePage/index.tsx
  frontend/src/pages/ReviewZonePage/styles.ts
Labels: 🍀 FE, 🚀 기능

#1047 [BE] chore: profile에 따라 다른 H2 의존성 옵션 추가
  backend/build.gradle
Labels: ✨ BE, 🍰 초간단

#1071 [BE] fix: Flyway 스크립트 DDL 문법 오류 수정
  backend/src/main/resources/db/migration/V4__template_association.sql
Labels: 🐛 버그, 🍰 초간단

#1067 [BE] chore: 롬복 설정에서 불필요한 부분 제거
  backend/build.gradle
Labels: ✨ BE, 🍰 초간단

#1064 [FE] feat : 리뷰 생성 중 UI 구현
  frontend/src/components/index.tsx
  frontend/src/components/loading/BlinkLoader/index.tsx
  frontend/src/components/loading/BlinkLoader/style.ts
  frontend/src/components/loading/index.tsx
  frontend/src/components/reviewURL/URLGeneratorForm/components/URLGeneratorButton/index.tsx
Labels: 🍀 FE, 🚀 기능, 🎨 디자인, 🍰 초간단

#1070 [FE] refactor : 회원 전용 페이지 path 수정
  frontend/src/constants/amplitudeEventName.ts
  frontend/src/constants/route.ts
  frontend/src/utils/index.ts
  frontend/src/utils/path.ts
Labels: 🍀 FE, 🛠️ 리팩터링, 🍰 초간단
